### ISSUE TITLE
Built-in support for history api fallback

### ISSUE THREAD

**Issue by jsonmaur** [webpack-contrib/webpack-serve#107]
As I understand it, in order to implement this I have to follow the example [here](https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/history-fallback.config.js). I definitely think this should be built into webpack-serve itself, as it is a pretty universal requirement for webpack development servers. I don't want to install two external dependencies to get it to work (`connect-history-api-fallback` and `koa-connect`), and this is a big holdback coming from webpack-dev-server.

I'm probably unaware of the details that went into making this decision, but that's just my two cents.

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.

**Comment by aaronbeall** [comment]
I agree with @jsonmaur I would expect this to be a built-in feature. It's interesting that Webpack 4 went the direction of making *more* built in for ease of use, but dev-server went the direction of making *less* built in which makes it less easy to use.

**Comment by shellscape** [comment]
(`dev-server` went in no direction haha. I think you may be mixing your module names)

With `webpack-serve` it was decided to learn from past mistakes in `dev-server`. A development server is not there to cater to the needs of every single user in an ecosystem. Quite to the contrary, it should cater to common needs, and allow users to easily extend it. Such is the case for `express` and `koa` and users familiar with those two server staples should recognize the patterns used to extend webpack-serve. It's reasonable for developers to expect to be able to extend a tool, but it's not reasonable for a developer to pick up a tool and demand that it has built-ins to cater to their every need. Remember: your needs are subjective as is the opinion that the module is less easy to use - there is an entire ecosystem to consider. Where you see disadvantage, others see more freedom and less restriction by the tool to use what middleware they want to use in whatever order they choose.

If you find using server middleware to be a difficult paradigm to grasp, then there's a great opportunity there to expand your knowledge base and add to your marketable skills, as that's a common need these days. Learning that paradigm will open your world to a veritable feast of possibilities for extending `webpack-serve` to your whims, and will surely benefit you in the future with other industry standard server platforms on Node.js.
