### ISSUE TITLE
[Question]What's the best way to define --mode dev and production?

### ISSUE THREAD

**Issue by AndreasGalster** [webpack-contrib/webpack-serve#109]
I've just started using webpack-serve, works great :). However I'm not sure how to define the mode to be used in webpack-serve. I tried a config via a function exported, which seems not supported. When I console log the mode, it says development, but when webpack compiles it warns me that the mode is not defined and defaults to production.

Does webpack-serve default to development mode or not? I think compilation is pretty slow, so I'm guessing it is indeed using production mode. There seems to be no --mode flag for webpack serve to solve this.

**Comment by JoccaWeb** [comment]
I found that it's enough to add "mode: 'production'," between 
"module.exports = {" and 
"module: {" in webpack.config.js, to make the mode warning go away.
Hope this is clear and helpful...

btw: Webpack (4) defaults to production mode when not configured, not webpack-serve if i'm right.

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.
