### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by m4ss1m0g** [webpack-contrib/webpack-serve#112]
* Operating System: **Windows 10**
* Node Version: **v8.11.1**
* NPM Version: **5.8.0**
* webpack Version: **4.6.0**
* webpack-serve Version: **0.3.2**
* Browser: **Chrome Version 66.0.3359.139 (Official Build) (64-bit)**

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [ ] **modification** request
- [X] **Question/Improvement** request see #92 

### Folder structure

dist\output.js
src\app.js
Index.html
package.json
webpack.config.js

##### src/app.js
```js
// file src/app.js
alert("Hello Word");
```

##### CLI Command
_See the package.json below_
```console
  $ npm run live 
```

##### webpack.config.js

```js
const path = require('path');

module.exports = {
    entry: {
      index: [path.resolve(__dirname, 'src', 'app.js')]
    },
    mode: 'development',
    output: {
      filename: 'output.js'
    }
  };
```

##### package.json

```js
{
  "name": "testserve",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "webpack",
    "live": "webpack-serve ./webpack.config.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^4.6.0",
    "webpack-cli": "^2.1.2",
    "webpack-serve": "^0.3.2"
  }
}

```

### Expected Behavior

Load and execute the code on output.js

### Actual Behavior

When navigate to http://localhost:8080 the browser log 
**404 NotFound** for dist\output.js

### How Do We Reproduce?

See above

### Note

I understand that webpack-serve do not output nothing to dist folder and compile in memory I see #92 , but how to setup a minimal working config ? You can add on README ?

**Comment by shellscape** [comment]
@m4ss1m0g please see the issue template for support options, and that is what you are seeking here.

>  👉🏽 Need support, advice, or help? Don't open an issue.
  Head to StackOverflow or https://gitter.im/webpack/webpack.

there are a litany of examples in the `tests` as well that you can reference.

**Comment by m4ss1m0g** [comment]
I disagree. 
Good software must provide a minimum working example on the README page.
This is my opinion.

**Comment by shellscape** [comment]
Here is a minimum working example: https://github.com/webpack-contrib/webpack-serve/blob/master/test/fixtures/basic/webpack.config.js. Feel free to add it to the README via a Pull Request
