### ISSUE TITLE
Re-use current tab instead of open a new one

### ISSUE THREAD

**Issue by elrumordelaluz** [webpack-contrib/webpack-serve#117]
* Operating System: OSX
* Node Version: 8.11.0
* NPM Version: 6.0.0
* webpack Version: 4.7.0
* webpack-serve Version: 0.3.2

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

##### CLI Command

```console
  $ webpack-serve ... # remove this block if using the API
```

##### webpack.config.js

```js
  // If your bitchin' code blocks are over 20 lines, please paste a link to a gist
  // (https://gist.github.com).
```

```js
  // additional code, HEY YO remove this block if you don't need it
```

### Expected Behavior

Try to refresh the current _browser_ window

### Actual Behavior

Open always a new tab

### New Feature Use Case

Inspired on `create-react-app` solution.

Since I usually use _Google Chrome_, I expect to stay in the same (current) _browser_ tab
when re-launch `webpack-serve`, instead of use a new one and close those more.

Just curious if the _Webpack_ people/ecosystem are interested in having this behaviour (will PR in case), since is very specific to _Chrome_ browser in _OSX_ platform.

Furthermore, the solution requires to have an extra file `.applescript` in the _package_.

Thoughts?

[related](https://github.com/webpack/webpack-dev-server/issues/1400#issuecomment-387093963)

**Comment by shellscape** [comment]
@elrumordelaluz thanks for the issue 🍺 

If you can find a way to make that happen with https://github.com/sindresorhus/opn, you probably won't need a custom feature or option in `webpack-serve`, as we allow passing through most options already, and that module handles opening up your browser of choice.

**Comment by elrumordelaluz** [comment]
`create-react-app` uses `opn` but [tries to open the same _tab_](https://github.com/facebook/create-react-app/blob/25184c4e91ebabd16fe1cde3d8630830e4a36a01/packages/react-dev-utils/openBrowser.js#L65-L86) using `.applescrip`

**Comment by shellscape** [comment]
I would recommend using the [`listening`](https://github.com/webpack-contrib/webpack-serve#events) event and running that AppleScript locally. That's just too much complexity for this project for a single browser on a single platform.

If you'd like to contribute an `applescript` file to the repo in the `docs` directory, we can add a note tlo the `open` option, and an example of how to accomplish that on a per-user basis.

**Comment by elrumordelaluz** [comment]
> That's just too much complexity for this project for a single browser on a single platform.

Absolutely agree

> If you'd like to contribute an applescript file to the repo in the docs

Sound good for me

**Comment by shellscape** [comment]
Well it's licensed under MIT, so you'd have to keep that header in it if you were going to use it verbatim. 

> The example could fit in Readme?

No, but we'd put a link to a directory in the `docs` directory, which would contain the example snippet needed.

**Comment by elrumordelaluz** [comment]
Cool, so will add the `.applescript` file and another `reuse-current-tab.js` with the `serve` config
