### ISSUE TITLE
How do I detect if webpack rebuilds bundle?

### ISSUE THREAD

**Issue by ctaylo21** [webpack-contrib/webpack-serve#121]
* Operating System: MacOSX
* Node Version: 9.8
* NPM Version: 5.6
* webpack Version: 4.5
* webpack-serve Version: 0.3.2

This issue is for a:

- [ ] **bug**
- [X] **feature** request
- [ ] **modification** request

### New Feature Use Case
I might have missed this in the docs, but how could I listen to the event where webpack rebuilds the bundle due to a change?

I can listen to the initial load with:
```
serve({ config }).then((server) => {
  server.on('listening', () => {
    // Run code after server is ready
  });
});
```
How about any subsequent rebuilds?

**Comment by shellscape** [comment]
@ctaylo21 thanks for the issue :beer:

Interesting one; pseudo-support, pseduo-feature request.  We had [this issue](https://github.com/webpack-contrib/webpack-serve/issues/3) for event feedback open for a while but didn't get any feedback on it.

We're encouraging people to use `WebSockets` and connect to the serve for getting notifications that are identical to what the browser `WebSocket` receives, but if that's too much trouble for a simple operation, we can add some additional events. If you're planning on doing a lot of work with the various compilation events though, I'd recommend the `WebSocket` approach as it's much more useful.

**Comment by shellscape** [comment]
> and then running it with mocha-headless-chrome.

boooooooooo. you should totes use [`mocha-chrome`](https://github.com/shellscape/mocha-chrome) (disclaimer: `mocha-chrome` is one of my other modules)

> Ideally I can find a way to re-run tests when something changes and the bundle gets rebuilt.

In that case I think that a `WebSocket` would be overkill, but it'll get you off the ground immediately. An event is probably going to be a better approach for your needs long term, as it's way simpler. A `WebSocket` does give you the added advantage of being able to create it and connect in any context on your machine (or even your network).

Here is the compiler hook for when a compilation finishes: https://github.com/webpack-contrib/webpack-hot-client/blob/master/index.js#L104

Here's the intermediary that actually sends data to the connected client sockets: https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/util.js#L117

And here's the client-side handler function (method names represent message "type"): https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/client/index.js#L43

The message types you'll probably want to listen for are `compile` and `ok`. Granted, these weren't really named for consumption outside of the the module (`webpack-hot-client`) so there's going to be a small learning curve there.

In the mean time, if you have any other suggestions for events that would make your world more convenient, please follow up on issue #3, and we'll re-open that and get to work.

**Comment by ctaylo21** [comment]
> boooooooooo. you should totes use mocha-chrome (disclaimer: mocha-chrome is one of my other modules)

I'll gladly switch since you've been awesome :)

I initially implemented this by creating an incredibly basic plugin that tapped into ["done" compiler hook](https://webpack.js.org/api/compiler-hooks/#done). That seemed to work as needed, but it also seemed like overkill since I only ever listened to that single event.
```
const { runner } = require('mocha-headless-chrome');

export default class MochaPuppeteer {
  constructor(options) {
    this.options = options;
  }

  apply(compiler) {
    compiler.hooks.done.tap('MochaPuppeteer', () => {
      runner(this.options)
        .then(() => {
          // Done
        }).catch((e) => {
          // Error
        });
    });
  }
}
```
Any opinions on just using that strategy (with your headless chrome library of course!) vs listening to web socket events?
