### ISSUE TITLE
Documentation: browser compatibility

### ISSUE THREAD

**Issue by mischkl** [webpack-contrib/webpack-serve#13]
This issue is for a:

- [x] **documentation improvement**

According to the `webpack-dev-server` documentation, `webpack-serve` can only be used if "old browsers" don't need to be supported.

The information about which browser versions aren't compatible is missing, however. It would be great if a list of minimum browser versions could be added to the `webpack-serve` documentation.

**Comment by shellscape** [comment]
Good catch. Neglected to copy the relevant information from webpack-hot-client. I'll update that now. In the future, please leave the template intact 🍻

**Comment by mischkl** [comment]
@shellscape Great, thanks. I only modified the template because it didn't seem like any of it was relevant to documentation. Maybe the template can be adjusted to accommodate for such cases? :beers:

**Comment by mischkl** [comment]
Also just to double check, this means IE11 is supported? If so that's great news for us! :smiley:

**Comment by shellscape** [comment]
Yessir, IE11 supports native `WebSocket` 🎉 

If you have suggestions on how the issue template can be updated to better suit documentation issues, please do let me know!
