### ISSUE TITLE
[Bug] Serve port and hot port conflict on Windows

### ISSUE THREAD

**Issue by meteorlxy** [webpack-contrib/webpack-serve#135]
* Operating System: Windows 10
* Node Version: v8.11.1
* NPM Version: v5.5.1 (yarn v1.6.0)
* webpack Version: 4.8.1
* webpack-serve Version: 0.3.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### API

```js
const serve = require('webpack-serve')
const compiler = /* our compiler */
serve({
    compiler,
    host,
    port: 8081
})
```

### Expected Behavior

Works well

### Actual Behavior
```
｢serve｣:  { Error: listen EADDRINUSE 127.0.0.1:8081
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
```
### How Do We Reproduce?
 It's related to:
https://github.com/webpack-contrib/webpack-serve/blob/c9235b5fc5135257809c15994b84b03088afd211/lib/server.js#L117-L118

If all ports are free, only `8081` port have this error. As those two `getPort`s will both find port from `8081` and then use the same port.

The core problem is that those two `getPort`s have the possibility to get a some port and cause conflict

> We noticed that at https://github.com/vuejs/vuepress/issues/424

**Comment by shellscape** [comment]
@meteorlxy this isn't a bug - that's the default port for the `WebSocket` server. If you're choosing to use that as the primary web serve's port as well, then you're configuring this for failure out of the gate. The solution is simply not to do that.

**Comment by meteorlxy** [comment]
@shellscape 
It's possible that, set the `primary web serve's port` as 8080 our smaller, but from `primary web serve's port`  to `8080` are all in used, then the first `getPort` will choose 8081 and cause this error, too.

I think we could make it cleverer to avoid it.
