### ISSUE TITLE
Browser keeps refreshing with multiple entry points/configurations

### ISSUE THREAD

**Issue by ematipico** [webpack-contrib/webpack-serve#139]
* Operating System: Windows 7
* Node Version: 6.10
* NPM Version: 5.3.0
* webpack Version: 4.6.0
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

```js
const config = require('webpack.config')
serve({
 config,
 logLevel: 'trace',
 dev: {
   publichPath: '/'
 },
 add: (app, middleware) => {
   middleware.webpack();
   middleware.content({
      index: 'index.html'
   });
 }
});
```

##### webpack.config.js

```js
module.exports = [
  {
     entry: {
       index: [path.resolve(__dirname, 'app.js')],
     },
     mode: 'development',
     output: {
       filename: 'output.js',
     }
  }
  {
     entry: {
       index: [path.resolve(__dirname, 'iframe-app.js')],
     },
     mode: 'development',
     output: {
       filename: 'iframe-bundle.js',
     }
  }
]
```

```html
<!-- index.html from where I serve my bundles -->

<html>
  <body>
      <iframe src="http://localhost:8080/iframe.html">

      </iframe>
     <script src="output.js"></script>
  </body>
</html>
```

```html
<!-- iframe.html where I load the second bundle -->

  <div>
     <script src="iframe-bundle.js"></script>
  </div>
```

### Expected Behavior

It should serve both bundles without refreshing the whole web page.

### Actual Behavior

The browsers keeps refreshing every time the iframe gets rendered and loads the second output.

### How Do We Reproduce?

I managed to have the same 'refreshing loop' by having two entry points that are loaded in the same page or by recreating a situation like mine (which could take longer).

I am note sure if it is a real bug of I am using `webpack-serve` not correctly. I am here to seek advice.

**Comment by shellscape** [comment]
Thanks for the issue, but this would be a `webpack-hot-client` bug. Can you open it there instead?

**Comment by ematipico** [comment]
It's now done :) 
https://github.com/webpack-contrib/webpack-hot-client/issues/61

**Comment by shellscape** [comment]
Thanks 🍺
