### ISSUE TITLE
Catch clipboardy errors?

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack-contrib/webpack-serve#14]
* Operating System: Win 10
* Node Version: 8.9
* NPM Version: 5.6
* webpack Version: 4 beta
* webpack-serve Version: 1.0.0-beta.1

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Code

https://github.com/webpack-contrib/webpack-serve/blob/68380abb2b6202f8f811b82ce58a5408d202f130/lib/server.js#L100-L101

##### webpack.config.js

```js
  // any config
```

### Expected Behavior

Warn if clipboardy fails.

### Actual Behavior

Error if clipboarfy fails. Can't use webpack-serve.

---

clipboardy can fail because of several reasons (e.g. [this one](https://github.com/sindresorhus/clipboardy/blob/master/lib/linux.js#L7)). It would be nice, if webpack-serve would catch these errors and show a warning instead of failing completely, as this is more of an optional feature.

**Comment by donaldpipowitch** [comment]
Maybe just changing it to this?

```js
            try {
              clip.writeSync(uri);
              log.info(chalk.grey('Server URI copied to clipboard'));
            } catch (err) {
              log.warn(chalk.grey('Couldn\'t copy Server URI to clipboard, because of this error:'));
              log.warn(err);
            }
```

![image](https://user-images.githubusercontent.com/1152805/36591397-32568b16-1892-11e8-8487-450c81fa38b2.png)

**Comment by shellscape** [comment]
Thanks for reporting that. I was curious if that was going to fail or not, and as crazy as it might seem, I didn't swallow that error to see if it was going to be stable enough for enough people to keep it in there. (which is OK for a 0.x version space).

I'll get a try/catch in there for that shortly.

**Comment by shellscape** [comment]
v0.1.4 is up 🚀

**Comment by donaldpipowitch** [comment]
Thank you.
