### ISSUE TITLE
--require and -r options are broken

### ISSUE THREAD

**Issue by jdalton** [webpack-contrib/webpack-serve#140]
Reposting as a new issue from https://github.com/webpack-contrib/webpack-serve/issues/138#issuecomment-389534909:

Ok, after digging into this a bit the issue does appear to be a `webpack-serve` issue.

`webpack-serve` receives the `-r` or `--require` as `options.flags` but then does not pass them off to `config-loader` which expects a `options.require`. 

Receiving as `options.flags`
https://github.com/webpack-contrib/webpack-serve/blob/f7842c4c684706fa94ca032d718948ce9cabe83c/cli.js#L71-L74

Still `options.flags`
https://github.com/webpack-contrib/webpack-serve/blob/f7842c4c684706fa94ca032d718948ce9cabe83c/lib/options.js#L59-L62

Passing to `config-loader` as `options.require`
https://github.com/webpack-contrib/webpack-serve/blob/f7842c4c684706fa94ca032d718948ce9cabe83c/lib/config.js#L60-L86

**Comment by shellscape** [comment]
Resolved in 9ef5b293a62f83920ab6d05d231d2c8d4f9e22a7

**Comment by oles** [comment]
Awesome - thank you both ❤️

**Comment by alexperrault** [comment]
Thank you for the hard work !
@shellscape, any chance this hotfix could be released before the rest of the branch it is currently on (test/ava) ?

**Comment by shellscape** [comment]
@alexperrault no, sorry. Please have patience.

**Comment by jdalton** [comment]
Hi @shellscape!

Is there anything I can help with?

**Comment by shellscape** [comment]
Nope. https://github.com/webpack-contrib/webpack-serve/commits/master

**Comment by jdalton** [comment]
Oh, I know it was merged 😋  
I was more asking if there's anything I can help with to bump the release is all.

**Comment by shellscape** [comment]
@jdalton that's just a passive-aggressive alternative to asking when the release will be published. please refrain from that in the future, it is not welcome.
