### ISSUE TITLE
No error on start up when websocket port (8081) unavailable

### ISSUE THREAD

**Issue by radicaled** [webpack-contrib/webpack-serve#141]
* Operating System: macOS 10.13
* Node Version: Node 8
* NPM Version: 5.5.1
* webpack Version: 4.8.1
* webpack-serve Version: 0.3.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve webpack.config.js
```

### Expected Behavior

If I have another process using the websocket port 8081 (for instance, this is the port that the React Native package manager uses), then I expect to see a message from webpack-serve telling me that the port is unavailable and hot reload, etc, won't work.

### Actual Behavior

webpack-serve silently continues, implying everything is fine.

### How Do We Reproduce?

Run any process that takes over port 8081

**Comment by shellscape** [comment]
That is not a bug, but by design. The console output will indicate what port things are running on. Behold, terminal output from running two instances of the same config at the same time:

```console
# terminal 1
→ node cli.js --config test/fixtures/basic/webpack.config.js
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
ℹ ｢serve｣: Project is running at http://localhost:8080
```

```console
# terminal 2
→ node cli.js --config test/fixtures/basic/webpack.config.js
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: WebSocket Server Listening at localhost:54425
ℹ ｢serve｣: Project is running at http://localhost:54426
```

You might then say "but this is not useful to me, I expect an error" and you indeed might. But years of user history of webpack tooling has told us that the vast majority of users prefer when the server makes use of a fallback port. You'll find similar behavior in `webpack-dev-server` as well. Unfortunately, this will not change anytime soon.

**Comment by radicaled** [comment]
> That is not a bug, but by design.

Interesting that in your tests webpack correctly changed ports:

Terminal 1
```
$ node node_modules/react-native/local-cli/cli.js start
Scanning folders for symlinks in /Users/arron/Projects/smiletime/gather-mobile/node_modules (32ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
```

(react native has indeed taken over port 8081 with a http server that will upgrade certain requests to a full-fledged websocket connection)

Terminal 2
```
$ webpack-serve --config ./webpack.config.js --no-clipboard
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
ℹ ｢serve｣: Project is running at http://localhost:8080
ℹ ｢hot｣: webpack: Compiling Done
ℹ ｢wdm｣: Hash: a0b13afaf04420a2453b
```

Personally I'd still consider the behavior a bug, but I'm afraid I can't devote any time to tracking it down right now. Hope this helps anyone who encounters it in the future, though.
