### ISSUE TITLE
HMR client attaches only to first entry

### ISSUE THREAD

**Issue by rmanoka** [webpack-contrib/webpack-serve#145]
* Operating System: x86_64 GNU/Linux
* Node Version: v8.11.2
* NPM Version: 5.6.0
* webpack Version: 4.8.3
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

A simple two entry config, with two independent HTML files that serve the two entries.  HMR loads on the first, not the second.  Please scroll below for github repository for minimal example.

##### CLI Command

```console
  $ npx webpack-serve
```

##### webpack.config.js

```js
module.exports = {
  mode: 'development',
  entry: {
    main: './src',
    second: './second',
  }
}
```

```js
// src.js
console.log('src loaded.');
```

```js
// second.js
console.log('second src loaded.');
```

Also need two separate HTML files to load the two entries.

First one:  index.html

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Page Title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="main.js"></script>
</head>
<body>
</body>
</html>
```

Second:  say second.html

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Page Title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="second.js"></script>
</head>
<body>
</body>
</html>
```

### Expected Behavior

HMR should load on all entries.  That is, when we navigate to either HTML, we should see the message 'HMR Connected' in the console.  This seems, IMO, to be the most intuitive behaviour;  if the consensus is otherwise, then an option could be provided to add HMR to all entries.

### Actual Behavior

HMR loads when we navigate to  `index.html` but not to `second.html`.  This boils down to the runtime client of HMR or dev not getting added to the second entry.  This is also evident from what webpack says in the output:

```
...
[1] multi ./second 28 bytes {second} [built]                          
[2] multi webpack-hot-client/client?c64955b6-30a9-42f6-8b04-758f4812e19e ./src 40 bytes {main} [built]
...
```

Note that the `webpack-hot-client/client` is not getting added to the second entry.

### How Do We Reproduce?

Please clone https://github.com/rmanoka/hmr-issue-minimal and run `npx webpack-serve` (after `npm install`).  Then open browser to https://localhost:8080/second.html and inspect to observe that HMR is not being loaded.

**Comment by shellscape** [comment]
This is by design. See https://github.com/webpack-contrib/webpack-hot-client/issues/60

**Comment by shellscape** [comment]
Please continue discussion on the issue linked to.

**Comment by rmanoka** [comment]
@shellscape Apologies for the confusion, but I overlooked the `hot` option which passes options to webpack-hot-client.  Indeed, this issue is best dealt by that package.
