### ISSUE TITLE
bundle.js returns 404 if project dir is named a certain way?

### ISSUE THREAD

**Issue by dingbat** [webpack-contrib/webpack-serve#147]
* Operating System: macOS 10.12.6, also Ubuntu 14.04.3
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.8.3
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
$ webpack-serve
```

##### webpack.config.js

```js
module.exports = {
  mode: process.env.NODE_ENV,
  entry: [
    "./index.html",
    "./index.jsx",
  ],
  output: {
    filename: "bundle.js",
    publicPath: "/",
  },
  module: {
    rules: [
      {
        test: /\.html$/,
        use: {
          loader: "file-loader",
          options: {
            name: "[name].[ext]",
          },
        },
      },
      {
        test: /\.jsx?$/,
        use: {
          loader: "babel-loader",
        },
      },
    ],
  },
  resolve: {
    extensions: [".js", ".jsx"],
  },
};
```

index.jsx:
```jsx
import ReactDOM from "react-dom";
import React from "react";

ReactDOM.render(
  <div>hello</div>,
  document.getElementById("app")
);
```

.babelrc
```js
{
  "presets": ["env", "react", "stage-0"]
}
```

### Expected Behavior

```console
$ pwd
/Users/dan/my-test
$ webpack-serve

other-shell$ curl http://localhost:8080/bundle.js
......bundle......

$ <CTL-C>
$ cd ..
$ mv my-test my%2Ftest
$ cd my%2Ftest
$ webpack-serve

other-shell$ curl http://localhost:8080/bundle.js
Not Found
```

### Actual Behavior

That `bundle.js` is still found when the directory name does not have `%2F` in it!

### How Do We Reproduce?

To reproduce, rename the parent dir of any project with webpack-serve to include `%2F` in it. The usecase here (how I found this) was jenkins building git branch names that had slashes in them (rendering the slashes as `%2F` in the directory name for the branch).

Tested with both fish and bash shells.

This is a super weird one. For the record, the same thing happens with [webpack-dev-server](https://github.com/webpack/webpack-dev-server) (came here to see if it would work with webpack-serve), for webpack versions 3 and 4.

I tried to pare down the webpack config to something completely minimal but I left React loaders etc (maybe it's something there). Haven't tested it out with too many other character combinations, but -- dir named `a%a` seemed to work, `a%20a` seemed to fail.

Any ideas???

**Comment by shellscape** [comment]
This is likely an issue with webpack-dev-middleware more than anything else, as that handles delivering the bundle to the attached server. Fwiw ut has a history of not handling special url chars well.

**Comment by shellscape** [comment]
Going to chalk this up as a `webpack-dev-middleware` problem. Please repost on that project if this continues to be an issue.
