### ISSUE TITLE
Building multiple bundles but only automatically including one bundle

### ISSUE THREAD

**Issue by ctaylo21** [webpack-contrib/webpack-serve#148]
* Operating System:
* Node Version: 9.8
* NPM Version: 5.6.0
* webpack Version: 4.8.1
* webpack-serve Version: 0.3.2

This issue is for a:

- [ ] **bug**
- [X] **feature** request
- [ ] **modification** request

### New Feature Use Case

I might have completely missed this in the docs, but is there a way to build a bundle via webpack but not have webpack-serve automatically add it to the html page? I have a script that I can't load until another script has loaded and performed some async operations. I am building the two separate bundles via webpack.

For example, just something like the config below and I want `script1` to be loaded right away but not `script2`.
```
module.exports = merge(common, {
  entry: {
    script1: path.resolve(__dirname, '../src/entry1.js'),
    script2: path.resolve(__dirname, '../test/entry2.js'),
  },
  serve: {
    content: [
      path.resolve(__dirname, '../dist/'),
    ],
  } //etc..
})
```

Thanks in advance!

**Comment by shellscape** [comment]
Sorry, but this isn't a support forum. Please use one of the support options listen in the issue template.
