### ISSUE TITLE
Report when HotModuleReplacementPlugin is included manually

### ISSUE THREAD

**Issue by kentcdodds** [webpack-contrib/webpack-serve#149]
```json
  "devDependencies": {
    "webpack": "^4.8.3",
    "webpack-cli": "^2.1.4",
    "webpack-serve": "^1.0.2"
  }
```

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

##### webpack.config.js

```js
// anything
plugins: [
  new webpack.HotModuleReplacementPlugin(),
],
server: {
  hot: {
    hot: true,
  }
}
// anything else
```

### Expected Behavior

What I _want_ this to do is throw a useful error saying that you don't need to include the HMR plugin manually when using the server.

### Actual Behavior

It includes it twice, resulting in very confusing issues. More context here: https://github.com/webpack/webpack/issues/7380

### How Do We Reproduce?

I have a reproduction repo [here](https://github.com/kentcdodds/webpack-dynamic-hmr-example/tree/ebdd72ee5cafc92c3777127c4d00c17916e51e81) (note the commit sha, I've updated it to be in a working state now).

**Comment by shellscape** [comment]
Thanks for issue :beer:  Please don't exclude template fields in the future - that's something we hold contributors and code owners to as well.

We'd welcome a PR for this, but it should land in webpack-hot-client. You also have options there to disable automatically configuring hot-client.

**Comment by tjallingt** [comment]
After looking through https://github.com/webpack-contrib/webpack-hot-client it seems to me that perhaps the best spot to put a check is in the `validateCompiler` or `modifyCompiler` functions (which are ran when auto configuring): https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/util.js but I'm not sure.

Let me know what you think and I'll be happy to submit a PR

**Comment by shellscape** [comment]
This will be resolved in https://github.com/webpack-contrib/webpack-hot-client/pull/66
