### ISSUE TITLE
Routing return not found, only root works, added historyApiFallback.

### ISSUE THREAD

**Issue by appsolutegeek** [webpack-contrib/webpack-serve#151]
* Operating System: OSX 
* Node Version: 10.0.0
* NPM Version: 5.6.0
* webpack Version: 4.8.3
* webpack-serve Version: 1.0.2

This issue is for a:

- [X] **help**
- [ ] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Expected Behavior
In an angular app you can route to all valid routes.

### Actual Behavior
The root of the app works but ALL routes return not found, I tried it with webpack-dev-server and it works. I think its something to do with the historyApi which I have included - but still no luck. 

### How Do We Reproduce?
A standard angular app (and also I presume react??) and have the following in a server.config.js in the root.

const history = require('connect-history-api-fallback');
const convert = require('koa-connect');

```
module.exports.serve = {
  content: [__dirname],
  add: (app, middleware, options) => {
    const historyOptions = {
      // ... see: https://github.com/bripkens/connect-history-api-fallback#options
    };

    app.use(convert(history(historyOptions)));
  },
};
```

If anyone can help I would really appreciate it.

**Comment by shellscape** [comment]
Sorry, but this isn't a support forum.

>  👉🏽 Need support, advice, or help? Don't open an issue.
> Head to StackOverflow or https://gitter.im/webpack/webpack.

**Comment by appsolutegeek** [comment]
Ok, thanks.
