### ISSUE TITLE
Build time for webpack is having 11 seconds added to it

### ISSUE THREAD

**Issue by eddiesholl** [webpack-contrib/webpack-serve#152]
* Operating System: macos
* Node Version: v8.5.0
* NPM Version: 5.3.0
* webpack Version: 4.9.1
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

Everything here is as simple as possible...

##### CLI Command

```console
  $ webpack-serve
```

##### webpack.config.js

```js
module.exports = {
  entry: './index.js'
}
```

### Expected Behavior
The run time for running webpack as part of webpack-serve should be accurate. I don't see any reason to be messing with the numbers calculated by the regular webpack code paths.

### Actual Behavior
I noticed that the build time shown by webpack when running in webpack-serve seemed higher than it actually was. There's always 11 seconds too much in the total build time. If the actual build time for webpack is 500ms, it will report around 12 seconds when running inside `webpack-serve`.
I'm not sure why `TimeFixPlugin` is being used here, I guess its to simulate the time to start up `webpack-serve`, but it defaults to 11 seconds, and that just seems wrong.

### How Do We Reproduce?

I have created a repo at https://github.com/eddiesholl/webpack-timing-bug to make the problem clear. This repo includes some simple steps to spot the problem. As far as I can tell, its happening on any usage of `webpack-serve` and `webpack`

**Comment by shellscape** [comment]
This is not a bug and is by design. Build times are not actually 10s longer, it's a fix for webpack's incorrect watching when using webpack-dev-middleware. See https://github.com/webpack-contrib/webpack-serve/blob/master/lib/config.js#L39

**Comment by eddiesholl** [comment]
I don't see how this can not be a bug. I understand that there might be a particular scenario where something else was messing the time up, and I assume that's why `TimeFixPlugin` was introduced. But in the simplest possible scenario, like in my example repo, the build time is just always 11 seconds too long.

![image](https://user-images.githubusercontent.com/3746494/40631287-7d2e75b4-631e-11e8-8827-8510377e3e8a.png)

Maybe you mean something like there's a bug in file watching, and the start time for webpack has to be rolled backwards to help with change detection? Maybe another instance of TimeFixPlugin could be used at the end to roll the startTime back to where it should be?

**Comment by shellscape** [comment]
I assure you that it's not a bug with this module. You may want to head over to the repo for `TimeFixPlugin` and speak with them. https://github.com/egoist/time-fix-plugin

**Comment by eddiesholl** [comment]
OK I see. I've tried to suppress the issue by introducing an instance of TimeFixPlugin with an offset of 0, but am still seeing the 11 seconds. Thought I was going mad, but this looks like another instance of the same solution:
https://github.com/webpack-contrib/webpack-hot-client/blob/5cc12b7f7ac8f3a529e409819af02f4f4d82a380/index.js#L112

Is that one also necessary? What about removing that one and relying on TimeFixPlugin to perform the offset?

**Comment by shellscape** [comment]
Probably best to open an issue in `webpack-hot-client` and go from there.

**Comment by eddiesholl** [comment]
Done. Thanks.
https://github.com/webpack-contrib/webpack-hot-client/issues/68
