### ISSUE TITLE
feat: throw error instead of resolving free port

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/webpack-serve#155]
* Operating System: Ubuntu 18.04
* Node Version: 10.2.1
* NPM Version: 6.1.0
* webpack Version: 4.10.1
* webpack-serve Version: 1.0.2

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### Code

I think not require

### Expected Behavior

Right now we try auto resolve free `port` https://github.com/webpack-contrib/webpack-serve/blob/master/lib/server.js#L116. But in some cases (example when i use `proxy` for `api` server, `metrics` server and etc) i resolve free ports for their in own startup script and also resolve free port for `dev` server and `hot` to avoid conflict and allow using this host/port as argument to other servers (for communication between part of application). It is possible disable this behavior? I prefer throw error than resolve new free port, because it is can broke communication between hot server and other part of systems (example send messages to web socket server).

### Actual Behavior

Always try to resolve free port.

### How Do We Reproduce?

not a bug, i think

### New Feature Use Case

Maybe add option for this?

**Comment by shellscape** [comment]
I'm sorry but this is a core feature of the module and it won't be disabled. If you need to prevent `webpack-serve` from running if a port is or is not in use before hand, there are many modules on NPM which can accomplish that. eg. wait-port, tcp-port-used, wait-for-port, etc.

**Comment by shellscape** [comment]
I was revisiting this question today, and still feel that this is an edge case that most will not encounter. However, I looked up some alternative approaches you could use that don't involve adding complexity to `webpack-serve`. Using bash to wait, or determine, if a port is free/open is possible, and would integrate well with NPM scripts. Please see:

https://stackoverflow.com/a/44484835
https://unix.stackexchange.com/a/149478

I think these would work well for your case.

**Comment by evilebottnawi** [comment]
@shellscape can't use `bash` :disappointed: it should be work on difference platform, without bash

**Comment by shellscape** [comment]
But your operating system was `Ubuntu 18.04`? Bash should be available. What platforms are you using it on which don't have bash?

**Comment by evilebottnawi** [comment]
@shellscape it is internal boilerplate for creating apps inside our company, some people works on windows, some on macos

**Comment by shellscape** [comment]
This should work well for multiple platforms: https://github.com/sindresorhus/is-port-reachable. Coupled with a small script in tooling:

```js
#!/usr/bin/env node

const isPortReachable = require('is-port-reachable');

isPortReachable(8080, {host: 'localhost'}).then(reachable => {
  if(!reachable) {
    process.exitCode = 1;
  }
});
```

**Comment by evilebottnawi** [comment]
@shellscape thanks for link, looks should be work

**Comment by shellscape** [comment]
Cool. Let me know here if it does not and we will reopen the issue.
