### ISSUE TITLE
Documentation should illuminate the drop-in capability of this over webpack-dev-server

### ISSUE THREAD

**Issue by jonnyasmar** [webpack-contrib/webpack-serve#158]
* Operating System: n/a
* Node Version: n/a
* NPM Version: n/a
* webpack Version: n/a
* webpack-serve Version: n/a

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Expected Behavior

Decided to give webpack-serve a try over webpack-dev-server due to an oustanding bug with Webpack4 and noticed that webpack-serve can be used as a pure drop-in replacement within my current configuration (which uses webpack config's `devServer` option to handle some configuration).

Searched all through the README to see if this was possible and there was no mention.

### Actual Behavior

I think it's very well worth noting that the minimum required setup to migrate from webpack-dev-server to webpack-serve is to simply replace the reference from one to the other in your npm scripts that use it.

If this is inaccurate for some reason or another, I believe the README should try to elaborate on any relevant steps one might need to follow to migrate, though from my experience this was not the case.

With that said, well done on creating a seamless migration experience (at least for me)! Thanks!

**Comment by shellscape** [comment]
Thanks for the issue :beer: and the kinds words.

It's rad that you're digging the module, but I'm not sure that it's doing what you think it is. `webpack-serve` doesn't support nor look for the `devServer` option and uses the `serve` option property instead (or a host of other configuration location options). If you're positive that your scripts are running `webpack-serve`, then it's likely running with the default configuration, which is rather opinionated.

**Comment by jonnyasmar** [comment]
Ah -- interesting. Yep, everything seemed to be working as expected. I was fooled!

Tested out historyApiFallback and can confirm devServer is not the config being read.

Is there an equivalent to that with the serve option?

**Comment by shellscape** [comment]
Yessir, check out the Add-ons section of the README.
