### ISSUE TITLE
webpack-serve serves files from src folder, overriding generated files

### ISSUE THREAD

**Issue by BernieSumption** [webpack-contrib/webpack-serve#159]
* Operating System: Mac
* Node Version: v8.10.0
* NPM Version: yarn 1.7.0
* webpack Version: 4.10.2
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

Minimal repro at https://github.com/BernieSumption/webpack-serve-bug-demo

### The issue

I discovered this while trying to figure out why html-webpack-plugin worked in production builds but not with webpack-serve. webpack-serve serves files from the source directory. This breaks the development experience when there are files in the source directory that have the same name as files in the output directory. Also, serving these files at all allows developers to write code that works in development with webpack-serve but fails in a production build as it directly refers to files in the source directory that aren't copied to the output directory.

### Expected Behavior

In general, webpack-serve should serve exactly the same content as if you did a webpack build then served the output folder using a static file server.

1. http://localhost:8080/ should serve the `index.html` file created by html-webpack-plugin
2. http://localhost:8080/bundle.js (or whatever file name is specified in webpackConfig.output.bundle) should serve the webpack bundle, regardless of whether there is a `src/bundle.js`.
3. http://localhost:8080/index.js should give a 404

### Actual Behavior

1. http://localhost:8080/ serves `src/index.html` - the template used by html-webpack-plugin, not the output of the plugin
2. If you create a file `src/bundle.js`, this file overrides the webpack bundle
3. http://localhost:8080/index.js serves `src/index.js`.

### How Do We Reproduce?

Clone https://github.com/BernieSumption/webpack-serve-bug-demo then `yarn && yarn start` to launch webpack-serve. `yarn build` to do a webpack build to the `dist` folder.

**Comment by shellscape** [comment]
See #114. This isn't a bug. This is a symptom of your environment. You'll need to configure `webpack-serve` correctly for your environment.
