### ISSUE TITLE
Proposal to improve developer experience around the static file serving performance optimisation

### ISSUE THREAD

**Issue by BernieSumption** [webpack-contrib/webpack-serve#160]
* Operating System: n/a
* Node Version: n/a
* NPM Version: n/a
* webpack Version: n/a
* webpack-serve Version: n/a

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

##### CLI Command

n/a

##### webpack.config.js

n/a

### Expected Behavior

n/a

### Actual Behavior

n/a

### New Feature Use Case

I'd like to submit a PR for this, opening the issue to figure out in advance whether you'd accept the PR, and if so what approach to take.

#### Background

webpack-serve has a performance optimisation: static content takes precedence over generated content; the static root is configured using the `content` CLI flag or API option; and the static root defaults to the webpack context, which defaults to process.cwd().

Issues #80, #114 and #159 all represent users who did not understand this behaviour and its implications.

I'd like to submit a PR to keep the performance benefit but reduce the confusion, either through better documentation, CLI warnings, tweaking the default behaviour, or some combination of the above.

The suitability of the current behaviour depends on your app's requirements:

| App requirements | Outcome |
| - | - |
| Static assets are kept in the source code root and copied to the output. No files in the source code root have the same name as generated files. This is typical for website projects. | The default setup works great |
| Static assets are kept in a subdirectory, e.g. `/static`. This is typical for web application projects. | The default setup will work, but with reduced performance because static assets are served through webpack-dev-middleware, not koa-static. The developer should set `content` to `./static`, but probably won't because things seem to work out of the box. |
| Files in the source code root have the same name as generated files | Rename the files, after a lengthy debugging session to figure out what was happening :) |

#### Possible fixes

What do you think of implementing one or more of these options?:

* Put documentation on the need to set the `content` option for your project as one of the first things in the project README.
* Print a warning when no `content` option is specified, saying that it is being defaulted to {config.context} and describing the implications.
* Change the behaviour of `content` - if it is not specified, print a warning that performance may suffer, and disable static serving. Users can enable the option if appropriate for their project for improved performance.
* Detect when a file in the static root is overriding a generated file and print a warning only in that case. Perhaps the most useful, but also the most work!

**Comment by shellscape** [comment]
This interesting, thanks for submitting it. For future reference, please abide by the instructions in the issue template and please _do not_ remove sections of the template. If they don't apply, just leave blank or use "n/a". 

> The default setup will work, but with reduced performance because static assets are served through webpack-dev-middleware, not koa-static.

Do you have metrics on this? I'm not sure "reduced performance" here is that big of a deal considering the intent of the module is to be used locally. If the numbers are dramatic, then that would indicate an issue in `webpack-dev-middleware`. 

> Put documentation on the need to set the content option for your project as one of the first things in the project README.

Documentation is only useful if the user reads the documentation, and there's a certain amount of discovery involved in that. I'm open to a separate `.md` file explaining content ordering with regard to builds, that was then linked to in the `content` option's block in the README. 

> Detect when a file in the static root is overriding a generated file and print a warning only in that case. Perhaps the most useful, but also the most work!

This is the best option for DX.  I think there should be a few informational bits:

1. info: `Serving content from ${path}\` should do the trick. This was previously considered extraneous.
2. warn: some file in build is being overriden by static assets

This is going to be tricky. Much of the logic for getting the path of a file in the MemoryFileSystem is contained within `webpack-dev-middleware` and we don't want to duplicate it in another project. There's also the matter of how to tell which comes first. The user can after-all, use the `add` function to change that order or insert any number of middleware between `dev-middleware` and `koa-static`. 
Ideally, this would detect any and all files in the build, in the MemoryFileSystem, as a part of server startup, and only if the `content` middleware was run first. Alternatively, we could also just throw an error and make the user correct it before proceeding. In most cases it would seem like continuing to run the server with that conflict would not be preferable.

If you'd like to embark on the path recognition bit, I'd keep it isolated to a branch in your own fork for the time being. I'm halfway through a refactor of the project (koa-webpack and webpack-hot-client are already done) to enable better testing, and it's going to significantly change the structure.

**Comment by BernieSumption** [comment]
> Do you have metrics on this? I'm not sure "reduced performance" here is that big of a deal considering the intent of the module is to be used locally.

I haven't noticed a performance hit, in fact in my project I've effectively disabled static serving using `--content ./dummy` and am perfectly happy with the performance.

Perhaps I've misunderstood the reason for koa-static being used. I thought that performance was the reason for using koa-static on the basis of your comment in #114 "And it's way faster for static content if webpack isn't trying to examine whether or not it's a bundle first."

If the performance of webpack-dev-middleware is adequate (I've found it fine) then why not remove the static file serving and just use webpack-dev-middleware, which would ensure that you serve exactly the content that the webpack build produces, no more, no less. Or perhaps disable koa-static by default, and allow it to be enabled through `--content` for people who have a static assets folder that is not processed by webpack.

This is, effectively, the experience that people with a `./static` subdirectory are already getting if they don't configure the `content` option.

**Comment by BernieSumption** [comment]
Oh and sorry about the issue template, I put it back in :)

**Comment by shellscape** [comment]
So WDM is only concerned with files that are part of a bundle. If you included all of your static assets as "part of the bundle" (there are round about ways to do this where they aren't actually in the bundle, but still considered to be part of it) then WDM would handle all of the requests to them. There is a minor a mount of overhead there. But it's a wonky idea, so truly static content should be served by a static content handling middleware. That might prompt one to ask - then why have WDM there at all? The answer there is that it runs all of the HMR stuff in memory, which if you turned that off, you'd see a flood of JSON and JS files to the disk while it's watching and performing HMR operations. That means that bundles are written to memory and not the disk, which is why we have to have that middleware separate, and why the bundle files get served from memory and the rest of the assets get served from disk.

**Comment by BernieSumption** [comment]
OK, so to summarise, the reason that koa-static is there is because many sites have a static folder that is not copied to the output by webpack, and so WDM isn't enough to reliably serve a project in development. Is that about right?

If that's the primary reason, then why not by default put WDM before koa-static? WDM is the certain thing - you know that a file served by WDM definitely should be in the output. The default behaviour of koa-static is a best guess - if the project has static files at all, and they are kept in the webpack context root, then the default static file behaviour is appropriate. Again, this behaviour would have prevented all 3 of the related issues, without breaking anybody's site as far as I can see.

You did cite performance concerns in your response to #114, would it help if I did some rough benchmarking to put some numbers on the performance penalty of putting WDM before koa-static?

**Comment by shellscape** [comment]
> If that's the primary reason, then why not by default put WDM before koa-static? 

Lordy. This has been covered before. That assumes that the folks who need static assets served first have less priority than the folks who need the bundle middleware first. And the reverse is also true if it were to be changed You're forgetting or not taking into account that this ecosystem is insanely vast, and that there are an incredibly number of different environments that use these tools. _Your way is not the best way for everyone else_. The simplest setup is default - it's the setup by which all other servers on the planet run by default.

_If users needs this behavior changed, they are empowered to easily make the change._

I will not debate the order of the middleware further, because users have the power to easily change it. You started this issue to improve documentation or the developer experience. Your last reply has verged off into trying to assert your personal preference for the development environment as a best alternative. If you'd like to continue your original train of thought, I'm happy to leave this open and continue the discussion.

**Comment by BernieSumption** [comment]
Sorry, didn't mean to pick the scab, I'm just having trouble imagining the project configuration that would work with static-before-WDM but not with WDM-before-static. Quite happy to assume that these exist and that the problem is with my imagination. Let's move on.

I propose that:

1. I submit a PR for a bit of documentation to clarify the purpose and importance of the `content` option, and the use of the `add` function to change the order of middleware if required. I agree with you that "documentation is only useful if the user reads the documentation", but I did read the documentation looking for answers to this question before submitting #159, and didn't find any. I suggest a separate .md file explaining the option and a link to said file near the top of the README. Hopefully this will significantly reduce the proportion of users who re-report this issue (3 in the last 5 weeks, I don't blame you for not wanting to debate it any more :). If you like, I can also add a CLI warning, if the `content` option is not specified, linking to the .md file.

2. If and when I have time I look in to a better solution, involving detecting when static files shadow generated files so that a warning can be printed, I may do so. But I understand from your comments about in-memory file systems that this may be hard.

**Comment by shellscape** [comment]
That sounds like a good plan. My only modifications to this would be:

>  I can also add a CLI warning, if the content option is not specified, linking to the .md file.

I still don't feel a warning here is warranted. The `log.info` method should be sufficient, and printing the static content location root each time isn't intrusive, given that it's informative.

> near the top of the README

It would be more appropriate for the `add` option section or the _Add-Ons_ section opening paragraph. I'm not opposed however, to highlighting the _Add-Ons_ section out of the gate with a modification to the README's opening paragraph. Something along the lines of:

```
A lean, modern, and flexible webpack development server.

`webpack-serve` can be molded to suit your environments needs by making use of the highly-extensible [Add-On Feature](#add-on-features).
```

**Comment by BernieSumption** [comment]
The argument for a more prominent warning is 3 issues submitted in 5 weeks, though you could always start with an info and make it a warning if the issue reports keep coming. Preview:

#### content option specified

> $ webpack-serve --config webpack.config.js --content ./static
> ℹ ｢hot｣: webpack: Compiling...
> ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
> ℹ ｢serve｣: Project is running at http://localhost:8080
> ℹ ｢serve｣: Server URI copied to clipboard
> ℹ ｢serve｣: Serving static content from "./static"
> ℹ ｢hot｣: webpack: Compiling Done

#### content option not specified

> $ webpack-serve --config webpack.config.js
> ℹ ｢hot｣: webpack: Compiling...
> ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
> ℹ ｢serve｣: Project is running at http://localhost:8080
> ℹ ｢serve｣: Server URI copied to clipboard
> ⚠ ｢serve｣: Serving static content from "./src" because no --content option was specified. This causes issues with some project setups. See https://github.com/webpack-contrib/webpack-serve/blob/master/STATIC-CONTENT.md for more information
> ℹ ｢hot｣: webpack: Compiling Done

Questions:

1. Is the wording OK?
2. Warn if no --content specified as above, or info in both cases?

**Comment by shellscape** [comment]
So I get that this was a problem you ran into, and that there's a perceived urgency here from your end. But you're tailoring your solution to your specific problem. There's a larger ecosystem at play here. There's just no reason to warn in this situation when content isn't explicitly specified, and I can't get down with that. It's bad UX.

For the content log message, it should read:

```js
log.info(chalk`Serving Static Content from: {grey ${conentPath}}`);
```

Where `contentPath` is the variable containing the full path to the static content directory. This also has to account for multiple content directories, as that's allowed. In that case the UX should compensate for that, and it should look like this in the end:

```console
i ｢serve｣: Serving Static Content from:
                  /some/path/first
                  /some/path/second
                  /some/path/third
```

We're quickly reaching a point where we're expending more energy hashing over this than we would if I just went ahead and made the log change. I want to encourage you and others to contribute, but the scale is starting to tip.

**Comment by tjallingt** [comment]
Just ran into this behaviour...

I have a `public/` folder that contains the html / css / images / static js files but my output path is `public/lib/` so that after I run production webpack I can simply statically serve my `public/` folder.

If I run `webpack-serve` after running the production build (which outputs files to the `public/lib/` folder) I stop receiving the development bundle from `webpack-serve` as it opts to send me the generated production bundle.

**Comment by shellscape** [comment]
Closed by #167

**Comment by shellscape** [comment]
@tjallingt @BernieSumption @benwiley4000 @dupski through private channels I'm hearing about this situation - where static content path is the same as output path - being a problem and a source of confusion more and more. It's got me wondering if it's time to switch the order of which middleware is called first by default. Since this affected both of you, I'm curious if you can see any situations in which that might have a negative impact.

**Comment by benwiley4000** [comment]
@shellscape to be clear, the proposal is to check the virtual filesystem first and then the static files?

**Comment by shellscape** [comment]
@benwiley4000 You are correct. Based on mounting evidence I'm thinking that may be a good change going forward.

**Comment by tjallingt** [comment]
> where static content path is the same as output path

This is very similar to how im using webpack serve. i have a `public` folder containing all my static assets (html, css, images etc) and i tell webpack to output my bundle to a folder (that i call `lib`) inside this `public` folder. However after i run my production build process there are js files in there with the exact file names that webpack serve has generated in memory. This way i potentially get in a really confusing situation where i run webpack serve but none of my code changes are appearing.

To avoid this i tend to swap the middlewares in my config whenever i use webpack serve.

I have not experienced any issues with the middlewares swapped and i can't directly think of a scenario in which this would present a problem.

**Comment by BernieSumption** [comment]
@shellscape Playing devil's advocate since as you know my use case would have benefitted from reversing the order :) I had a think, and all I can come up with is that if someone has a webpack config that generates additional files that they don't need, and they are relying on these files being overwritten by the static content. For example, say the config is copying library files using copy-webpack-plugin with an over-wide glob expression "some-lib/*.*" where they only want the JS and CSS files, but the lib folder also contains an index.html.

Despite that possibility, I still think it's the right thing to have webpack generated take precedence over static files, simply because the static file serving is webpack-serve's best guess and may be wrong, whereas the webpack bundle will always contain exactly the files defined by the webpack config supplied by the user.

**Comment by shellscape** [comment]
v2.0.0-beta.2 is up with the order reversed. please give it a try.

**Comment by benwiley4000** [comment]
Will do thanks!

**Comment by BernieSumption** [comment]
v2.0.0-beta.2 is working for me.
