### ISSUE TITLE
React HMR broken in v1.0.2, works fine in v0.3.2

### ISSUE THREAD

**Issue by tonghae** [webpack-contrib/webpack-serve#161]
* Operating System: Windows 7 / MacOS High Sierra
* Node Version: 
* NPM Version:
* webpack Version: 4.6 & 4.10
* webpack-serve Version: 0.3.2 & 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Expected Behavior
React HMR works fine

### Actual Behavior
React HMR works only with single entry in webpack config or with older version, 0.3.2

### How Do We Reproduce?
I prepared minimal reproducible example in this repo, step-by-step readme included:
https://github.com/tonghae/WSMEPIE

**Comment by shellscape** [comment]
Thanks for the very thorough reproducible instructions. Unfortunately this is a known-issue and was by-design to work around several other requests in `webpack-hot-client@3.0.0`. A future version of `webpack-serve` will leverage `webpack-hot-client@4.x` which will allow use of the `allEntries` option. For the time being you can use `hot: { autoConfigure: false}` and setup your entries manually, or use the older version of `webpack-serve`. If this is still an issue when a new version of `webpack-serve` is released, using `webpack-hot-client@4`, please let us know and we'll reopen this issue.

**Comment by tonghae** [comment]
Ok I can just use single entry point for now

**Comment by phyllisstein** [comment]
I'm seeing much the same issue with multiple entrypoints and HMR in `webpack-serve@2.0.2` with `webpack-hot-client@4.1.1`. Even with `allEntries` set to `true` in my `hotClient` config, only changes to the first configured entrypoint's dependencies trigger an update. Changing the second entrypoint, I get this in the console:

```
｢hot｣ Hot Module Replacement Enabled. Waiting for signal.
log.js:59 ｢hot｣ WebSocket connected
log.js:59 ｢hot｣ App updated. Recompiling scripts/front-page/index.js
log.js:59 ｢hot｣ webpack: Compiling (<unnamed compiler>)
log.js:59 ｢hot｣ App Updated, Reloading Modules
log.js:59 ｢hot｣ Checking for updates to the bundle.
log.js:59 ｢hot｣ No Modules Updated.
log.js:59 ｢hot｣ App is up to date.
```

I can put together a repro repo tonight if it's helpful; just let me know if you need it to track down the issue. Thanks in advance for taking a look!
