### ISSUE TITLE
Definitions for WebpackServer seems not correct

### ISSUE THREAD

**Issue by Jokcy** [webpack-contrib/webpack-serve#163]
* Operating System: macos 10.13
* Node Version:   9.11.1
* NPM Version:    6.1.0
* webpack Version:  4.10.0
* webpack-serve Version:  1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
```ts
// write this is typescript
serve({
      compiler: this.compiler // a no matter what webpack compiler
    })
```

### Expected Behavior
success

### Actual Behavior
error shows that **serve function expect args like {config: {compiler: xxx-compiler}}**

### How Do We Reproduce?
just use typescript to start webpack-serve

It seems Definitions for WebpackServer not correct, the code now is:
```ts
declare function WebpackServe(
  { config }: { config: WebpackServe.Options }
): Promise<WebpackServe.Instance>;
```
and I guess this will be correct:
```ts
declare function WebpackServe(
  config: WebpackServe.Options
): Promise<WebpackServe.Instance>;
```

I can make a PR but I don't know where to pull the Definitions code

**Comment by shellscape** [comment]
Thanks for the issue, but this project does not maintain nor publish TypeScript definitions.

**Comment by Jokcy** [comment]
@shellscape so can you tell me where to fix this?

**Comment by shellscape** [comment]
@Jokcy unfortunately no, I don't use TypeScript.

**Comment by aaronbeall** [comment]
Type defs are available through DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webpack-serve
