### ISSUE TITLE
1.0.3: cannot pass buffer/string certificates to https option anymore

### ISSUE THREAD

**Issue by stnwk** [webpack-contrib/webpack-serve#166]
* Operating System: macOS 10.13.3
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.11.1
* webpack-serve Version: 1.0.3

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

```js
import startDevServer from 'webpack-serve';
import { certificateFor } from 'devcert';

// https holds buffers
const https = await certificateFor('localhost', {
 skipHostsFile: true,
 skipCertuil: false,
});

startDevServer({
 // other config does not matter, reproducible either way
 https,
});

```

### Expected Behavior
Should start up the dev-server with a valid https cert.

### Actual Behavior
Throws an error:

`An error was thrown while starting webpack-serve.
   { Error: ENAMETOOLONG: name too long, lstat 'Certificate:
{...certificate data}
`

### How Do We Reproduce?

Generate a self-signed certificate using `devcert` and pass it in as `https` option to webpack-serve >= 1.0.3.

Before 1.0.3 it was perfectly fine to pass buffers/strings for each entry in the https options, but since 1.0.3 it does not work anymore.

I think this bug was introduced in https://github.com/webpack-contrib/webpack-serve/commit/e030696cf0c64c97582f33c1ae3492918c23fb41#diff-763aa8deb604d725a74f8304903c1422R78

It basically runs `fs.lstatSync()` on the actual passed string/buffer value of the cert/key, which of course is too long. We'll need to check first weather it's an actual file (path) before using lstat.

**Comment by shellscape** [comment]
Are you sure you're using/reporting the right project? This project hasn't gotten to version 4 yet.

**Comment by stnwk** [comment]
@shellscape 

> Are you sure you're using/reporting the right project? This project hasn't gotten to version 4 yet.

😄 My bad. Of course I meant `1.0.3` instead of `4.0.3`.
Edited.

Thanks for pointing that out!

**Comment by shellscape** [comment]
@stnwk ah, there we go. would you be interested in submitting a fix for this? should be a simple test of whether or not the value is a `Buffer`.

**Comment by stnwk** [comment]
Sure, i'll take a look at it! :)

**Comment by stnwk** [comment]
@shellscape Was about to submit my PR when I realised you fixed it yourself.. what's the point of asking for help then? 😕 Heads-up would have been nice.

Either way: Thanks for tackling this so quickly!

**Comment by shellscape** [comment]
@stnwk we welcome contribution whole heartedly, but we also can't let critical bugs like that stand unresolved for too long. you might also run into the same situation where another user submits a PR for a fix at the same time you're working on one. unfortunately without opening a pre-emptive work-in-progress PR, there's no way to know who's working on what or how close to ready a fix is. sorry that this one got fixed before you had that chance.
