### ISSUE TITLE
Does webpack serve pay attention to plugins?

### ISSUE THREAD

**Issue by tavurth** [webpack-contrib/webpack-serve#169]
In my `webpack.config.js` I have a plugin:

```js
// Ignore certain kinds of development scratch files
new webpack.WatchIgnorePlugin([/^\.#.*/]),
```

However, while `webpack --watch` does not rebuild when these files change, webpack-serve always rebuilds.

`webpack-serve` also seems to disregard `stats` part of the config, blobbing large amounts of text into the console.

* Operating System: Linux
* Node Version: v8.10.0
* NPM Version: 5.6.0
* webpack Version: 4.9.1
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ NODE_ENV=development webpack-serve --progress --watch --port 3002 --host 0.0.0.0 --config ./webpack/config.client.babel.js
```

##### webpack.config.js

```js    plugins: [
        ...plugins,
        // Ignore certain kinds of development scratch files
        new webpack.WatchIgnorePlugin([/^\.#.*/]),
    ],
```

### Expected Behavior
Webpack-serve uses the WatchIgnorePlugin

### Actual Behavior
Webpack does not ignore these files and rebuilds every time they change

**Comment by shellscape** [comment]
`webpack-dev-middleware` is responsible for initiating the watch of your build. I see that you previously opened the same issue in another repo that was leveraging `webpack-serve`. I'm sorry to have to send you to another repo, but this is not an issue with this module.
