### ISSUE TITLE
bump `webpack-hot-client` to 4.x

### ISSUE THREAD

**Issue by jkzing** [webpack-contrib/webpack-serve#170]
* Operating System: macOS High Sierra 10.13.2
* Node Version: 10.4.0
* NPM Version: -
* webpack Version: - 
* webpack-serve Version: 1.0.3

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  # not relevant
```

##### webpack.config.js

```js
  // not relevant
```

### Expected Behavior
HMR successfully

### Actual Behavior

HMR failed with uncaught JS error.
`hot.js:31 Uncaught TypeError: lastHash.indexOf is not a function`

---

Did a quick look into the code, this should be already fixed in the latest code here https://github.com/webpack-contrib/webpack-hot-client/blob/master/lib/client/index.js#L69.

However `webpack-serve` is not using latest version of `webpack-hot-client`, so maybe bump `webpack-hot-client` to 4.x?

**Comment by shellscape** [comment]
Close as quasi-duplicate. This was already addressed in #165. This is also an incredibly incomplete issue. Had #165 not existed, there'd be no way to triage based on the sparse information provide. Please consider being verbose in the future.

**Comment by jkzing** [comment]
I am sorry if this issue is not met your requirements.I believe I gave enough information in the detail description, hope didn't waste you much time to understand it. 🙂
