### ISSUE TITLE
No file changes detection on VirtualBox/Vagrant mounted folders

### ISSUE THREAD

**Issue by schrej** [webpack-contrib/webpack-serve#172]
* Host Operating System: MacOS 10.13.4
* Vagrant version: 2.1.1
* Vagrant Image: bento/ubuntu-16.04 (virtualbox, 201803.24.0)
* Vagrantfile is [here](https://github.com/pterodactyl/panel/blob/feature/vuejs/Vagrantfile)
* Node Version: 8.11.2
* NPM Version: 6.1.0
* webpack Version: 4.4.1
* webpack-serve Version: 1.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [x] **modification** request

##### CLI Command

```console
  $ webpack-serve --hot --config ./webpack.config.js "--host" "192.168.50.2"
```

##### webpack serve config
```js
  {
     serve: {
        content: "./public/",
        dev: {
            publicPath: "/assets/",
            headers: {
                "Access-Control-Allow-Origin": "*",
            }
        },
        hot: {
            hmr: true,
            reload: true,
        }
    }
}
```
All of it (a little messy) can be found [here](https://github.com/pterodactyl/panel/blob/feature/vuejs/webpack.config.js).

### Expected Behavior
`webpack-serve` should detect file changes and recompile the code

### Actual Behavior
`webpack-serve` doesn't detect the file changes

### How Do We Reproduce?
Run `webpack-serve` on a shared folder within a Vagrant VM.

This [issue](https://github.com/webpack/webpack-dev-server/issues/155) also occured with `webpack-dev-server`. There were two solutions, the second one isn't really ideal imo.

1. add the `--watch-poll` flag to the dev server to alternate the detection of file changes and make it work with Virtualbox
2. Using `rsync-auto` with Vagrant and changing the mount mechanism. [source](https://stackoverflow.com/a/33699702/4430124)

Can we readd the `--watch-poll` flag here, or is there another solution that I missed?

**Comment by frenzzy** [comment]
How about something like this?
```js
{
  serve: {
    ...
    dev: {
      ...
      watchOptions: {
        poll: 1000 // Check for changes every second
      }
    }
  }
}
```

- https://github.com/webpack-contrib/webpack-serve#dev
- https://github.com/webpack/webpack-dev-middleware#watchoptions
- https://webpack.js.org/configuration/watch/#watchoptions

**Comment by schrej** [comment]
That totally does the trick.

I found an even better solution though:
There is a tool called [`notify-forwarder`](https://github.com/mhallin/notify-forwarder) that forwards file system events to virtualbox.
For vagrant users there is [`vagrant-notify-forwarder`](https://github.com/mhallin/vagrant-notify-forwarder) that does it automatically for vagrant mounts.
Maybe you can link it somewhere, it's a lot better regarding performance than the polling.
[source with more details](https://blog.codecentric.de/en/2017/08/fix-webpack-watch-virtualbox/)

**Comment by airtonix** [comment]
Is it enough to use the cli argument? 

```
webpack-serve --dev-ware.watchOptions.poll=300 --log-time --port $PORT --host $HOST --log-level info --open-path '/#/collections/test/entries/test',
```

**Comment by thenewguy** [comment]
@airtonix 

Probably.  My comment was mentioning that it works if you use the correct settings namespace.  The recommendation earlier in the issue have the wrong namespace.  This does work for me:

```
        devMiddleware: {
            watch: false,
            watchOptions: {
                poll: true
            }
        },
```
