### ISSUE TITLE
watchOptions.ignored not honored

### ISSUE THREAD

**Issue by thielium** [webpack-contrib/webpack-serve#174]
* Operating System: OSX
* Node Version: 8.11.1
* NPM Version: 5.10.0
* webpack Version: 4.12.0
* webpack-serve Version: 1.0.4

This issue is for a:

- [x] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve webpack.config.js
```

##### webpack.config.js

```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  mode: "development",
  entry: "./index.js",
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js"
  },
  watchOptions: {
    ignored: /ignored.js$/
  },
  plugins: [
    new HtmlWebpackPlugin()
  ]
}
```

index.js:
```js
require('./ignored.js');

console.log("The file was loaded", new Date());
```
ignored.js:
```js
console.log("The file was loaded, too, but should have been ignored", new Date());
```
### Expected Behavior
`webpack-serve`'s recompile behavior should honor `watchOptions.ignored` and not recompile ignored files.

### Actual Behavior
`webpack-serve` recompiles the ignored files

### How Do We Reproduce?

1. clone https://github.com/thielium/webpack-serve-watch
2. `npm run native-watch` and `touch ignored.js`. Note how webpack does not recompile.
3. `npm run webpack-serve` and `touch ignored.js`. Note how webpack-serve recompiles.

### New Feature Use Case

As a user, when a certain fileset is expensive to watch, I would like like to ignore it to keep my rebuilds fast.

**Comment by shellscape** [comment]
Thanks for filing a complete issue :beer: but as [this issue reply stated](https://github.com/webpack-contrib/webpack-serve/issues/172#issuecomment-396098987), `webpack-serve` does not handle file watching. This is likely an issue with `webpack-dev-middleware`.
