### ISSUE TITLE
Page does not refresh on change

### ISSUE THREAD

**Issue by clubajax** [webpack-contrib/webpack-serve#175]
* Operating System: OSX
* Node Version: 10.4
* NPM Version: 6.1
* webpack Version: 4.1.1
* webpack-serve Version: 1.0.4

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

{
	"mode": "development",
	"context": "/Users/mwilcox/sites/webpack-runner/tests/./app4//",
	"entry": {
		"vendor": [
			"./vendors",
			"webpack-dev-server/client?http://0.0.0.0:8888",
			"react-hot-loader/patch",
			"webpack/hot/only-dev-server"
		],
		"main": "./index.jsx"
	},
	"output": {
		"filename": "[name].js",
		"path": "/Users/mwilcox/sites/webpack-runner/dist",
		"publicPath": "http://localhost:8888/"
	},
	"module": {
		"rules": [
			{
				"test": {},
				"use": {
					"loader": "babel-loader",
					"options": {
						"babelrc": false,
						"presets": [
							"@babel/react",
							[
								"@babel/preset-env",
								{
									"modules": false,
									"useBuiltIns": "usage",
									"targets": {
										"browsers": [
											"Chrome >= 60",
											"Safari >= 11",
											"iOS >= 11",
											"Firefox >= 54",
											"Edge >= 15"
										]
									}
								}
							]
						],
						"plugins": [
							"lodash",
							"date-fns",
							"react-hot-loader/babel",
							"@babel/plugin-syntax-dynamic-import",
							"@babel/plugin-proposal-object-rest-spread"
						]
					}
				},
				"exclude": {}
			}
		]
	},
	"plugins": [
		DefinePlugin { definitions: [Object] },
		MiniCssExtractPlugin { options: [Object] },
		CaseSensitivePathsPlugin { options: {}, pathCache: {}, fsOperations: 0, primed: false },
		ProgressPlugin { profile: undefined, handler: [Function] },
		HtmlWebpackPlugin { options: [Object] },
		HotModuleReplacementPlugin {
			options: {},
			multiStep: undefined,
			fullBuildTimeout: 200,
			requestTimeout: 10000 },
		NamedModulesPlugin { options: {} }
	],
	"devtool": "none",
	"serve": {
		"clientLogLevel": "none",
		"port": 8888,
		"host": "0.0.0.0",
		"content": "/Users/mwilcox/sites/webpack-runner/dist",
		"historyApiFallback": true,
		"hot": {
			"host": "0.0.0.0",
			"port": 8090
		},
		"stats": {
			"colors": true
		},
		"on": {}
	}
}

### Expected Behavior
Page refreshes on code change

### Actual Behavior
I see the code compile in the terminal window, but page does not refresh

### How Do We Reproduce?
I don't know. It seems I am using a standard config, other than that I use the serve API and not the CLI.

**Comment by shellscape** [comment]
>   👉🏽 Need support, advice, or help? Don't open an issue.
  Head to StackOverflow or https://gitter.im/webpack/webpack.

Looks like you have a lot of settings in there left over from `webpack-dev-server`. It looks like you're asking for support rather than reporting a legitimate bug. Unfortunately, this isn't the proper place to ask for support.
