### ISSUE TITLE
Invalid documentation for --no-hot-client

### ISSUE THREAD

**Issue by blikblum** [webpack-contrib/webpack-serve#176]
* Operating System: Windows 10
* Node Version: node 8.11
* NPM Version: 5
* webpack Version: 4.12
* webpack-serve Version: 1.0.4

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

##### CLI Command

```console
  $ webpack-serve --no-hot --mode=development
```

##### webpack.config.js

```js
https://github.com/blikblum/marionette-wires-revisited/blob/master/webpack.config.js
```

### Expected Behavior

The cli documentation should contain the correct options

### Actual Behavior

In https://github.com/webpack-contrib/webpack-serve#cli there's a --no-hot option which if set, breaks the server (the page reloads indefinitely with message i ｢hot｣: WebSocket Client Connected ). The correct option seems to be --no-not-client cited [here](https://github.com/webpack-contrib/webpack-serve#hot)

**Comment by shellscape** [comment]
Thanks for the issue 🍺  We'll have this fixed shortly.
