### ISSUE TITLE
Support HTTP/2 on Node 8 LTS

### ISSUE THREAD

**Issue by madhavarshney** [webpack-contrib/webpack-serve#177]
* Operating System: Windows
* Node Version: 8.11.2
* NPM Version: 6.1.0
* webpack Version: 4.12.0
* webpack-serve Version: 1.0.4

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Code

N/A

### Expected Behavior

HTTP/2 should be supported on versions of Node.js > 8.4, or at least 8.9 LTS.

### Actual Behavior

HTTP/2 is only supported on versions of Node.js > 9.0.0

### New Feature Use Case

Since HTTP/2 support was added in Node.js v8.4.0, is it possible to support HTTP/2 on Node.js 8 LTS and above?  The change would be quite simple; I can submit a PR if it's fine with you guys.

**Comment by shellscape** [comment]
Can you link to documentation for http2 support in those versions of node?

**Comment by madhavarshney** [comment]
https://nodejs.org/dist/latest-v8.x/docs/api/http2.html

**Comment by shellscape** [comment]
Thanks. It's a good idea to include that kind of info in issues moving forward.

So the release notes for 8.4.0 state that it's being the `--expose-http2` flag in 8.4.0 https://nodejs.org/en/blog/release/v8.4.0/. Is that true of later releases in the 8.x major as well? If so, we shouldn't support it (just as we don't support other features directly that require flags). If not, we'll need the link to the documentation or release notes that state it's no longer behind a flag.

**Comment by madhavarshney** [comment]
> Thanks. It's a good idea to include that kind of info in issues moving forward.

Sure, thanks for the feedback!

> So the release notes for 8.4.0 state that it's being the --expose-http2 flag in 8.4.0 https://nodejs.org/en/blog/release/v8.4.0/. Is that true of later releases in the 8.x major as well?

Sorry, I forgot about that part!  But no, from 8.8.0 onward, http2 is exposed by default: https://nodejs.org/en/blog/release/v8.8.0/.  So it's probably a good idea to support HTTP/2 on Node 8.9.0 LTS+.

**Comment by madhavarshney** [comment]
@shellscape - Should I submit a PR?

**Comment by shellscape** [comment]
@madhavarshney yes, please do. please also include the release notes link for 8.8.0 in the PR for reference.

**Comment by madhavarshney** [comment]
@shellscape - Sure.  Should I support Node.js 8.8.0+ or 8.9.0 LTS+ ?

**Comment by shellscape** [comment]
I'd got the 8.9.0 LTS route. Safest by far considering it's an older version.

**Comment by shellscape** [comment]
@madhavarshney we've added this to the refactor that will be released as a new major. you can view the change here: https://github.com/webpack-contrib/webpack-serve/blob/cfee4ec542e88ccade35b1a33306be0514dfa61a/lib/options.js#L67-L69. Thanks for lending your comments and insight into this.
