### ISSUE TITLE
Option: log only url and status (building, done,..)

### ISSUE THREAD

**Issue by MatejMazur** [webpack-contrib/webpack-serve#179]
### New Feature Use Case

Please, provide an option so we could have in console only something like this:

```
The server is running on http://localhost:8080
Status: builded // or 'building' or 'error' (and show the error)
```

Everytime the bundle is updated it should keep showing url and status. Nothing more.

The `webpack-dev-server` has the option `quiet` which allows to hide clutter stats but then you must define custom logging and that's too much low level. It would be great if there would be some option which just do that.

Thanks for any response!

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed portions of the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request template sections. They're in the template because they're useful to the maintainers of this project.
