### ISSUE TITLE
webpack.config.js that exports a function is not supported

### ISSUE THREAD

**Issue by Kovensky** [webpack-contrib/webpack-serve#18]
* Operating System: macOS
* Node Version: 9.5.0
* Yarn Version: 1.3.2
* webpack Version: 4.0.1
* webpack-serve Version: 1.0.0-beta.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ "$(npm bin)"/webpack-serve
```

##### webpack.config.js

```js
module.exports = function (env, webpackOptions) { return { serve: {} } }
```

### Expected Behavior

webpack-serve should start

### Actual Behavior

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration should be an object.
    at webpack (.../node_modules/webpack/lib/webpack.js:24:9)
    at getOptions.then (.../node_modules/webpack-serve/index.js:28:28)
```

The function in module.exports is being passed to webpack as-is instead of being called with the env options / parsed options as arguments.

Support for this is necessary if the webpack config is shared with both `webpack-serve` and `webpack-cli`.

### How Do We Reproduce?

Execute the CLI command

**Comment by shellscape** [comment]
@Kovensky the issue template is incomplete. we'll reopen when the missing info is added.

**Comment by shellscape** [comment]
Thanks for adding the missing bits back to the issue.

**Comment by kschiffer** [comment]
I've got a similar issue when adding a serve option to my `serve.config.js` like in [this example](https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/proxy-history-fallback.config.js)
```
$ ./node_modules/.bin/webpack-serve ./config/serve.config.js
Error: An error was thrown while initializing Webpack
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'serve'. These properties are valid:.

...

```
webpack: v4.0.0
webpack-cli: v2.0.14
webpack-serve: v2.0.2
node: v9.11.1

**Comment by shellscape** [comment]
@kschiffer upgrade webpack. You're 16 minor versions behind.
