### ISSUE TITLE
specify `serve.config.js` file location 

### ISSUE THREAD

**Issue by ZSkycat** [webpack-contrib/webpack-serve#183]
* Operating System:
* Node Version:
* NPM Version:
* webpack Version:
* webpack-serve Version: 1.0.4

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### New Feature Use Case

```console
  $ webpack-serve --serve-config .tool/serve.config.js
```

I want to put "serve.config.js" in the "tool" directory

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed portions of the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request template sections. They're in the template because they're useful to the maintainers of this project.
