### ISSUE TITLE
Folders are not redirected if missing a slash at the end

### ISSUE THREAD

**Issue by Maia-Everett** [webpack-contrib/webpack-serve#184]
* Operating System: Ubuntu 18.04
* Node Version: 8.11.3
* NPM Version: 5.6.0
* webpack Version: 4.12.0
* webpack-serve Version: 1.0.4

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

##### webpack.config.js

Any

### Expected Behavior

If the URL points to a folder with an index.html file and it is missing a slash at the end, the server should respond with a redirect with a slash added at the end.

### Actual Behavior

If the URL points to a folder with an index.html file and it is missing a slash at the end, the server does not redirect with the slash added, making the browser think that the folder name is a file name, which in turn makes relative URLs work differently depending on whether or not the slash is present.

### How Do We Reproduce?

* Create a folder named e.g. `folder` with an `index.html` file in it.
* Open `http://localhost:8080/folder` (without a slash).
* Observe that unlike with most web servers, the browser does not redirect to `http://localhost:8080/folder/`.

**Comment by shellscape** [comment]
Thanks for the issue :beer:

This project uses `koa` and `koa-static` to serve static files. Please report the issue with either one of those projects. If you find that an enhancement can be made to utilize options in either one of those projects to resolve the issue you've raised, please submit a PR with the enhancement.
