### ISSUE TITLE
Yarn add / npm install fails

### ISSUE THREAD

**Issue by mattixittam** [webpack-contrib/webpack-serve#188]
* webpack-serve Version: latest

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

When I try to install webpack-serve:

```console
  $ yarn add webpack-serve
```
### Expected Behavior
webpack-serve installs

### Actual Behavior
`error Couldn't find package "@shellscape/koa-static@^4.0.4" required by "webpack-serve" on the "npm" registry.`

**Comment by shellscape** [comment]
>   👉🏽 Need support, advice, or help? Don't open an issue.
  Head to StackOverflow or https://gitter.im/webpack/webpack.

```console
→ npm info @shellscape/koa-static time
 
{ created: '2018-02-12T01:33:39.346Z',
  '4.0.2': '2018-02-12T01:33:40.510Z',
  modified: '2018-03-31T02:20:04.403Z',
  '4.0.3': '2018-02-12T01:40:36.568Z',
  '4.0.4': '2018-02-12T01:56:04.613Z',
  '4.0.5': '2018-03-31T02:20:03.769Z' }
```

You'll have to use `npm` or figure out why your local setup doesn't work properly. This is not a bug - please be a bit more diligent in trying to resolve issues on your end before tossing an issue at a project and labeling it a bug. Not everything is a bug.

**Comment by mattixittam** [comment]
Hmm, this may have something to do with out private registry. Found out just _after_ submitting the issue of course.
