### ISSUE TITLE
Adding a serve option key directly to the webpack options is incompatible with webpack-cli

### ISSUE THREAD

**Issue by Kovensky** [webpack-contrib/webpack-serve#19]
This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ "$(npm bin)"/webpack
```

##### webpack.config.js

```js
module.exports = function (env, webpackConfig) { return { serve: {} } }
```

### Expected Behavior

webpack-cli should run

### Actual Behavior

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'serve'. These properties are valid:
   object { mode?, amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry?, externals?, loader?, module?, name?, node?, output?, optimization?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
```

**Comment by shellscape** [comment]
@Kovensky looks like you removed info from the issue template.

the goals of this module don't include supporting `webpack-cli` in reverse. they'll have to figure out how to be compatible with this module unfortunately (and that project is a bit of a mess, so it's not something I'm going to wade into until they get it organized).

the solution for the moment is to use `webpack-serve` instead of `webpack serve`. there's a 1:1 byte and keystroke ratio between the two.

**Comment by Kovensky** [comment]
That'll work if you're using `webpack-serve` to host your build, but it prevents building artifacts for deploying elsewhere.

**Comment by shellscape** [comment]
If the artifacts you're speaking of here is the config (or multiple configs), you can simply use a conditional build of the config to add `serve` properties for a development environment. if you're testing a single config on multiple development servers, you can add a condition for `webpack-serve` exclusively. 

with webpack being unfortunately strict in it's validation of the options object, that's the relatively small hoop that requires jumping through.

**Comment by Pyrolistical** [comment]
How does one detect webpack 4 development mode in webpack.config.js in order to know to add the `serve` property?

**Comment by shellscape** [comment]
@Pyrolistical that should be part of your toolchain. eg: package.json

```json
"scripts": {
  "build": "webpack",
  "build:dev": "WEBPACK_ENV=development; npm run build"
  ...
}
```

When this commit https://github.com/webpack-contrib/webpack-serve/pull/41/files#diff-168726dbe96b3ce427e7fedce31bb0bcR16 is merged and published, you'll be able to use that environment variable as well.

**Comment by xhite** [comment]
@shellscape I think it should be added to the doc
