### ISSUE TITLE
Could you plan add error overlay?

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/webpack-serve#193]
* Operating System: any
* Node Version: any
* NPM Version: any
* webpack Version: 4
* webpack-serve Version: current

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### Expected Behavior
Need to have error overlay window like weback-dev-server has

### Actual Behavior
there is no error overlay

### New Feature Use Case
add to options ```overlay: boolean```

it's easy to add this feature - have a look at this [repo](https://github.com/smooth-code/error-overlay-webpack-plugin) - modifications only need for discovery serve key in webpack options and fix registering error middleware for koa syntax

**Comment by shellscape** [comment]
Thanks for the issue :beer:

Please do try searching issues. There is a duplicate of this request here: https://github.com/webpack-contrib/webpack-serve/issues/4

**Comment by G-Rath** [comment]
@budarin if you're still wanting this, over the weekend I created & published [`webpack-serve-overlay`](https://github.com/G-Rath/webpack-serve-overlay) that uses the overlay from `webpack-dev-server`.

It should be exactly what you're after.

**Comment by budarin** [comment]
@G-Rath 
it's great! thanks!
