### ISSUE TITLE
Boilerplate code?

### ISSUE THREAD

**Issue by chobo2** [webpack-contrib/webpack-serve#196]
Hi

I am coming from webpack-dev-server and wondering if anyone has some boilerplate code on how to get up and running.

I am just using in my package.json I am have this line

`"start": "webpack-dev-server --mode development --open --hot --history-api-fallback",`

and in my webpack.config I got
```
  devServer: {
    historyApiFallback: true
  }
```

How can I get the same functionality?

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.

Boilerplate is not needed for `webpack-serve`.

>  👉🏽 Need support, advice, or help? Don't open an issue.
  Head to StackOverflow or https://gitter.im/webpack/webpack.

I've already responded on gitter and offered to help you get set up. Please connect there for further help, the issues here are not the place for support.
