### ISSUE TITLE
Possible perf_hooks memory leak detected

### ISSUE THREAD

**Issue by Jokcy** [webpack-contrib/webpack-serve#199]
* Operating System: macos
* Node Version:  9.11.1
* NPM Version:  6.1.0
* webpack Version:  4.12.0
* webpack-serve Version:  1.0.4

use as nodejs API

### Expected Behavior

without warning

### Actual Behavior

warning with message:
```
Warning: Possible perf_hooks memory leak detected. There are 996 entries in the Performance Timeline. Use the clear methods to remove entries that are no longer needed or set performance.maxEntries equal to a higher value (currently the maxEntries is 150)
```

### Code

```js
const config = {...webpackConfig}
const server = serve({ config })
```

### How Do We Reproduce?
start serve for a long time and make it rebuild about 150 times. 

Actually I found it may be a bug of `nanobus` which used by webpack-serve to emit events. nanobus will create a perfomance entry use `perf_hook` everytime it emit a event.

So I don't know if it is a bug of this project so I also create an issue to nanobus. or maybe you can change to another event emitter?

**Comment by shellscape** [comment]
Thanks for the issue :beer:

nanobus is a great, small event bus. I'd like to see how https://github.com/choojs/nanobus/issues/32 is resolved before we modify that for `webpack-serve`.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
