### ISSUE TITLE
Cannot use secure WebSockets (wss) with beta version of webpack-serve

### ISSUE THREAD

**Issue by Demivan** [webpack-contrib/webpack-serve#201]
* Operating System: Windows 10
* Node Version: v9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.14.0
* webpack-serve Version: 2.0.0-beta.4

### Expected Behavior

When specifying `https` option for `webpack-serve` `webpack-hot-client` should be using secure web sockets with provided key and cert.

### Actual Behavior

`webpack-hot-client` is started using insecure web socket connection.
When site is using SSL (https) browsers don't allow using insecure WebSocket connection.
Firefox, for example, throws exception: `SecurityError: The operation is insecure.`
So you cannot use `webpack-serve` HMR functionality on https site.

If `https` option is specified in `hotClient` options directly, `wss://` url is used, but SSL cert is wrong (looks like it is missing).

### Code

```js
serve: {
	https: {
		key: <path to key>,
		cert: <path to cert>
	},
	hotClient: {
		allEntries: true,
		https: true, // false
		hmr: true,
		autoConfigure: true
	},
	devMiddleware: {
		publicPath
	}
},
```

### How Do We Reproduce?

Specify `https` option for `webpack-serve` and check url and cert that `webpack-hot-client` uses.

**Comment by shellscape** [comment]
Thanks for the issue :beer:

This issue is being tracked here: https://github.com/webpack-contrib/webpack-hot-client/pull/80
