### ISSUE TITLE
How to log which files changed and caused webpack to reload?

### ISSUE THREAD

**Issue by JCMais** [webpack-contrib/webpack-serve#202]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

How I can access which files changed and caused webpack to recompile?

**Comment by shellscape** [comment]
Please don't remove portions of issue templates, or your issue may be closed as invalid next time. 

It looks like you chose the "Documentation" issue to ask a question looking for help. Note that we have a separate issue type specifically addressing that.

> 👉🏽 Need support, help, or advice? Don't open an issue! Head to StackOverflow or https://gitter.im/webpack/webpack.

If you legitimately feel that this is a documentation issue, please edit your issue, add the missing template sections, and provide context about what documentation you feel does not exist or is missing.

**Comment by shellscape** [comment]
Closing due to no response from OP.
