### ISSUE TITLE
beta: webpack-serve reads / parses argv in API mode, cause an error

### ISSUE THREAD

**Issue by whitetrefoil** [webpack-contrib/webpack-serve#203]
* Operating System: macOS
* Node Version: v10.5.0
* NPM Version: v6.1.0
* webpack Version: v4.14.0
* webpack-serve Version: v2.0.0-beta.4

### CLI Command

```console
  $ gulp devServer -d # using the API
```

### Expected Behavior

A dev server should start.

### Actual Behavior

```
Error: Flags were specified with invalid values:

  --config  must be set to a string

Please check the command executed.
    at validate (<MyProject>/node_modules/@webpack-contrib/cli-utils/lib/validate.js:85:15)
    at apply (<MyProject>/node_modules/webpack-serve/lib/flags.js:29:5)
    at apply (<MyProject>/node_modules/webpack-serve/lib/options.js:39:19)
    at load.then (<MyProject>/node_modules/webpack-serve/lib/options.js:118:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Code

https://github.com/whitetrefoil/vue-ts-arch/blob/b135b9914dc63d3c437da275ba835a4da9ab68bb/dev/gulp/dev-server.ts#L24

### How Do We Reproduce?

https://github.com/whitetrefoil/vue-ts-arch/blob/temp/webpack-serve-beta

### Additional Information

`webpack-serve` reads `process.argv` even using API mode, while that argv is not for `webpack-serve`.

**Comment by shellscape** [comment]
Thanks for the issue :beer: And especially for the great info.

So the API has changed. See https://github.com/webpack-contrib/webpack-serve/tree/next#serveargv-options. The first parameter is `argv`, just pass `{}` if not needed.
