### ISSUE TITLE
Multiple "host" option values

### ISSUE THREAD

**Issue by tonghae** [webpack-contrib/webpack-serve#204]
* webpack-serve Version: 1.0.4

### Feature Proposal

Ability to fill "host" option with multiple values

### Feature Use Case

For example, to set up both localhost and local ip. And be able to look for the project via wi-fi connected celly or tablet and to open localhost from dev pc/mac.

**Comment by tonghae** [comment]
Oh I needed to use '0.0.0.0' as host value

**Comment by shellscape** [comment]
Please do not remove portions of the issue template in the future.
