### ISSUE TITLE
Can this be used with webpack-command instead of webpack-cli?

### ISSUE THREAD

**Issue by dietergeerts** [webpack-contrib/webpack-serve#206]
* Operating System: Windows 10
* Node Version: 8
* NPM Version: 6
* webpack Version: 4
* webpack-serve Version: 1

### Feature Proposal

Ability to use webpack-command instead of webpack-cli

### Feature Use Case

Because it would be consistent with all modes in a project.

**Comment by shellscape** [comment]
webpack-serve doesn't rely or depend upon on webpack-cli nor webpack-command for its function.

**Comment by marcofugaro** [comment]
I think this is somehow related to https://github.com/webpack-contrib/webpack-command/issues/45

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
