### ISSUE TITLE
Use with Hapijs?

### ISSUE THREAD

**Issue by bschwartz757** [webpack-contrib/webpack-serve#207]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

While researching how to get an app that was built using `create-react-app` working with Hapi, I landed on https://github.com/webpack/webpack-dev-server#project-in-maintenance, which directed me to webpack-serve. There are some articles out there on rolling your own hapi-webpack setup, but nothing (that I've found) on making it work as part of a create-react-app setup. 

This seems to be a bit of an issue with the Webpack/React ecosystem in general - documentation is more oriented to hobby/side projects, and lacks some structure that would be very useful when trying to actually migrate existing production apps to use these tools.

### Your Proposal for Changes

**Comment by shellscape** [comment]
@bschwartz757 appreciate the issue. looks like you're more so hunting for some support or a point in the right direction, versus an issue with the documentation here. I have next to zero knowledge of Hapijs, so I'm afraid I won't be of more help. It might be a good play to try one of the support channels mentioned on the issues entry page. We'll leave this one open for a while to see if anyone else can weigh in.

**Comment by antony** [comment]
I've used [[this plugin](https://www.npmjs.com/package/hapi-webpack-dev-middleware) successfully before, so I would assume the webpack-serve integration can be done in a similar way?

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
