### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by Rouche** [webpack-contrib/webpack-serve#208]
Hello, lets try to explain this!

* Operating System: Windows 10 Pro
* Node Version: 6.11.4
* NPM Version: 6.1.0
* webpack Version: 4.15.1
* webpack-serve Version: 1.0.4
* Chrome: 67.0.3396.99

### CLI Command

From package.json
```console
webpack-serve --content ./src/html --open-path index.html
```

### Expected Behavior

No error in browser console. When using normal build and opening html directly in broswer theres no error:
```
webpack --config webpack.config.js --mode development
```

For index.html directly in browser adjust links to `../../dist/app.js` and `../../dist/app.css`

### Actual Behavior

Everything seems to be working and hot reloading too. 
I mean, i don't know if something else is broken but not in my little example.
Aditional note: 
* Changing something like color in _common.scss produces a build. But browser does not reload. I need a manual F5
* Changing something in a .js, the browser reloads fine.

Error:
[Script Loader] ReferenceError: module is not defined
    at eval (eval at module.exports (addScript.js:NaN), <anonymous>:20:1)
    at eval (<anonymous>)
    at module.exports (addScript.js:20)
    at eval (webpack://EntryPoint/(webpack)/buildin/global.js?:1:115)
    at Object../node_modules/webpack/buildin/global.js (app.js:968)
    at __webpack_require__ (app.js:726)
    at fn (app.js:103)
    at eval (punycode.js:521)
    at Object../node_modules/node-libs-browser/node_modules/punycode/punycode.js (app.js:816)
    at __webpack_require__ (app.js:726)

If i remove `script-loader` and every references to `MY_CONSOLE_GLOBAL`. The error disapear.
Is there something i need to configure with script-loader? Sadly, because of vanilla javascript, i have no choice to build with a lot of global JS.

from webpack.config.js
```
rules: [{
            test: /global\.js$/,
            use: [ 'script-loader' ]
        },
```

### Code

https://github.com/Rouche/webpack-boilerplate/tree/master/webpack-multi-setup

### How Do We Reproduce?

```
npm install
npm run start
```

**Comment by shellscape** [comment]
Thanks for the issue :beer:

Very thorough. Unfortunately this looks like an issue with your webpack config rather than `webpack-serve`. What happens when you build this with `webpack` and run in a browser _without_ going through `webpack-serve`?

**Comment by Rouche** [comment]
Hi,

Well with my repo. Normal webpack build, theres no errors. (See "Expected Behavior")
But ill work a better working example.

I just added an HTML file in `src/html/open_in_chrome.html`, with this command, you can see no errors.
```
$ npm run dev
```

It makes no sense really it should be the same build. But this made me think, ill compare everything built in `webpack-serve` with the CLI build. Stay tuned!

**Comment by Rouche** [comment]
Ok, The `app.js` files are very different.

Problem arise when `addScript` gets called incorrectly with code that fits my test. (global.js) from `webpack://EntryPoint/(webpack)/buildin/global.js?./node_modules/raw-loader`.
This is only with `webpack-serve`

code:
```
var g;

// This works in non-strict mode
g = (function() {
	return this;
})();

try {
	// This works if eval is allowed (see CSP)
	g = g || Function("return this")() || (1, eval)("this");
} catch (e) {
	// This works if the window reference is available
	if (typeof window === "object") g = window;
}

// g can still be undefined, but nothing to do about it...
// We return undefined, instead of nothing here, so it's
// easier to handle this case. if(!global) { ...}

module.exports = g;
```

I am trying to find a way to remove it.

**Comment by Rouche** [comment]
Gaaaa, Fixed. Was my fault, sorry. Normal build working lead me to the wrong place :)

Exclude node_modules with `script-loader`
```
        rules: [{
            //test: /^((?!node_modules).)*global\.js$/,
            test: /global\.js$/,
            exclude: /node_modules/,
            use: [ 'script-loader' ]
        },
```

**Comment by shellscape** [comment]
No worries, glad you were able to get there!
