### ISSUE TITLE
docs: Needed Conceptual Overview and Examples of Common Configurations

### ISSUE THREAD

**Issue by tsnieman** [webpack-contrib/webpack-serve#209]
Documentation Is:

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
Heyo :wave: It's been a while since I have setup a webpack development server / hot reloading. Jumping back in wasn't super straightforward, though I did end up getting it mostly figured out. I wanted to open an issue to address what could have helped me (and maybe even contribute to some of that change).

That said... I got the beta/v2 up and running today without too much hassle -- y'all are doing a great job with this tool so far :+1: Thanks for all your hard work.

### Your Proposal for Changes

1. Added conceptual overview
  - Think: "How does `webpack-serve` fit into the system?" or "What roles does `webpack-serve` fill?". It's nice to be reminded, and see it concisely described.
  - I know this one seems a little weird, but I think it'd be really helpful even if it doesn't strictly cover _only_ `webpack-serve`.
  - I took a stab at this sorta thing [when I added `webpack-serve` and hot reloading to this little test repo](https://github.com/tsnieman/fastify-webpack/blob/77b2f0b05d8bcf88b794175e5e0accf374600fad/client/README.md#whats-up-with-hot-module-reloading) if you want an example of what I mean.

2. Examples of common configurations
  - I think it'd be awesome to see some variations of:
    - `webpack-serve` + `react-hot-loader` + `express`
    - `webpack-serve` + `react-hot-loader` + `fastify`

Lemme know if I can clarify anything described or suggested here.

**Comment by givanse** [comment]
Maybe add an examples folder the way the Testem repo does it?
see: https://github.com/testem/testem/tree/master/examples

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
