### ISSUE TITLE
Config replaced by CLI input

### ISSUE THREAD

**Issue by MatTheCat** [webpack-contrib/webpack-serve#210]
This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve webpack.config.js
```

##### serve.config.js

```js
module.exports = {
  host: '0.0.0.0'
}
```

### Expected Behavior

Host is `0.0.0.0`

### Actual Behavior

Host is the default `localhost`

### How Do We Reproduce?

Use cosmiconfig to set webpack-serve configuration while setting webpack configuration file in the CLI.

I guess this comes from https://github.com/webpack-contrib/webpack-serve/compare/v1.0.3...v2.0.0#diff-f8849ae9f0614ba9464fdd14c2d98dc0R54 which makes the CLI input the whole config.

**Comment by shellscape** [comment]
Thanks for the issue :beer: Try those betas. We put those up to try and catch these regressions before they sneak into a release. 

Your diff link doesn't show any diff though. Is there another diff you'd like to highlight?

**Comment by MatTheCat** [comment]
Woops GitHub messed the autolink.

cli.js
```diff
-if (cli.input.length) {	
-  [options.config] = cli.input;	
-} else if (flags.config) {	
-  options.config = flags.config;	
-}
```

lib/cli.js
```diff
+if (cli.input.length) {
+  [config] = cli.input;
+}
```

**Comment by shellscape** [comment]
Ah I see what happened. fwiw the loading of config from flag was moved to https://github.com/webpack-contrib/webpack-serve/blob/d896e2e300d08621ca3b1aa0ff584efa8c6700de/lib/config.js#L65

But yeah the serve options aren't being sent along correctly. I'll get a fix up shortly.

**Comment by MatTheCat** [comment]
Thanks, checking this out tomorrow!
