### ISSUE TITLE
--require flag results in error "--r  Not sure what you mean there"

### ISSUE THREAD

**Issue by jonesnc** [webpack-contrib/webpack-serve#213]
* Operating System: Mac OS X 10.13.5
* Node Version: 10.5.0
* NPM Version: 6.1.0
* webpack Version: 4.15.1
* webpack-serve Version: 2.0.1
* webpack-cli Version: 3.0.8

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve --require @babel/register --config ./webpack.dev.babel.js
```

##### webpack configs gits
https://gist.github.com/jonesnc/a2bcae79e81e756ec64030eadb06e789

### Expected Behavior
Webpack-serve to include the `@babel/register` module, and then start the webpack-serve dev server.
### Actual Behavior
```
ℹ ｢config｣: Requiring the @babel/register module
Error: Flags were specified that were not recognized:

  --r  Not sure what you mean there

Please check the command executed.
    at validate (/Users/user/.config/yarn/global/node_modules/@webpack-contrib/cli-utils/lib/validate.js:103:15)
    at apply (/Users/user/.config/yarn/global/node_modules/webpack-serve/lib/flags.js:29:5)
    at apply (/Users/user/.config/yarn/global/node_modules/webpack-serve/lib/options.js:39:19)
    at load.then (/Users/user/.config/yarn/global/node_modules/webpack-serve/lib/options.js:118:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```
### How Do We Reproduce?

- Create a `package.json` file with the `devDependencies` listed in the gist linked above.
- Run `npm install` or `yarn install`
- Make sure `webpack` and `webpack-serve` are installed globally
- Run `webpack-serve --require @babel/register --config ./webpack.dev.babel.js`

### Repo

https://github.com/IronCountySchoolDistrict/ps-plugin-boilerplate

**Comment by shellscape** [comment]
Thanks, I'll investigate. Please do try the betas when they are listed. We issue those to try and catch bugs like these before releasing.

**Comment by jonesnc** [comment]
Will do. It looks like this regression happened pre-`2.0.0-beta.1`, as I can reproduce this issue using that version. `1.0.4` does not appear to have this issue.

**Comment by shellscape** [comment]
Fixed in https://github.com/webpack-contrib/cli-utils/commit/cced3b7259da7e07ad8f1ff1258b0f354d8a4d79

I'll publish a patch version to make sure the new version of this dependency is pulled down.
