### ISSUE TITLE
Hot client port seems to be ignored

### ISSUE THREAD

**Issue by MatTheCat** [webpack-contrib/webpack-serve#218]
* Operating System: Alpine 3.7.0
* Node Version: 10.6.0
* NPM Version: 6.1.0
* webpack Version: 4.15.1
* webpack-serve Version: 2.0.2
* webpack-hot-client Version: 4.1.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve docs/webpack.config.js
```

##### serve.config.js

```js
module.exports = {
  clipboard: false,
  devMiddleware: {
    publicPath: '/pattern-library/dist/'
  },
  hotClient: {
    allEntries: true,
    host: {
      client: '*',
      server: '127.0.0.1'
    },
    port: {
      client: 8082,
      server: 8081
    }
  },
  host: '0.0.0.0'
}
```

### Expected Behavior

Websocket client uses client port 8082.

### Actual Behavior

Websocket client try using server port 8081 and fails.

![](https://user-images.githubusercontent.com/1898254/42503601-63e71d72-8439-11e8-84d2-f3c479290b89.png)

### How Do We Reproduce?

Set `hotClient.port` as an object.

**Comment by MatTheCat** [comment]
Maybe this is a webpack-hot-client issue. `options.webSocket.port changes between `modifyCompiler` call (where it has the right value) and `beforeCompile` event (where it takes value from `port.server`).

No idea why this happens.

**Comment by shellscape** [comment]
Yeah, that's an issue for `webpack-hot-client`. Please open it up over at https://github.com/webpack-contrib/webpack-hot-client

**Comment by MatTheCat** [comment]
Done https://github.com/webpack-contrib/webpack-hot-client/issues/86
