### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Sibiraj-S** [webpack-contrib/webpack-serve#219]
* webpack-serve Version: 2.0.2

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Actual Behavior

The Readme is quite confusing at start

Also now there are two config properties, which will be considered as priority?

**Comment by Sibiraj-S** [comment]
My bad got confused while going through the docs. I needs to be more clear I think.

**Comment by shellscape** [comment]
Sorry you feel that way, but there is only [one `config` option](https://github.com/webpack-contrib/webpack-serve#optionsconfig).

Please don't ignore issue template instructions, you should not remove sections of issue templates.

**Comment by Sibiraj-S** [comment]
Actually, It is allowed to pass `path of the config` file in `argv` so two. `option.config` is ignored if config is already loaded.

**Comment by shellscape** [comment]
Actually, you are confusing argv/flags and options when using the API. If you are going to use the API, you must fully understand it. Otherwise, use the CLI.
