### ISSUE TITLE
Build is failing with webpack-serve, though working with just webpack --watch

### ISSUE THREAD

**Issue by dietergeerts** [webpack-contrib/webpack-serve#220]
* Operating System: Windows 10
* Node Version: 8
* NPM Version: 6
* webpack Version: 4.15
* webpack-serve Version: 2.0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

##### webpack.config.js

[link to gist](https://gist.github.com/dietergeerts/d6c0bc2c607e6035a5ccf95a4d44abd4)

### Expected Behavior

That it works with the current settings...

### Actual Behavior

It gives the following error:

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Compiler.<anonymous> (D:\Projects\mdt-app\toolkit-next\node_modules\spawn-loader\index.js:50:88)
    at hooks.afterCompile.callAsync.err (D:\Projects\mdt-app\toolkit-next\node_modules\webpack\lib\Compiler.js:553:14)
```

### How Do We Reproduce?

Can't share a link, as it's a private repo.
But I can tell you all I already discovered myself. I also don't know if it is because of webpack-serve, or webpack itself though.

1. In the first setup, I used the same config, but without the output property and with `webpack --watch`. That was working.
1. Then I added the output property, and I saw the exact same error popping up. I had set the property to:
```
{
    filename: '[name].[hash].js',
}
```
1. After debugging, I found out that adding the `chunkFilename` solved the issue, as the chunk files where empty in spawn-loader because of it. So webpack didn't add them because the property was missing.
1. Then I tried webpack-serve, and I get the error again.

So I think for some reason, webpack doesn't receive a certain property from webpack-serve, or there is another property needed to make it work. That's how far I got. So hopefully, you guys have a better idea of what is causing this.

**Comment by Sibiraj-S** [comment]
this happens in output path.

**Comment by shellscape** [comment]
Few things that stand out with your issue:

- `webpack-serve` doesn't appear in your stack trace (nor do any modules in webpack-contrib, which this module depends upon)
- `webpack-serve` isn't in the business of adding compiler-critical values to the configs
- [`webpack-dev-middleware`](https://github.com/webpack/webpack-dev-middleware/tree/master/lib) handles running the compiler, and watching for file changes.

No idea why your config isn't working. You should probably knock your config down to a minimal case and build it back up to identify the problem. 99% of the time problems like this exist within the users' config.

Since your repo is closed and can't be shared, I'm afraid you're going to have to debug the problem.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
