### ISSUE TITLE
feat: allow appending path to cli output

### ISSUE THREAD

**Issue by daviestar** [webpack-contrib/webpack-serve#224]
* Operating System: OS X 10.13.5
* Node Version: 10.4.1
* NPM Version: 6.1.0
* webpack Version: 4.15.0
* webpack-serve Version: 2.0.2

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

##### webpack.config.js

```js
config.serve = {
  port,
  host,
  add: (app) => {
    app.use(compress())
    app.use(history())
  },
  hotClient: {
    logLevel: 'info',
    logTime:  true
  },
  devMiddleware: {
    logLevel: 'warn'
  },
  // open: {
  //   app:  'My project,
  //   path: '/some/app/path/1337'
  // },
  logLevel:  'info',
  logTime:   true
}
```
![screen shot 2018-07-11 at 09 55 09](https://user-images.githubusercontent.com/959906/42561389-ecf61c32-84f0-11e8-8fd2-fe47e9284840.png)

### New Feature Use Case

Using the `open` option, I can specify a `path` to the URL of my project, which works as expected.

However I'd rather just click the link on the terminal:
```
Project is running at http://localhost:3001/some/app/path/1337
```

But AFAICS it's not possible just now:

https://github.com/webpack-contrib/webpack-serve/blob/4c7ad1bc543628a2c1b36d0de7e2adb28eb00f91/lib/server.js#L16-L18

I was able to achieve what I wanted but it's messy:

```js
config.serve = {
  port,
  host,
  add: (app) => {
    app.use(compress())
    app.use(history())
  },
  on: {
    'build-finished': () => {
      console.log(`Project is running at http://${host}:${port}/some/app/path/1337`)
    }
  },
  hotClient: {
    logLevel: 'info',
    logTime:  true
  },
  devMiddleware: {
    logLevel: 'warn'
  },
  logLevel:  'info',
  logTime:   true
}
```
![screen shot 2018-07-11 at 10 40 31](https://user-images.githubusercontent.com/959906/42563748-e4e597e2-84f6-11e8-8d8a-ae51d269d065.png)

Happy to provide a PR for this, but please let me know what the preferred options configuration might look like, as `open.path` doesn't make sense in this case.

Cheers.

**Comment by shellscape** [comment]
Thanks for the great feature issue. :beer:

_Something of note: most terminal/console environments don't have clickable url functionality without adding it on. At least, that was true when I looked into it about 6 months ago_

I'm afraid that this one falls into the category of "more trouble that it's worth." To implement this, we'd need some nutty logic around _which_ `content` path to use (because that option can accept an array of them), or to use `config.output.publicPath` - and then in the case of `MultiCompiler`, which one of those to use when they're setup differently. That's an awful lot of considerations for a few characters in the console.

I think for the time being your solution is the best one, and far less messy than it would be to implement a solution that worked for every user.

**Comment by daviestar** [comment]
Just a little note on your note!  In iTerm if you hold command when hovering text, it turns text links into a clickable links - bit of a hidden feature you might not know about, if you use iTerm...

What about passing `chalk` and `log` through to events?

```js
on: {
  'build-finished': (e, { log, chalk }) => {
    const uri = `http://${host}:${port}/some/app/path/1337`
    log.info(chalk`Project is running at {blue ${uri}}`)
  }
}
```

**Comment by shellscape** [comment]
Neat. I'll have to try that.

As for passing dependencies, I'd rather avoid that. It's added complexity for likely little gain across the ecosystem and not likely a common need. Passing log would not be a good idea, as your goal there is to produce output that looks like it's coming from `webpack-serve`, when in fact it's coming from a custom event handler - there's not much benefit to doing that, and you might actually end up confusing other users in your org/team as to the source of the message if something goes awry.

**Comment by daviestar** [comment]
Yeah fair enough. In case anyone else lands here, here's what I ended up doing:

```js
config.serve = {
  port,
  host,
  add: (app) => {
    app.use(compress())
    app.use(history())
  },
  on: {
    'build-finished': () => {
      const d = new Date()
      const h = String(d.getHours()).padStart(2, 0)
      const m = String(d.getMinutes()).padStart(2, 0)
      const s = String(d.getSeconds()).padStart(2, 0)
      const timestamp = `[${h}:${m}:${s}]`
      const msg = `Project is running at http://${host}:${port}/some/app/path/1337`
      setTimeout(() => {
        console.log(`${timestamp} ✨ ${msg}`)
      }, 10)
    }
  },
  hotClient: {
    logLevel: 'info',
    logTime:  true
  },
  devMiddleware: {
    logLevel: 'warn'
  },
  logLevel:  'warn',
  logTime:   true,
  clipboard: false
}
```
![screen shot 2018-07-11 at 14 05 14](https://user-images.githubusercontent.com/959906/42573257-7f07be88-8513-11e8-9953-588cf86665ef.png)
