### ISSUE TITLE
No way to set mode with no-config webpack 4

### ISSUE THREAD

**Issue by cilliemalan** [webpack-contrib/webpack-serve#225]
There currently seems to be no way to set the `mode` property Webpack [requires](https://webpack.js.org/concepts/mode/) when not using a `webpack.config.js` file. As of version 4, webpack [doesn't require any configuration](https://webpack.js.org/guides/getting-started/#using-a-configuration), but, if no configuration file is present, `webpack-serve` always works in production mode and produces a warning.

* Operating System: Windows
* Node Version: 10.1.0
* NPM Version: 5.5.1
* webpack Version: 4.16.0
* webpack-serve Version: 2.0.2

This issue is for a:

- [ ] **bug**
- [X] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

##### webpack.config.js
`webpack.config.js` *does not exist*

### Expected Behavior
You should be able to set `mode` without having to create a configuration file with the sole purpose of setting the mode.

### Actual Behavior
There is no way to set the mode apart from creating a configuration file. When running `webpack-serve`, you always get a production build with the following warning printed in the console:

```
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/
```

### How Do We Reproduce?
Follow the Webpack [Getting Started](https://webpack.js.org/guides/getting-started/) guide up until [Creating a Bundle](https://webpack.js.org/guides/getting-started/#creating-a-bundle). Then install the `webpack-serve` package and run it.

### New Feature Use Case

One possible solution is to add a `--mode` argument like `webpack-cli`. Another option could be to use an environment variable or to default `mode` to either `production` or `development` when no config file is present (`development` seems to make the most sense).

**Comment by shellscape** [comment]
Happy to review a PR that implements either solution. Both seem reasonable to me.

**Comment by cilliemalan** [comment]
On it

**Comment by nicoabie** [comment]
Webpack supports returning a function as its module exports config value.
[see](https://webpack.js.org/concepts/mode/#mode-none)

@cilliemalan  Can the --mode flag be redirected to the argv?

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
