### ISSUE TITLE
2.0.2: options.hotClient.server ignored when using options.https

### ISSUE THREAD

**Issue by stnwk** [webpack-contrib/webpack-serve#226]
* Operating System: macOS 10.13.3
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.16.0
* webpack-serve Version: 2.02

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### webpack.config.js

```js
import { createServer } from 'https';
import { certificateFor } from 'devcert';
import { serve } from 'webpack-serve';

// generate valid https certificate
const https = await certificateFor('localhost', {
  skipHostsFile: true,
  skipCertuil: false,
});

// create https server
const socketServer = createServer(https).listen(
  {
    host: 'localhost',
    port: 3010,
  },
  (err) => {
    if (err) {
      return console.log(err);
    }

    // 
    serve(
      {},
      {
        host: 'localhost',
        port: 3000,
        hotClient: {
          https: true,
          logLevel: 'info',
          autoConfigure: true,
          allEntries: true,
          server: socketServer, /* attach hot client web socket to custom server */
        },
        https,
      },
    )
  }
);
```

### Expected Behavior
Before 2.0.2 this code worked as expected: It would create an https server on `https://localhost:3010`, serve the webpack output on `https://localhost:3000` and attach the hot client websocket to the custom created https server on port **3010**.

### Actual Behavior
After upgrading to 2.0.2 this does not work anymore.

I believe I found the culprit here: https://github.com/webpack-contrib/webpack-serve/blob/4c7ad1bc543628a2c1b36d0de7e2adb28eb00f91/lib/middleware/WebpackMiddleware.js#L26

```js
    if (options.https) {
      server = getServer(null, options);
      koaWebpackOpts.hotClient.server = server;
    }
````

This code basically overrides the passed `options.hotClient.server` when `options.https` is passed. The underlying `getServer()` method creates its own http(s) server depending on wether `options.https` is set, but ignores the fact the `options.hotClient.server` is a valid option to pass and it should attach the websocket to it instead of overriding.

I hope it's clear what I mean. If you need anymore details I'd be happy to provide them!

**Comment by shellscape** [comment]
Good catch. Looks like there's another logical check that needs to go in that `if` statement where you found the problem.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
