### ISSUE TITLE
List compiled files in browser

### ISSUE THREAD

**Issue by ahmehri** [webpack-contrib/webpack-serve#227]
* Operating System: Ubuntu 16.04 LTS
* Node Version: 10.3.0
* NPM Version: 6.1.0
* webpack Version: 4.10.2
* webpack-serve Version: 2.0.2

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### New Feature Use Case

Using `webpack-dev-server` we can list the compiled files in the browser using the special `/webpack-dev-server` URL. Does `webpack-serve` provides the same feature?

**Comment by shellscape** [comment]
`webpack-serve` does not. Please use the `Source` tab in your browser's Developer Tools to inspect your bundle.
