### ISSUE TITLE
Setting hotClient to false results in an error

### ISSUE THREAD

**Issue by Nikki1993** [webpack-contrib/webpack-serve#233]
### System Info

* Operating System: Arch Linux
* Node Version: v10.6.0
* NPM Version: 6.1.0 (using yarn though so 1.8.0)
* webpack Version: 4.16.0
* webpack-serve Version: 2.0.2

### This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
cross-env NODE_ENV=development ts-node ./node_modules/.bin/webpack-serve --config ./webpack.config.ts",

```

##### webpack.config.js

Using typescrypt so it's a webpack.config.ts
https://gist.github.com/Nikki1993/0c0a59af462f2b662446be6d10180255
Check the development object key for dev configuration in question

### Expected Behavior
Settings hotClient disables hot module replacement completely

### Actual Behavior
Setting hotClient results in the following error

```
(node:7176) ExperimentalWarning: The http2 module is an experimental API.
TypeError: Cannot create property 'server' on boolean 'false'
    at WebpackMiddleware.call (/home/nick/git/tieto_eb_client/node_modules/webpack-serve/lib/middleware/WebpackMiddleware.js:26:39)
    at MiddlewareState.call.args (/home/nick/git/tieto_eb_client/node_modules/webpack-serve/lib/middleware/MiddlewareState.js:11:17)
    at /home/nick/git/tieto_eb_client/node_modules/webpack-serve/node_modules/mem/index.js:36:18
    at series (/home/nick/git/tieto_eb_client/node_modules/webpack-serve/lib/app.js:50:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
### How Do We Reproduce?

Supposedly, setting hotClient to false is enough.

P.S. P.S. I created my own types for webpack-serve since supplied one are outdated and haven't had the chance to submit a PR yet.

**Comment by shellscape** [comment]
Holy crap that's a huge config. Are you setting up `https` by chance?

**Comment by Nikki1993** [comment]
Yea types make it huge :D plus both prod and dev configs are in there, makes it easier to pass envs. 

Yea, I do. I set it dynamically based on the presence or absence of .cert and .key
```
const useHttps = (): IServeConfiguration  => {
  if (fs.existsSync('localhost.cert') && fs.existsSync('localhost.key')) {
    console.log('\x1b[32m', 'Localhost certificates are present, project will be built with HTTPS support')
    return {
      https: {
        key: fs.readFileSync('localhost.key'),
        cert: fs.readFileSync('localhost.cert'),
      },
      http2: true,
    }
  }
  else {
    console.log('\x1b[31m', 'No localhost certificates are present, project will be built without HTTPS support')
    return {};
  }
};
```

**Comment by Nikki1993** [comment]
Worth noting that prior to 2.0 release this very same setup worked perfectly and HMR was disabled. The only changed between now and then was the rename from **hot** to **hotClient**

**Comment by shellscape** [comment]
> Worth noting that prior to 2.0 release this very same setup worked perfectly and HMR was disabled. The only changed between now and then was the rename from hot to hotClient

That's not correct. `webpack-hot-client` reworked a lot of how HTTPS was handled, and so did `webpack-serve` between 1.x and 2.x, not to mention a significant refactor. We had a beta up for about three weeks, could've used the input.

Based on the stack trace, here's the problem https://github.com/webpack-contrib/webpack-serve/blob/master/lib/middleware/WebpackMiddleware.js#L26. Looks like it shouldn't do that if `hotClient: false`. I'm short on time, so we'd happily review a PR in the mean time.

**Comment by Nikki1993** [comment]
My bad, I meant API usage wise. I realized that internally it was a massive change.

I was on vacation the entire beta release so could not have caught it any earlier :D

**Comment by shellscape** [comment]
Well hopefully the vacation was fun 🌴

**Comment by kspearrin** [comment]
I'm seeing this now too after moving to v2.0 /w `hotClient: false` and `https`. Config:

```
{
    https: {
        key: fs.readFileSync('dev-server.pem'),
        cert: fs.readFileSync('dev-server.pem'),
    },
    hotClient: false,
}
```

**Comment by Nikki1993** [comment]
@kspearrin best course of action at this point is to switch back to webpack-dev-server as in the near future these two projects are gonna merge features.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
