### ISSUE TITLE
Warning about missing mode option when using webpack-merge and webpack-serve node API

### ISSUE THREAD

**Issue by sqal** [webpack-contrib/webpack-serve#234]
* Operating System: Windows 10
* Node Version: 10.4.1
* NPM Version: 6.1.0
* webpack Version: 4.16.0
* webpack-serve Version: 2.0.2

### Expected Behavior

Shouldn't raise an error about missing `mode` in webpack's configuration.

### Actual Behavior

In my project i split my webpack configuration into multiple files, like base/dev/prod. I use `webpack-config` to merge base configuration with the development/production configuration and I am getting an error about missing mode option (although it's always set) in situation when I use webpack-config along with webpack-serve node API.

```console
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/
```

### Code

Reproduction: 

https://github.com/sqal/webpack-serve-mode-bug

### How Do We Reproduce?

- Clone repo, dependencies
- Run `npm run dev`, webpack-serve will launch the server with mentioned warning ❌
- Run `npm run dev:cli` (runs webpack-serve from cli) - no warning ✅
- Now go to `webpack.config.dev` file, comment code that does not work, and uncomment code that uses Object.assign
- Run `npm run dev` - no warning this time ✅

**Comment by shellscape** [comment]
This doesn't sound like a problem in `webpack-serve` and more likely related to your environment. I would encourage you to find the cause, and if it is indeed in `webpack-serve`, open a PR to resolve it.

**Comment by sqal** [comment]
Hmm this is really weird, what I did now, in `webpack.config.dev.js` i shallow clone the configuration returned from webpack-config like this

```js
module.exports = {
  ...new Config()
    .extend('webpack.config.js')
    .merge(devConfig) 
}
```
and the warning is gone. Any idea why it did not work before?

**Comment by sqal** [comment]
I think it's caused by this line https://github.com/webpack-contrib/webpack-serve/blob/master/lib/config.js#L18 because it returns false when i log:

```js
const cfg = new Config()
  .extend('webpack.config.js')
  .merge(devConfig);


console.log(isPlainObject(cfg)) // false
```

**Comment by sqal** [comment]
I think there someting wrong with this check https://github.com/webpack-contrib/webpack-serve/blob/master/lib/config.js#L71 because when i log config returned from webpack-config, isPlainObject returns false


```js
const cfg = new Config()
  .extend('webpack.config.js')
  .merge(devConfig);


console.log(isPlainObject(cfg)) // false
```

**Comment by mkungla** [comment]
Isn't that similar as issue webpack-contrib/webpack-command#27 and relatd PR webpack-contrib/webpack-command#29 ?

**Comment by shellscape** [comment]
@sqal if `is-plain-obj` is returning false, then there's likely something wrong with the object you're returning, versus something wrong with that `if` statement. I'd recommend taking your config and trying the `extends` functionality instead. If that doesn't work, break your config down into simple pieces to try and identify the problem's cause. 9 times out of 10 issues like these end up being a problem with the config.

**Comment by sqal** [comment]
@shellscape Apologies for not replying but I was busy at work and had no time to look at this issue more closely. I don't know if I understand what you mean by "try extends functionality". You mean I should clone the object and then pass to the `serve` function like thi:

```
serve({}, {
  config: { ...myConfig }
} 
```

? As I said before, this actually fixes the issue, although I don't know why i have to do this. I also think there's notihing wrong with the config object itself. I mean, when I am passing the same config directly to the webpack compiler (`webpack(myConfig)`) then it does not complain and builds my project correctly. So with that being said I still believe that the problem lies in webpack-serve and probably and this [line](https://github.com/webpack-contrib/webpack-serve/blob/master/lib/config.js#L71). I checked why is-plain-ob is returning false with my config and turns out it fails exactly in this line https://github.com/jonschlinkert/is-plain-object/blob/master/index.js#L31 so I'm not sure what to do next with it 🤔

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
