### ISSUE TITLE
Cannot find module 'webpack/schemas/WebpackOptions.json'

### ISSUE THREAD

**Issue by givanse** [webpack-contrib/webpack-serve#235]
For the benefit of future devs googling errors. (probably me again)

If you see the error `Cannot find module 'webpack/schemas/WebpackOptions.json'`

The issue is that you are using a version of `webpack-serve` that is not compatible with `webpack`. I was using webpack 3 and webpack-serve 2. The last version to support Webpack 3 is `webpack-serve 0.1.5`

**Comment by shellscape** [comment]
The minimum required version of webpack is listed in two places:

- https://github.com/webpack-contrib/webpack-serve#requirements
- https://github.com/webpack-contrib/webpack-serve/blob/master/package.json#L51

*Whenever* you upgrade from a 0.x version to a major version, you should check your requirements. 0.x versions are not beholden to semver rules and standards.
