### ISSUE TITLE
`options.add` doesn't catch errors

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/webpack-serve#236]
* Operating System: Ubuntu 18.04
* Node Version: v8.11.3
* NPM Version: 6.2.0
* webpack Version: 4.16.1
* webpack-serve Version: 2.0.2

### Expected Behavior

Should immediate stop and throw error.

### Actual Behavior

Throw error only after `ctrl+c`

### Code

From example https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/proxy-router.config.js

```js
module.exports.serve = {
  content: [__dirname],
  add: (app, middleware, options) => {
    // this example shows how to properly add middleware _after_ the built-in
    // webpack and content middleware. since middleware must be added at the
    // end of the middleware stack, we have to call the default middlewares
    // ourselves
    middleware.webpack().then(() => {
      middleware.content({
        index: 'index.htm',
      });

      throw new Error('Something wrong');

      // this example assumes router must be added last
      app.use(router.routes());
    });
  },
};
```

### How Do We Reproduce?

Use code above and run

**Comment by shellscape** [comment]
You should `catch` on that promise.

**Comment by evilebottnawi** [comment]
@shellscape it makes no sense (because it is just function call https://github.com/webpack-contrib/webpack-serve/blob/master/lib/app.js#L45), try to add `catch` in example - nothing happened

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
