### ISSUE TITLE
Custom middleware order in documentation

### ISSUE THREAD

**Issue by danmartens** [webpack-contrib/webpack-serve#238]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

I've been using the `add` option for adding custom routes from a koa-router `Router` to my webpack development environment. In the current documentation, there seems to be two different orders specified for calling `middleware.webpack()` and `middleware.content()`:

- https://github.com/webpack-contrib/webpack-serve#optionscontent
- https://github.com/webpack-contrib/webpack-serve#add-function-parameters

Neither of the orders documented seem to work consistently for me (I'm guessing a because of a race condition?). Calling `middleware.content()` inside of the "resolve" callback for `middleware.webpack()` does seem to work consistently though. I am I misunderstanding something or should the docs be updated?

### Your Proposal for Changes

Replace the two examples with something like this:

```javascript
add: (app, middleware, options) => {
  middleware.webpack().then(() => {
    middleware.content();

    app.use(router.routes());
  });
}
```

**Comment by agilgur5** [comment]
Had the same issue, placing `middleware.content()` in the resolve callback instead of directly after similarly fixed the problem for me. Thanks @danmartens !

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
