### ISSUE TITLE
Server not running when both https & h2 are configured

### ISSUE THREAD

**Issue by pruett** [webpack-contrib/webpack-serve#241]
* Operating System: macOS High Sierra 10.13.6
* Node Version: v10.4.0
* NPM Version: yarn version 1.7.0
* webpack Version: 4.16.1
* webpack-serve Version: 2.0.2

### Expected Behavior

Client to load without errors.

### Actual Behavior

Client reports errors with Websocket connection

```js
// In browser
WebSocket connection to 'wss://wp-local.com:55420/' failed: Error during WebSocket handshake: Unexpected response code: 403
connect @ socket.js:19
14:05:27.450 
```

```bash
# In console
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onread (net.js:656:25)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
```

### Code

```js
// webpack-serve config
handleCerts().then(() => {
    const serverOptions = {
        add(app, middleware, options) {
            app.use(convert(history()));
            app.use(
                webpackServeWaitpage(options, {
                    title: "️🌎",
                    theme: "material",
                })
            );
        },
        config,
        host,
        https: {
            key: <link_to_key>
            cert: <link_to_cert>
        },
        open: true,
        hotClient: {
            host,
            https: true,
        },
        http2: true, // removing this line makes the dev server work
    };
    serve(argv, serverOptions).then(server => {
        server.on("listening", () => {});
    });
});

```

### How Do We Reproduce?

Conifgure webpack-serve to use https with the proper credentials (everything should work). Kill server and add `http2: true` to webpack-serve's options and it will break with Websocket handshake error.

**Comment by shellscape** [comment]
Bummer. Happy to review a Pull Request.

**Comment by pruett** [comment]
I see that h2 is labeled as experimental, but I first wanted to call it out in case someone has already addressed this.

**Comment by huijiewei** [comment]
I found if enable https, WebpackMiddleware.js be change hotClient.server to getServer, when enable http2 getServer will return http2 server, but hotClient's WebSocket Serve not support http2
https://github.com/websockets/ws/issues/1293

sorry, i can't post a success pr.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
