### ISSUE TITLE
'listening' event is not emmited

### ISSUE THREAD

**Issue by everdimension** [webpack-contrib/webpack-serve#242]
* Operating System: mac 10.13.4
* Node Version: `v9.11.1`
* NPM Version: `v6.2.0`
* webpack Version: `v4.16.1`
* webpack-serve Version: `v2.0.2`

### Expected Behavior

According to these [docs](https://github.com/webpack-contrib/webpack-serve/tree/80c0b5d64faa57f4608d99f42b54b24a1340fa3b#events), I write something like this:
```js
serve(/* ... */).then(server => {
  server.on('build-started', () => console.log('started'));
  server.on('listening', () => console.log('listening'));
});
```

I expect to see both `started` and `listening` in the terminal output.

### Actual Behavior

I don't see `listening` in the terminal output.

**Comment by shellscape** [comment]
Read the breaking changes: https://github.com/webpack-contrib/webpack-serve/releases/tag/v2.0.0

If you're in that `then` handler, then the server is already listening. Looks like the README needs to be updated. Happy to review a PR.

**Comment by everdimension** [comment]
@shellscape I see, thanks.
Here's a PR: https://github.com/webpack-contrib/webpack-serve/pull/243

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
