### ISSUE TITLE
How do I define webpack-serve options in my webpack conf?

### ISSUE THREAD

**Issue by nikolas** [webpack-contrib/webpack-serve#245]
The README says:

> It's most common to keep serve options in your webpack.config.js (see below),

But... looking below, I don't see any example of this. Where is it?

Documentation Is:

- [ ] Missing
- [ ] Needed
- [X] Confusing
- [ ] Not Sure?

**Comment by shellscape** [comment]
https://github.com/webpack-contrib/webpack-serve#webpack-config-serve-property

If you're not familiar with how to define properties in webpack.config.js, you should immediately learn about webpack and it's config before going any further with this module. Also, please try one of the support options mentioned before opening a question issue.

**Comment by nikolas** [comment]
I am familiar with how to define properties in webpack.config.js - it's more that the wording here just isn't accurate. I suggest just removing the "(see below)" text since there is no example webpack config below it.
