### ISSUE TITLE
iOS Safari Render Issue

### ISSUE THREAD

**Issue by dcflow** [webpack-contrib/webpack-serve#246]
* Operating System: Windows 10
* Node Version: 10.4.0
* NPM Version: 6.1.0
* webpack Version: 4.12.0
* webpack-serve Version: 2.0.2

### Expected Behavior

The page served with `webpack-serve` or `webpack-dev-server` works fine on Chrome for iOS but it doesn't work on iOS Safari.

The page stays blank and this is the net log (no errors in the console).

![screenshot 2018-07-24 19 56 22](https://user-images.githubusercontent.com/6751025/43157159-6e285348-8f7c-11e8-88c2-277d4db7c010.png)

Thank You!

**Comment by shellscape** [comment]
> 👉🏽 Need support, help, or advice? Don't open an issue! Head to StackOverflow or https://gitter.im/webpack/webpack.

**Comment by dcflow** [comment]
@shellscape You are confident that it isn't the servers fault that the page loads on iOS Chrome and not on iOS Safari?

**Comment by dcflow** [comment]
@shellscape It also works on Firefox iOS, Opera iOS ... on Safari it doesn't get the js files from the server.

**Comment by dcflow** [comment]
It had Javascript disabled .. sigh

**Comment by shellscape** [comment]
😉
