### ISSUE TITLE
Problem when using minimist

### ISSUE THREAD

**Issue by aczekajski** [webpack-contrib/webpack-serve#249]
* Operating System: Windows 10
* Node Version: 8.9.3
* NPM Version: 6.1.0
* webpack Version: 4.12.0
* webpack-serve Version: 2.0.2

### Expected Behavior

The documentation states that `argv` parameter of `serve` method is "_An object containing the parsed result from either minimist or yargs-parser_". So, when I pass the result of `minimist`'s `parseArgv` directly as the first argument to `serve` method, it should just work correctly.

### Actual Behavior

It exits with error:
```
Error: Flags were specified that were not recognized:

  --_  Not sure what you mean there
```

### Code

```js
import * as serve from 'webpack-serve';
import * as parseArgv from 'minimist';
import config from './dev';

console.log(process.argv.slice(2));
const argv = parseArgv(process.argv.slice(2));
console.log(argv);
serve(argv, { config });
```

I run the code without any arguments. This code produces the following output:
```
[]
{ _: [] }
```
and of course the error I mentioned above. As you can see, there are no arguments, just the usual `_` field which is a correct output of `minimist`.

### How Do We Reproduce?

Run the above code with any config.

**Comment by shellscape** [comment]
Well `_` is pretty moot in this context, and it's not a valid flag for `webpack-serve`, so it shouldn't exit on that object. Why not just `delete argv._`? If you'd like to take the time to submit a PR to have the API entrypoint do that before it's validated, I'd be happy to review it. But seems like it'd just be easier to delete that property before passing `argv`.

**Comment by aczekajski** [comment]
I can look into the code and submit PR with the modification but before I do that, the question is if you want the parsers-specific logic incorporated into the library. Maybe some clarification in docs will be enough?

Btw, I just checked, and `yargs-parser` does the same thing with `_`.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
