### ISSUE TITLE
stats options are ignored using the 'dev' key but works with 'devMiddleware'

### ISSUE THREAD

**Issue by axelo** [webpack-contrib/webpack-serve#250]
* Operating System: MacOS High Sierra 10.13.5
* Node Version: 8.11.1
* NPM Version: 5.6.0
* webpack Version: 4.16.1
* webpack-serve Version: 2.0.02

### Expected Behavior

When setting 

`serve: {
    dev: {
        stats: 'none'
    }
}`

in webpack config, or in package.json no stats are outputted.

### Actual Behavior

Stats are outputted as the option is ignored.

### Code

[webpack config](https://gist.github.com/axelo/94c4e82bf6ae87e347c163690bc5d64a#file-webpack-config-js-L136)

### How Do We Reproduce?

Using same version of webpack and webpack-serve and try change the stats config and run

`webpack-serve` on any project.

## Workaround

I investigated the options object webpack-serve received, and by changing from 'dev' to 'devMiddleware' everything works as expected.

Maybe webpack has changed the key from 'dev' to 'devMiddleware' on some later releases?

**Comment by shellscape** [comment]
It pays to read the release notes for major versions: https://github.com/webpack-contrib/webpack-serve/releases/tag/v2.0.0

https://github.com/webpack-contrib/webpack-serve#optionsdevmiddleware

**Comment by axelo** [comment]
Ah sorry, ill do that next time!
