### ISSUE TITLE
Webpack command line progress

### ISSUE THREAD

**Issue by aaronbeall** [webpack-contrib/webpack-serve#253]
* Operating System: MacOS High Sierra
* Node Version: v8.11.3
* NPM Version: 5.6.0
* webpack Version: 4.16.2
* webpack-serve Version: 2.0.2

### Feature Proposal

An option to output the webpack command line progress, ie what you get with `webpack --progress`.

### Feature Use Case

I'm aware of `webpack-serve-waitpage` but in my setup the UI is served on a different port than the app is accessed with, because its proxied through a docker container that has a lot of other stuff. When I start the docker containers and the UI I can't actually see the page until both docker and webpack-serve are ready, but I don't see any webpack progress unless I visit a browser page just to see progress (which isn't a usable page after completion). This is quite inconvenient. I just want to see the regular `webpack --progress` at the command line. Thanks!

**Comment by shellscape** [comment]
Sorry, but that is not supported in webpack-server, and won't be something we'll be adding unless there is a massive call for it. `webpack-dev-middleware` handles the webpack builds for webpack-server and webpack-dev-server, so if that's something you want to see the middleware output to the console, you should open a pull request on that repo for that feature.

**Comment by aaronbeall** [comment]
You're saying `webpack-dev-middleware` doesn't actually provide the progress output?
