### ISSUE TITLE
Support dynamic entry

### ISSUE THREAD

**Issue by crlfe** [webpack-contrib/webpack-serve#255]
* Operating System: Linux
* Node Version: 8.9.1
* NPM Version: 6.1.0
* webpack Version: 4.16.3
* webpack-serve Version: 2.0.2

[Dynamic entry](https://webpack.js.org/configuration/entry-context/#dynamic-entry) is buggy due to a limitation cleaning up the entries for webpack-hot-client. A dynamic entry seems to be used most often to have webpack pick up globbed entry points ([example package](https://www.npmjs.com/package/webpack-watched-glob-entries-plugin); getEntries returns a function).

### Code

```js
// webpack.config.js
const { resolve } = require('path');

exports.default = {
    entry: () => resolve(__dirname, 'src/index.js'),
}
```

```js
// src/index.js
```

### Expected Behavior

Running webpack-serve starts and waits for changes.

### Actual Behavior

Error: An error was thrown while initializing koa-webpack
 TypeError: webpack-hot-client: The value of `entry` must be an Array, Object, or Function. Please check your webpack config.

### How Do We Reproduce?

Any dynamic entry that returns a value not supported by webpack-hot-client will cause this crash, because [lib/config.js#toArray](https://github.com/webpack-contrib/webpack-serve/blob/32563f5e721f28c69f5337181bddd2db323526c7/lib/config.js#L9) does not handle functions. I have a local fix with test if you'd like me to throw up a fork and PR -- it splits toArray and wraps up the dynamic entry function so that its result is transformed appropriately.

As a slightly-related refactor, I'd like to suggest renaming toArray to entryFix (to match timeFix below, and because `toArray` implies no side-effects). No objection to doing it myself (as a second PR), but didn't want to start that swath of renames without running it past you first.

**Comment by shellscape** [comment]
> it splits toArray and wraps up the dynamic entry function so that its result is transformed appropriately.

The proper fix would be prevent the call to `toArray`. It should not be called if the entry is a function or thenable, and should just let hot-client handle it from there. If hot-client isn't handling a function properly, a patch should be made to fix that in webpack-hot-client's repo.

> I'd like to suggest renaming toArray to entryFix

Please don't. The return value of that function should always be an array, so the name is appropriate.

**Comment by crlfe** [comment]
> The proper fix would be prevent the call to toArray. It should not be called if the entry is a function or thenable, and should just let hot-client handle it from there. If hot-client isn't handling a function properly, a patch should be made to fix that in webpack-hot-client's repo.

The hot-client bug is the same one you [already know about](https://github.com/webpack-contrib/webpack-hot-client/issues/11#issuecomment-385227714). Working around it here is a small extension of the logic you already have: hot-client is choking on the return value of the function not being hot-client-friendly.
 
> > I'd like to suggest renaming toArray to entryFix
> 
> Please don't. The return value of that function should always be an array, so the name is appropriate.

That's actually a vote in favor: [confiig.js::toArray](https://github.com/webpack-contrib/webpack-serve/blob/32563f5e721f28c69f5337181bddd2db323526c7/lib/config.js#L9) _never_ returns an array. Instead it fixes the entry field of the object that it is passed.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
