### ISSUE TITLE
Return 200 after initial build for non-browser clients

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack-contrib/webpack-serve#256]
* Operating System: MacOS
* Node Version: Node 8
* NPM Version: 5
* webpack Version: 4
* webpack-serve Version: 2.0.2

### Expected Behavior / Situation

```
# after $ webpack-serve
$ curl -I http://localhost:8080
HTTP/1.1 200
```

### Actual Behavior / Situation

```
# after $ webpack-serve
$ curl -I http://localhost:8080
HTTP/1.1 404 Not Found
```

### Modification Proposal

Not sure if this is by design, because of the web socket approach, but it would be nice, if webpack-serve would return `200` as soon as the initial build has finished, if you try to reach `http://localhost:8080` with a non-browser client. That way you can better use it together with other tools like https://github.com/bahmutov/start-server-and-test.

**Comment by shellscape** [comment]
Well the whole point of this server is to facilitate serving webpack build assets. Hitting the server for a resource that doesn't yet exist should not return a 200. You can always place a static `html` file in the root of the `content` directory that should return 200 as soon as the server starts - that should be the workaround for this situation.

**Comment by donaldpipowitch** [comment]
Alright. Than I guess I'll close this as "works as intended"? Thank you ✌️

However thinking of it I guess I tried curling "index.html" directly 🤔 well, I just try it again

**Comment by shellscape** [comment]
Yeah if you were already trying that, and it didn't work, that could mean there's a deeper problem there and we'd definitely like to fix that. Please do reopen if you find that's a problem.
