### ISSUE TITLE
HistoryApiFallback and Build Location Conflict

### ISSUE THREAD

**Issue by EvHaus** [webpack-contrib/webpack-serve#26]
* Operating System: macOS
* Node Version: v9.6.1
* Yarn Version: v1.3.2
* webpack Version: v4.0.1
* webpack-serve Version: v0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve webpack.config.js
```

##### webpack.config.js

```js
const convert = require('koa-connect');
const history = require('connect-history-api-fallback');

{
	entry: {
		app: '/var/www/html/js/index.js',
	},
	mode: 'development',
	output: {
		path: '/var/www/html/build/',
		publicPath: './build/',
		filename: '[name].js',
	},
	serve: {
		add: (app, middleware, options) => {
			app.use(convert(history()));
		},
		content: '/var/www/html/build/',
		dev: {
			publicPath: '/build/',
		},
		// This is true by default, but I'm adding it here explicitly just for clarity
		hot: true
	},
}
```

### Expected Behavior

When `serve.dev.publicPath` is set, I expect all webpack bundles (including HMR bundles) to be served from that directory so that my application works as expected.

Additionally, I expect HMR bundle reloads to use the `serve.content` path specified when I'm using `history-api-fallback`.

### Actual Behavior

However, at the moment, when `serve.hot` is enabled, it doesn't seem to respect the value set in `dev.publicPath` and all reloaded HMR bundles are served from the root directory `/` rather than from `/build/`. This means that HMR is effectively broken as webpack can't reconcile the bundles.

The `content` path isn't respected either when I'm using the `history-api-fallback` plugin. If I visit a nested route like `http://localhost:8080/nested/` and try to do a hot module reload from there, `webpack-serve` shows this in the network tab:

```
GET http://localhost:8080/nested/build/f8d7504067c7012a4cc1.hot-update.json 404 (Not Found)
```

Which obviously fails, because bundles should be loading from `/build/` not from `/nested/build`.

`webpack-dev-server` used to handle both of these scenarios correctly and I'm not sure how to make it work with `webpack-serve`.

### How Do We Reproduce?

Use the config file above and start a simple app with `webpack-serve` with HMR enabled and a non-default `dev.publicPath` value.

Try updating a file, watch HMR reload and it will fail with this message in the browser dev console:

```
｢hot｣ Checking for updates to the bundle.
｢hot｣ Ignored an update to unaccepted module ./html/js/containers/app.js ➭ ./html/js/containers/root.js ➭ ./html/js/index.js ➭ 1
｢hot｣ The following modules could not be updated:
          ⦻ ./html/js/containers/app.js
```

**Comment by shellscape** [comment]
That's a fun one.

The first thing I can see that sticks out is that `hot` is not true by default. It's an `Object` by default: https://github.com/webpack-contrib/webpack-serve/blob/master/lib/options.js#L17, as outlined here: https://github.com/webpack-contrib/webpack-serve/#hot

Beyond that, I would need you to whip up a repo that can reproduce this, regardless of filesystem setup of the user. From there I can debug locally here and see what we can do.

**Comment by EvHaus** [comment]
I have good news and bad news.

The bad news is that after trying to create a code repo to reproduce the issue, I was unable to reproduce it on a clean project.

The good news is that I now have a repo for a minimal boilerplate that uses `webpack-serve`, `react`, and `react-hot-loader` all working together quite well.

Here's the repo: https://github.com/EvHaus/webpack-serve-26

I'm going to close the issue since I'm not able to reproduce it anymore. I suspect my original issue has something to do with the fact that our project is still on React 15 and we cannot upgrade to the latest version of `react-hot-loader` just yet. Something about that combination isn't working as expected. But it definitely doesn't appear to bea an issue with `webpack-serve` since the repo is serving up HMR modules correctly even with `HistoryAPIFallback` enabled.

Sorry for wasting your time.

**Comment by shellscape** [comment]
No worries at all! Really glad some good came from that discovery, and I'm sure that'll help other users out. If you'd like to tweet about that and point folks to that repo, I'd be happy to get some RTs going.
