### ISSUE TITLE
Watch content example is broken

### ISSUE THREAD

**Issue by marcofugaro** [webpack-contrib/webpack-serve#264]
* Operating System: OSX 
* Node Version: 10.7.0
* NPM Version: 6.2.0
* webpack Version: 4.16.5
* webpack-serve Version: 2.0.2

### Expected Behavior
The [watch content example](https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/watch-content.config.js) should work as described

### Actual Behavior
It doesn't notify on file changed, it's caused by https://github.com/webpack-contrib/webpack-hot-client/issues/92, most likely an issue with `ws`.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
