### ISSUE TITLE
does not use output.path option from webpack.config.js

### ISSUE THREAD

**Issue by francoisromain** [webpack-contrib/webpack-serve#265]
* Operating System: Macos 10.13.6
* Node Version: 10.8.0
* NPM Version: 6.3.0
* webpack Version: 4.16.15
* webpack-serve Version: 2.0.2

### Expected Behavior

Webpack-serve should use the `output.path` option from `webpack.config.js`. It was working fine with webpack-serve v.0.3.1.

### Actual Behavior

With the current version of webpack-serve the compiled files (scripts.js and styles.css) are outputed at the root of the project, and not the path specified in the `output.path` option of webpack.config.js

### Code

```js
  // webpack.config.js
const dev = process.env.NODE_ENV !== 'production'

module.exports = {
  mode: dev ? 'development' : 'production',
  context: __dirname,
  entry: './src/scripts.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'scripts.js'
  }
…
```

### How Do We Reproduce?

install this repo: https://github.com/MTES-MCT/camino-landingpage, update `webpack-serve` to version `2.0.2` in package.json and run `npm install` and `npm run dev`.

The files `scripts.js` and `styles.css` should be at `/dist/…` but are at `/…`

**Comment by francoisromain** [comment]
I found a solution adding an entry to webpack.config. 

```
  serve: {
    devMiddleware: {
      publicPath: '/dist/'
    }
  }
```
Not sure why this is necessecary. I think it should work with `output.path`.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
