### ISSUE TITLE
Don't call process.exit when used as a library

### ISSUE THREAD

**Issue by SevInf** [webpack-contrib/webpack-serve#267]
* Operating System: macOS 10.13.5
* Node Version: v8.11.3
* NPM Version: v5.6.0
* webpack Version: v4.16.5
* webpack-serve Version: v2.0.2

### Expected Behavior

When `webpack-serve` is used as a library, I would expect that in case of an error it will return a rejected promise and let the app handle the error.

### Actual Behavior

webpack-serve [calls](https://github.com/webpack-contrib/webpack-serve/blob/v2.0.2/lib/index.js#L60) `process.exit(1)` and does not give a chance to handle the exception.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
