### ISSUE TITLE
support custom config file path with cli

### ISSUE THREAD

**Issue by nihgwu** [webpack-contrib/webpack-serve#268]
* Operating System: MacOS
* Node Version: 8.11.3
* NPM Version: 6.2.0
* webpack Version: 4.16.5
* webpack-serve Version: 2.0.2

### Feature Proposal

Support custom serve config file path

### Feature Use Case

right now `webpack-serve` use the default search pattern to find the config file via `cosmiconfig`, so I have to put the config file in the root of my project or it won't find it, or I have to put in the `webpack.config.js`'s `serve` section, yes we can require the custom serve config file to assign, but can we make it more nature to achieve that, thanks

the existing problem is that we use `--config` as the webpack config path

**Comment by nihgwu** [comment]
I think share the `dirname` with `webpack.config.js` is a bit confusing as we have to explain another search strategy, I'd prefer a new flag to do it, like `--entry`

I think we can just remove the support of config alias for `webpack` config, that means:
`webpack-serve ./serve.config.js` should respect serve config only, if you want to specific the webpack config, you have to explicitly provide it `webpack-serve --config ./webpack.config.js`, in this way we are actually mapping the cli options strictly.

BTW, I also find that we don't support `open-path` from config file, that would be a problem if I want open a custom url instead of the provided `host:port` in the config, should I create another issue for that?

**Comment by nihgwu** [comment]
BTW, I also find that we don't support `open-path` from config file, that would be a problem if I want open a custom url instead of the provided `host:port` in the config, should I create another issue for that?

Right now I have to use the event hook to open manually.

**Comment by nihgwu** [comment]
@michael-ciniawsky What about my proposal? consume the bare config path from cli as `webpack-serve`'s config, if you want to specific the config for `webpack`, use `--config` explicitly, if you think it's legitimate, I'd love to send a PR to do that

**Comment by michael-ciniawsky** [comment]
What about my proposal?

Added to the notes already :). Hmm... better to hold off with a PR for now, since I can't guarantee you anything atm 😛

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
