### ISSUE TITLE
Error: `entry` Object values must be an Array.

### ISSUE THREAD

**Issue by EvHaus** [webpack-contrib/webpack-serve#27]
* Operating System: macOS
* Node Version: v9.6.1
* Yarn Version: v1.3.2
* webpack Version: v4.0.1
* webpack-serve Version: v0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve webpack.config.js
```

##### webpack.config.js

```js
{
	entry: {
		app: '/var/www/html/js/index.js',
	},
	mode: 'development'
}
```

### Expected Behavior

Given the config above, I would expect to be able to launch a `webpack-serve` server without any issue.

### Actual Behavior

However, the server never starts and I get the following error:

```
TypeError: webpack-hot-client: `entry` Object values must be an Array. Please check your webpack config.
    at validateEntry (/Users/ev.haus/Git/ux/node_modules/webpack-hot-client/lib/util.js:131:19)
    at module.exports (/Users/ev.haus/Git/ux/node_modules/webpack-hot-client/index.js:32:3)
    at fn (/Users/ev.haus/Git/ux/node_modules/koa-webpack/index.js:74:18)
    at middleware.webpack.state.getPort.then (/Users/ev.haus/Git/ux/node_modules/webpack-serve/lib/server.js:32:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:705:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:665:3
```

Note, the error doesn't appear until you kill the process due to https://github.com/webpack-contrib/webpack-serve/issues/25

If you change `entry.app` from `'/var/www/html/js/index.js'` to `['/var/www/html/js/index.js']` then the server starts up just fine.

NOTE: This issue was also briefly discussed here: https://github.com/webpack-contrib/webpack-hot-client/issues/11#issuecomment-369387441

### How Do We Reproduce?

See config and CLI command and above.

**Comment by shellscape** [comment]
Thanks for the issue 🍺  We'll get a fix out for this quickly.

>  I would expect to

Haha just a friendly heads up; I appreciate the verbosity (really) but you don't have to preface this section with _"I expect to|etc..."_
