### ISSUE TITLE
Upgrading to 2.0.2 from 1.0.4 breaks server

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/webpack-serve#272]
* Operating System: Windows 7
* Node Version: 10.9.0
* NPM Version: 6.3.0
* webpack Version: 4.17.0
* webpack-serve Version: 2.0.2

### Expected Behavior

work properly

### Actual Behavior

does not serve content

### Code

```js
serve: {
        http2: true,
        port: STATIC_PORT,
        host: STATIC_HOST,
        https: {
            ca: fs.readFileSync('certs/cacert.crt'),
            key: fs.readFileSync('certs/server.key'),
            cert: fs.readFileSync('certs/server.crt'),
        },
        add: (app, middleware, options) => {
            app.use((ctx, next) => {
                ctx.set('Access-Control-Allow-Origin', '*');
                next();
            });

            middleware.webpack();
            middleware.content();
        },
    }
```
### How Do We Reproduce?

Run ```npm run client``` in my [repo](https://github.com/budarin/react-ssr-bootstrap-project) and try to get ```https://localhost:4440/client.js``` - you'll get the resource ```client.js```

Upgrade webpack-serve to 2.0.2 version and rerun command - you'll get the 404

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
