### ISSUE TITLE
Listening inside of serve() does not work

### ISSUE THREAD

**Issue by eflo11** [webpack-contrib/webpack-serve#274]
- [x] Needed
- [x] Confusing

### Details

Within the example you have mentioned that you can use the event `listening` after you have started `serve`.

```js
serve(argv, { config })
  .then((server) => {
    server.on('listening', ({ server, options }) => {
      console.log('happy fun time');
    });
  });
```

However by the time you get into the `then` of `serve` it has already started listening and will not ever hit the console log.

### Proposal for Changes

A way around this is to attach the listening event on the config object that you pass into serve.

```js
const options = { /* webpack config */ };

options.on = {
  listening: ({ server }) => {
    console.log('happy fun time');
  },
};

serve({}, options);
```

The proposed change would just be to list out what events would actually already be triggered by the time `serve` is finished starting and replace the example to clear up some confusion.

An example of one that you could replace your existing one with would be the `build-finished` event:

```js
serve({}, options).then((server) => {
  server.on('build-finished', () => {
    console.log('Build finished');
  });
});
```

**Comment by michael-ciniawsky** [comment]
> An example of one that you could replace your existing one with would be the build-finished event

I think this already happend in `webpack-server >= v2.0.0`

**Comment by michael-ciniawsky** [comment]
Which version are your currently using ?

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/webpack-serve/releases/tag/v2.0.0

> serve(argv, options) returns a promise that resolves when the server has begun
listening and is fully setup. **negates the need for the listening event**

**Comment by michael-ciniawsky** [comment]
#243
