### ISSUE TITLE
Allow serving `content` from `publicPath`, or disable it

### ISSUE THREAD

**Issue by Airkro** [webpack-contrib/webpack-serve#275]
I am try to Serving `content` from `publicPath`, like <https://github.com/webpack/webpack-dev-server/issues/954>

```js
// use webpack-dev-server , I can do this:
config.devServer = {
  // contentBase: './assets',
  publicPath: '/app/',
  before(app) {
    app.use('/app/', express.static('./assets'));
  }
};
```

Maybe I can do the same thing with `koa-static` and `koa-mount`, but I can't disable `content` in `webpack-serve`, it will fallback into `process.cwd`.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
