### ISSUE TITLE
watch content example break

### ISSUE THREAD

**Issue by Sunshine168** [webpack-contrib/webpack-serve#276]
* Operating System:macOs High Sierra
* Node Version:9.8.0
* NPM Version:5.6
* webpack Version:4.16.5
* webpack-serve Version:2.0.2

### Expected Behavior

work well

### Actual Behavior

```server.on is not a function```

### Code

```js

    serve: {
      hotClient: {
        host: 'localhost',
        port: 8090
      },
      compress: true,
      content: outputPath,
      on: {
        listening(server) {
          console.log(server);
          const socket = new WebSocket('ws://localhost:8090');
          const watchPath = outputPath;
          const options = {};
          const watcher = chokidar.watch(watchPath, options);

          watcher.on('change', () => {
            const data = {
              type: 'broadcast',
              data: {
                type: 'window-reload',
                data: {}
              }
            };

            socket.send(stringify(data));
          });

          server.on('close', () => {
            watcher.close();
          });
        }
      }
    }
```

```js
  // additional code, HEY YO remove this block if you don't need it
```

### How Do We Reproduce?

BTW doc [watch content](https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/watch-content.config.js) is outdating ,

```
  // hot may hotClient
  hot: {  
    host: 'localhost',
    port: 8090,
  },
```

**Comment by Sunshine168** [comment]
i fixed it , Actually the config should be 

```

module.exports.serve = {
  content: [__dirname],
  hotClient: {
    host: 'localhost',
    port: 8090,
  },
  on: {
   -- listening({server}) {
      const socket = new WebSocket('ws://localhost:8090');
      const watchPath = __dirname;
      const options = {};
      const watcher = chokidar.watch(watchPath, options);

      watcher.on('change', () => {
        const data = {
          type: 'broadcast',
          data: {
            type: 'window-reload',
            data: {},
          },
        };

        socket.send(stringify(data));
      });

      server.on('close', () => {
        watcher.close();
      });
    },
  },
};
```

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
