### ISSUE TITLE
Uri is invalid when options.host is equal to 0.0.0.0

### ISSUE THREAD

**Issue by ZSkycat** [webpack-contrib/webpack-serve#277]
* Operating System: Win10
* Node Version: v10.5.0
* NPM Version: v6.1.0
* webpack Version: 4.17.1
* webpack-serve Version: 2.0.2

I want `webpack-serve` not to bind the hostname, allow access by everyone (LAN), all I set `options.host` to `0.0.0.0`.
But clipboard and open use the wrong uri `http://0.0.0.0:65080`

### Expected Behavior / Situation
```
options = {
  host: '0.0.0.0',
  port: 65080,
  ...
}

// output
i ｢serve｣: Serving Static Content from: webroot\
i ｢serve｣: Project is running at http://127.0.0.1:65080
i ｢serve｣: Server URI copied to clipboard

// clipboard or open
http://127.0.0.1:65080
```

### Actual Behavior / Situation
```
options = {
  host: '0.0.0.0',
  port: 65080,
  ...
}

// output
i ｢serve｣: Serving Static Content from: webroot\
i ｢serve｣: Project is running at http://0.0.0.0:65080
i ｢serve｣: Server URI copied to clipboard

// clipboard or open
http://0.0.0.0:65080
```

### Modification Proposal

if `host == 0.0.0.0`, replace 0.0.0.0 in uri with 127.0.0.1
https://github.com/webpack-contrib/webpack-serve/blob/master/lib/server.js#L16

for output info `i ｢serve｣: Project is running at http://127.0.0.1:65080`
It may cause ambiguity, do we need to add a comment message? like this
`i ｢serve｣: Project is running at http://127.0.0.1:65080 (0.0.0.0)`

**Comment by ZSkycat** [comment]
`options.hotClient.host` is invalid when `options.host` is equal to 0.0.0.0.
Need user to set `options.hotClient.host` to work properly

https://github.com/webpack-contrib/webpack-serve/blob/master/lib/options.js#L80-L84

**Comment by nihgwu** [comment]
I'm encountering with the same problem, but instead of replace the host internally, I'd propose to add a new option `listeningHost`

In my case, I'm using a custom url like `local-xxx.yyy.zzz` as the public path, then I lose the benefit of listening to `0.0.0.0`, if I change to `0.0.0.0`, then it will be `Project is running at http://0.0.0.0:65080` and I just can't open it

**Comment by HairyRabbit** [comment]
Maybe also should set hotclient host ?

```js
serve: {
  host: '0.0.0.0',
  port: 8080
  hotClient: {
    host: {
      server: '0.0.0.0',
      client: '127.0.0.1'
    },
    port: 8081
  }
}
```

This code works for me, but also got a warning at server start.

```
`host.client` does not match `host.server`. This can cause unpredictable behavior in the browser.
```

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
