### ISSUE TITLE
Merge provided dev option with default

### ISSUE THREAD

**Issue by billyjanitsch** [webpack-contrib/webpack-serve#28]
* Operating System: macOS 10.13.3
* Node Version: 8.9.4
* NPM Version: 5.7.1
* webpack Version: 4.0.1
* webpack-serve Version: 0.1.5

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

##### webpack.config.js

```js
{
  serve: {
    dev: {logLevel: 'warn'},
  },
}
```

### Expected Behavior

Currently, the `dev` option [defaults](https://github.com/webpack-contrib/webpack-serve#dev) to `{publicPath: '/'}`. I was expecting that if I provided my own `dev` config object, it would be merged with the default one. In other words, if I _only_ provide `logLevel`, I expected `publicPath` to still be `/`.

Would you consider making this behavioral change? I would be happy to PR it.

### Actual Behavior

The provided object is not merged with the default one, so changing the log level of the dev server removes the default publicPath config.

### New Feature Use Case

Shown above -- tweaking an unrelated setting without affecting the defaults.

(P.S. thanks for this library! ❤️)

**Comment by shellscape** [comment]
Thanks for the PR 🍺  You'll see a fix commit pop up in this thread any second now. Feel free to put together PRs in the future, we love those! (I just happened to be cranking away on this when you made that issue)
