### ISSUE TITLE
Accessing websocket server port on "listening" event

### ISSUE THREAD

**Issue by benwiley4000** [webpack-contrib/webpack-serve#282]
* Operating System: Ubuntu 17.04
* Node Version: 8.9.0
* NPM Version: 6.4.1
* webpack Version: 4.17.1
* webpack-serve Version: 2.0.2

### Feature Proposal

In the [watch content example](https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/watch-content.config.js) the hot client port number gets hardcoded. It would be nice to take advantage of dynamic port assignment while still being able to watch content.

So when I add my `listening` event handler to my webpack config I want to be able to look up the port of the hot client websocket server.

I dove through some code and it looks like webpack-hot-client never sends the websocket port number back to webpack-serve - I guess that would be necessary for this to work.

### Feature Use Case

I want to watch files (html) that are used at development time but aren't included in the webpack build.

I also want to be able to run several development servers for several projects at once without having to go through and change port numbers to avoid overlaps. By taking a advantage of dynamic port allocation I don't have to worry about this.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
