### ISSUE TITLE
Chore: Update dependency on webpack-log

### ISSUE THREAD

**Issue by gbenson-wikia** [webpack-contrib/webpack-serve#283]
* Operating System: N/A
* Node Version: N/A
* NPM Version: N/A
* webpack Version: N/A
* webpack-serve Version: 2.0.2

### Expected Behavior / Situation
`webpack-log` is up-to-date (currently 2.0.0)

### Actual Behavior / Situation
`webpack-log` is `^1.1.2` in `package.json`

### Modification Proposal
Update `package.json` to set `webpack-log` to `^2.0.0` and test.

### Additional
Using the older version of `webpack-log` is shortly going to cause problems when Chrome 69 is released (probably in September 2018) because of https://github.com/shellscape/loglevelnext/issues/7 , which the 1.x version of `webpack-log` presently uses.

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
