### ISSUE TITLE
cli -r options not works multi times

### ISSUE THREAD

**Issue by HairyRabbit** [webpack-contrib/webpack-serve#284]
* Operating System: win10
* Node Version: v10.3.0
* NPM Version: 6.1.0
* webpack Version: 4.17.2
* webpack-serve Version: 2.0.2

### Actual Behavior

```
Error: Flags were specified with invalid values:

  --require  must be set to a string

Please check the command executed.
```

### Code

```sh
npx webpack-serve -r @babel/register -r esm
```

I look at the schema file, found the 'require' options type was `string`.

If I pass multi `-r`, the value will be `['@babel/register', 'esm']`, and the type should be `array`.

**Comment by bolasblack** [comment]
Hope this PR can be merged

In my case I need require both `ts-node/register` and `esm`

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
