### ISSUE TITLE
watch content example break 2

### ISSUE THREAD

**Issue by felixcatto** [webpack-contrib/webpack-serve#286]
Operating System: Ubuntu 16.04
Node Version: 8.11
NPM Version: 6.4.1
webpack Version: 4.17.2
webpack-serve Version: 2.0.2

**Expected Behavior**
page should reload after every file change

**Actual Behavior**
page reload after every odd file change. 

When i add line
`const socket = new WebSocket('ws://localhost:8090');`
the webpack serve begins to behave strangely. After first file change i see both lines and all works well
_｢wdm｣: Compiled successfully.
｢hot｣: WebSocket Client Connected_

But after second file change i see only one line, and page does not reload :(
_｢wdm｣: Compiled successfully._

That continues infinitely.

**Code**
```
{
      ...webpackConfig,
      serve: {
        content: path.resolve(__dirname, 'dist'),
        port: 3000,
        hotClient: {
          host: 'localhost',
          port: 8090,
        },
        on: {
          listening(server) {
            const socket = new WebSocket('ws://localhost:8090');

            reloadDevServer = (done) => {
              socket.send(JSON.stringify({
                type: 'broadcast',
                data: {
                  type: 'window-reload',
                  data: {},
                },
              }));
              done();
            };
          },
        },
      },
    }
```

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
