### ISSUE TITLE
Update debug package to version 4.0.0

### ISSUE THREAD

**Issue by ryanelian** [webpack-contrib/webpack-serve#287]
* Operating System: Windows & Linux
* Node Version: 8, 10
* NPM Version: 6.2.0
* webpack Version: 4.18.0
* webpack-serve Version: 2.0.2

### Expected Behavior

No warnings in my CI.

### Actual Behavior

I am getting warnings in my CI due to updated debug package:

- https://github.com/visionmedia/debug/issues/603#issuecomment-420237335

- https://github.com/visionmedia/debug/releases/tag/4.0.0

```
warning webpack-serve > debug@3.2.4: `debug` versions 3.2.0-3.2.2 break Node 4. Users of node LTS and onward (modern Node versions): please upgrade to `debug@4` or above as soon as possible. Node 4 users: please pin to `debug@>=3.2.3 <4` as it will be the last version range that supports Node@4.
```

### Code

```
npm install debug
```

### How Do We Reproduce?

```
npm install
```

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
