### ISSUE TITLE
HMR doesn't always work on multiple clients

### ISSUE THREAD

**Issue by natew** [webpack-contrib/webpack-serve#288]
* Operating System: Mojave
* Node Version: 9.10
* webpack Version: 4.17.2
* webpack-serve Version: 2.0.2

### Expected Behavior

Should work

### Actual Behavior

For some reason occasionally I don't see the [hmr] stack that I should on one of the clients. It isn't always unfortunately, but it is pretty common.

### How Do We Reproduce?

On one client I'll see success:

![image](https://user-images.githubusercontent.com/12100/45379214-46b7ee00-b5b4-11e8-9b18-892b4aaf2626.png)

But on the failing client I see:

```
｢hot｣ App updated. Recompiling src/apps/peek/panes/bitPanes/PeekBitDocument.tsx
log.js:59 ｢hot｣ webpack: Compiling (<unnamed compiler>)
```

Followed by the warnings, but then no "App updated".

**Comment by alexander-akait** [comment]
Already reported, author abandoned package, please use `webpack-dev-server`

**Comment by natew** [comment]
Wait, I literally just read somewhere else the author saying `webpack-dev-server` is a hot dumpster fire and everyone is using this now.... I was running into a variety of issues with it and this fixed a few of them....


😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓 😓

**Comment by alexander-akait** [comment]
@natew feel free to create issue in `webpack-dev-server`, sorry, can't do something here
