### ISSUE TITLE
Make webpack-cli a devDependency rather than a dependency?

### ISSUE THREAD

**Issue by billyjanitsch** [webpack-contrib/webpack-serve#29]
* Operating System: macOS 10.13.3
* Node Version: 8.9.4
* NPM Version: 5.7.1
* webpack Version: 4.0.1
* webpack-serve Version: 0.1.5

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Actual Behavior

Installing webpack-serve also installs webpack-cli. There don't appear to be [any references to webpack-cli](https://github.com/webpack-contrib/webpack-serve/search?utf8=%E2%9C%93&q=webpack-cli&type=) in webpack-serve, so I'm wondering if it needs to be included as a dependency. Maybe there's a reason for this that I'm missing?

### How Do We Reproduce?

`npm i webpack-serve`

### New Feature Use Case

webpack-cli is huge and some of its dependencies have postinstall scripts that take a ton of time, so if there's not a particular reason for webpack-serve to depend on it, it would be great to remove it from the dependencies. (Happy to PR this if you'd like.)

**Comment by shellscape** [comment]
Good call, and thanks for the PR 🍺 

At a point we were using one of it's convenience methods, but that was a while back. Looks like it stuck around as an old artifact. I'll get that cleaned up in a commit soon here.

**Comment by billyjanitsch** [comment]
Cheers. Looks like there's also an unnecessary dependency on [webpack-hot-client](https://github.com/webpack-contrib/webpack-serve/blob/master/package.json#L49). koa-webpack needs it, but already depends on it directly.
