### ISSUE TITLE
Nothing happens when trying to exit a build with Ctrl+C

### ISSUE THREAD

**Issue by spoldman** [webpack-contrib/webpack-serve#290]
* Operating System: Windows 10
* Node Version: 8.11.4
* NPM Version: 6.4.0
* webpack Version: 4.18
* webpack-serve Version: 2.0.2

### Expected Behavior

Pressing Ctrl+C should exit the build proccess

### Actual Behavior

Nothing happens. I have tried running webpack-serve from the API and with https://github.com/deepsweet/start/tree/master/packages/plugin-lib-webpack-serve using the same config and I get a similar results where the build keeps going.

**Comment by spoldman** [comment]
I have tried to disable, plugins and loaders and the results are the same. I cannot exit a build while it is building

**Comment by spoldman** [comment]
I have found out that it works as expected when using Bash shell but not in CMD or Powershell

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
