### ISSUE TITLE
Suggestion: error when port is unavailable

### ISSUE THREAD

**Issue by OliverJAsh** [webpack-contrib/webpack-serve#291]
I would like to suggest that we make webpack-serve fail loudly and quickly when the requested port is not available.

IIUC, currently the port setting is used only as a preference. If the port is in use, then a random port will be used instead. This is achieved via [`get-port`].

I've just spent several hours debugging an issue that turned out to be because I had a orphan instance of `webpack-serve` running, which meant that when I tried to run `webpack-serve` again, it silently failed and just ignored the port setting in favour of some other random port. I didn't realise this and thus was confused when `webpack-serve` seemed to be returning old content.

At the very least I think we should document this quirky behaviour of the port setting.

[`get-port`]: https://github.com/sindresorhus/get-port

**Comment by alexander-akait** [comment]
DEPRECATED. Please use `webpack-dev-server` (he is in support and update mode again). Feel free to create a issue if some features are not implemented in `webpack-dev-server`. 

Why deprecated `webpack-serve` ?
- The author stopped developing the package.
- Two development servers are misleading for developers.
- Hard to maintain two packages with same purpose.
- Some `dependencies` are not available to fixes/implement new features/etc (https://www.npmjs.com/package/webpack-hot-client and https://github.com/shellscape/koa-static) and there's nothing we can do here.
- `webpack-dev-server` is stable.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
