### ISSUE TITLE
[Workaround] for CLI Failure to Start on Windows

### ISSUE THREAD

**Issue by Slapbox** [webpack-contrib/webpack-serve#30]
## Issue:
Running `./node_modules/.bin/webpack-serve` fails on Windows 7 with:

```
C:\projects\myApp\node_modules\.bin\webpack-serve:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
```

## Solution:
Instead run `./node_modules/webpack-serve/cli.js`

**Comment by shellscape** [comment]
fill out the issue template as asked and we'll reopen this. closing as invalid.
