### ISSUE TITLE
Don't overwrite my clipboard contents

### ISSUE THREAD

**Issue by zenflow** [webpack-contrib/webpack-serve#34]
This issue is for a:

- [ ] **bug**
- [X] **feature** request
- [ ] **modification** request

```
ℹ ｢serve｣: Project is running at http://localhost:8080
ℹ ｢serve｣: Server URI copied to clipboard
```

Please don't overwrite my clipboard contents. It's intrusive. 

I suggest making it an opt-in feature.

**Comment by ooflorent** [comment]
See #33
