### ISSUE TITLE
Clipboard is broken on WSL

### ISSUE THREAD

**Issue by AndreasGalster** [webpack-contrib/webpack-serve#35]
* Operating System: Windows 10, WSL
* Node Version: 8.4.0
* Yarn Version: 1.3.2
* webpack Version: 4.0.1
* webpack-serve Version: 0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
   webpack-serve ./webpack.config.js --log-level debug
```

### Expected Behavior
Runs the project

### Actual Behavior
Error is thrown:
```
Error: xsel: Can't open display: (null)
```

**Comment by shellscape** [comment]
(the ongoing conversation about the clipboard aside)

This is common on systems without a display driver installed. Run `sudo apt install xsel`. You might have to run this as part of your setup as well:

```console
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start; sleep 3;
```
Let me know if this works for your setup.

We use CircleCI for our CI setup, which has docker containers with this already installed (as they provide a chrome browser install) and don't need to jump through any hoops.

**Comment by shellscape** [comment]
@AndreasGalster with #40 being merged, you'll have the option of disabling that feature. But hopefully the solution I pasted before solves the issue for you immediately.
