### ISSUE TITLE
Issue with __webpack_require__ with style-loader/css-loader

### ISSUE THREAD

**Issue by JMSantos94** [webpack-contrib/webpack-serve#38]
* Operating System: Arch
* Node Version: 8.9.4
* Yarn ~~NPM~~ Version: 1.3.2
* webpack Version: 4.0.1
* webpack-serve Version: 0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve --config webpack.config.js
```

##### webpack.config.js

```js
const webpack = require('webpack');
const path = require('path');
const history = require('connect-history-api-fallback');
const convert = require('koa-connect');

module.exports = {
    mode: 'development',
    resolve: {
        extensions: ['.js', '.jsx', '.json']
    },
    entry: [
        'webpack-hot-middleware/client',
        path.resolve(__dirname, 'src/index.js')
    ],
    serve: {
        content: ['./src'],
        open: true,
        port: 3000,
        hot: {
            hot: true
        },
        add: (app, middleware, options) => {
            app.use(convert(history()));
        }
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ],
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        cacheDirectory: true,
                        presets: [
                            'react',
                            'stage-1',
                            'env'
                        ],
                        plugins: [
                            'react-hot-loader/babel'
                        ]
                    }
                }
            },
            {
                test: /\.css$/,
                loader: ['style-loader', 'css-loader']
            }
        ]
    }
};

```
**Note**: Every dependency is at their latest version as of 03/02/2018.

### Expected Behavior
App doesn't crash, and imports the desired 'css' styles.

### Actual Behavior
App crashes, and throws the following error:

```console
styles.css:21 Uncaught SyntaxError: missing ) after argument list
    at Object../src/styles/main.css (bundle.js:18412)
    at __webpack_require__ (bundle.js:1399)
    at fn (bundle.js:781)
    at Object.eval (App.js:23)
    at eval (App.js:67)
    at Object../src/App.js (bundle.js:16446)
    at __webpack_require__ (bundle.js:1399)
    at fn (bundle.js:781)
    at eval (index.js:9)
    at Object../src/index.js (bundle.js:18293)
```

Digging deeper it seems to be related with HMR when using __webpack_require__.

I went ahead and tested this webpack configuration using `webpack-dev-server` and everything seems to be ok. This is the configuration I used for it:

```js
    devServer: {
        contentBase: './src',
        historyApiFallback: true,
        hot: true,
        open: true,
        port: 3000
    }
```

I also tried this with a larger codebase, and found that this piece of code that I use for Redux and HMR was also throwing me errors:
```js
    if (module.hot) {
        module.hot.accept('../reducers/index', () =>
            store.replaceReducer(require('../reducers/index').default)
        );
    }
```
Again, it seems related to requiring things.

### How Do We Reproduce?
Feel free to use this gist as a starting point:
https://gist.github.com/JMSantos94/c61833bcc716e338e2729bcc7fccbd59

Do let me know if you need more information!
Hope it is just not me missing a variable or something in the configuration :laughing:

**Comment by shellscape** [comment]
Thanks for the issue 🍺  The first thing that stands out to me is that you don't have to (and shouldn't with webpack-serve) define the `new webpack.HotModuleReplacementPlugin()`.

Other than that, this looks more like an issue with webpack itself and not webpack serve. You can note that webpack-serve doesn't even appear in the stack trace. Was there something about the error that made you think it was this module's cause versus webpack proper?

**Comment by JMSantos94** [comment]
Thanks to you for the hard work! :beers: 
You were right, it was simply a silly mistake on my end, `new webpack.HotModuleReplacementPlugin()` was the one giving me the error. I assumed the error related to `webpack-serve`, because this particular configuration was not giving me issues with `webpack-dev-server`. 

I will go ahead and close this issue! :smile:
