### ISSUE TITLE
Ignored an update to unaccepted module

### ISSUE THREAD

**Issue by joshunger** [webpack-contrib/webpack-serve#42]
* Operating System: Darwin 17.4.0
* Node Version: 9.5.0
* NPM Version 5.6.0
* webpack Version 4.0.1
* webpack-server Version 0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve ./webpack.config.js
```

##### webpack.config.js

```js
const HtmlWebPackPlugin = require("html-webpack-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
            options: { minimize: true }
          }
        ]
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
    })
  ]
};
```

### Expected Behavior
Making a change should reload.

### Actual Behavior
Fails to reload

![image](https://user-images.githubusercontent.com/2301847/36944868-280c97d4-1f83-11e8-8012-2473b4095137.png)

### How Do We Reproduce?

Is this already a known issue or do you need more information from me?  If so what?  Thanks.

**Comment by shellscape** [comment]
Thanks for the issue 🍺  `webpack-serve` doesn't handle this aspect, rather that functionality is in `webpack-hot-client`. Please see this issue, which tracks the same problem: https://github.com/webpack-contrib/webpack-hot-client/issues/26
