### ISSUE TITLE
Entry and entry point shows as Entrypoint undefined

### ISSUE THREAD

**Issue by joshunger** [webpack-contrib/webpack-serve#43]
* Operating System: Darwin 17.4.0
* Node Version: 9.5.0
* NPM Version 5.6.0
* webpack Version 4.0.1
* webpack-server Version 0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

![image](https://user-images.githubusercontent.com/2301847/36944692-449ef6b0-1f80-11e8-8af2-f7fdc3e6db4c.png)

**Comment by shellscape** [comment]
😞 your issue is invalid because you removed parts of the issue template. This is not an issue with `webpack-serve`. That output is controlled by `webpack` itself. An NPM architecture / structure tut might help out in situations like this to better understand the sources of errors.

**Comment by joshunger** [comment]
@shellscape thanks can you point me to one?

**Comment by shellscape** [comment]
Surely, happy to.

Note that the titles of these two are a little off-putting to folks who might already have this knowledge, or some of it, but they still contain solid info to review:
https://www.sitepoint.com/beginners-guide-node-package-manager/
http://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/

And here are a few that delve into the structure of node_modules and explains that madness:
https://snyk.io/blog/whats-an-npm-dependency/
https://medium.com/learnwithrahul/understanding-npm-dependency-resolution-84a24180901b
https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/

Ping me on twitter if I can help out more on that front.
