### ISSUE TITLE
Should --mode be in webpack-serve?

### ISSUE THREAD

**Issue by joshunger** [webpack-contrib/webpack-serve#44]
I was disappointed to see that `--mode` doesn't work.

For example -

`webpack-serve ./webpack.config.js --mode development`

This forces me to add additional logic to my `webpack.config.js` file.

Should `--mode` be in webpack-serve given that webpack-serve should be "lean".

**Comment by shellscape** [comment]
😞 your issue is invalid because you removed the issue template.

I'll comment on the question, however. `webpack-dev-server` allows pass-through CLI options from WDS through `webpack-cli`s shared modules. This makes the module overly and needlessly complex. `webpack-serve` does not follow that pattern and does not think it's proper. `mode` can easily be set in a config and should be for use with `webpack-serve`.

**Comment by joshunger** [comment]
Sweet two for two :)

**Comment by just-boris** [comment]
+1 to the initial request.

In my use-case, I have a single `webpack.config.js` file that is used for both build and dev-server. Currently, it is required to do some tricks like `webpack-dev.config.js` to override this property. Not zero-config anymore.

**Comment by shellscape** [comment]
@just-boris use environment variables. if cross-platform is an issue, use `cross-env`. `webpack-serve` is not `webpack`, nor is it `webpack-cli`. It's a development _server_ and there are a host of reasonable alternatives to a command line flag.

**Comment by shellscape** [comment]
Also of note, this was added a while back https://github.com/webpack-contrib/webpack-serve/blob/a4368071f9aaa1605e6d5e3690933ebba8db6a5b/index.js#L16 so you can use that to detect you're in the webpack-serve environment.

**Comment by benwiley4000** [comment]
@shellscape I understand your motivation and the desire to keep this module simple. That said, it's unfortunate that omitting these CLI options usurps the no-config-file-required-ness of webpack 4. It's easy to avoid using a config file while getting started with webpack 4, and likewise it would be nice if a new user of webpack could start using webpack-serve without immediately needing to write a config file.

Is it unduly complicated to simply pass unknown arguments to the webpack config and hope for the best? A limitation could be that only simple string arguments are "supported", to avoid requiring config validation. This would cover the basic cases of single entry, single output, and mode, which users would typically need to get started.

**Comment by just-boris** [comment]
Thanks, @shellscape!

I would go for the environment variable solution. In my `pacakge.json`

```
"scripts": {
   "build": "MODE=production webpack",
   "start": "MODE=development webpack-serve"
}
```

**Comment by joshunger** [comment]
@just-boris I like what you're thinking.  Maybe `WEBPACK_MODE` ?

**Comment by benwiley4000** [comment]
I like the automatic inclusion of an environment variable. I stuck this in my config:

```js
    mode: process.env.WEBPACK_SERVE ? 'development' : 'production',
```

I would contend creating this config file is an unfriendly onboarding experience for someone getting started with webpack (feels very permanent when you have no clue what you're doing), but it's friendly enough for me! 😄

**Comment by shellscape** [comment]
@benwiley4000 though I don't agree with the concern about the zero-config folks, I would say that there's an opportunity there for someone to submit a PR to webpack proper for reading environment variables to determine options like that. `lib/WebpackOptionsDefaulter` would be the place to look.

**Comment by dylanized** [comment]
Fwiw, running `NODE_ENV=production webpack-serve` appears to set the mode.

**Comment by tkrotoff** [comment]
@dylanized from [webpack documentation](https://webpack.js.org/concepts/mode/):
> Please remember that setting _NODE_ENV_ doesn't automatically set _mode_.

**Comment by elisherer** [comment]
put the production env var set only in the build script.
and in the config do like:
```js
mode = process.env.NODE_ENV || 'development'
```
this worked for me for a very long time.

**Comment by eirikb** [comment]
What if we don't have a config file?

**Comment by cilliemalan** [comment]
@eirikb That's what this is for: #231

**Comment by eirikb** [comment]
@cilliemalan Thanks. I didn't see the PR. I think it was very related to this issue, and now it has a link, which is nice 😄
