### ISSUE TITLE
hot is not turning off correctly 

### ISSUE THREAD

**Issue by dlebedynskyi** [webpack-contrib/webpack-serve#45]
* Operating System:  os 10.13
* Node Version: 8.9.4
* NPM Version: 5.6.0
* webpack Version: 4.0.0
* webpack-serve Version:  0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

```js
const config = getConfigFor('web', 'CLIENT', runConfig);
    logger.start('Creating assets server');

    const server = serve({
      config,
      port: +devAssetPort,
      hot: {hot: false}, 
      //  or hot: false,
     // or hot: null,
     //  or flags: {hot: null}
    });

```

##### CLI Command

```console
  Creating assets server
(node:71070) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
# put console for this 
options.hot { hot: false, host: 'localhost' }
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢hot｣: WebSocket Server Listening at localhost:8081
ℹ ｢serve｣: Project is running at http://localhost:3000
ℹ ｢serve｣: Server URI copied to clipboard
ℹ ｢hot｣: webpack: Compiling Done
✖ ｢wdm｣: Hash: 9fa181a973d2e1989f93
....

ERROR in multi webpack-hot-client/client?5949fd7e-97bb-491e-ba99-7e982ad4af4c ...
Module not found: Error: Can't resolve 'webpack-hot-client/client?5949fd7e-97bb-491e-ba99-7e982ad4af4c' in '/Users/dlebedynskyi/{SOURCE}'
 @ multi webpack-hot-client/client?5949fd7e-97bb-491e-ba99-7e982ad4af4c 
```

##### webpack.config.js

```js
  // whatever config here. webpack 4
```
### Expected Behavior

a. hot can be turned off. 
b. can use webpack-serve from another package that is symlinked
c. run websocket and server on [same ports and not different ports](https://github.com/webpack-contrib/webpack-hot-client#server)

### Actual Behavior

hot is "bitchin'"

### How Do We Reproduce?

a. try turn hot off from js code. 
b. use webpack-serve in package A -aka cli.  link package A to package B. run command from package B - see hot "bitchin'" for unresolve.

**Comment by shellscape** [comment]
Thanks for the issue 🍺 I'm not sure I understand most of what's in this issue, but it looks like you're expecting something to happen when you use the `hot: { hot: false }` option. That option is sent to [`webpack-hot-client`](https://github.com/webpack-contrib/webpack-hot-client) and not this module. 

It seems you've got multiple issues in one issue here:

> b. can use webpack-serve from another package that is symlinked

I can't guarantee this will work as expected as it sounds like you're using the module in a way that wasn't intended.

> c. run websocket and server on same ports and not different ports

This is not preferable. If you have a specific use-case for why you need this, please open a new feature request as a new issue explaining your use-case.

**Comment by shellscape** [comment]
If you still feel this is an error with webpack-serve, please provide a repo that we can clone to reproduce the problem, and we'll reopen the issue.

**Comment by dlebedynskyi** [comment]
I'll make a repo for first part. 
2nd part of issue looks like more koa-webpack issue - can reproduce regardless of webpack-server
