### ISSUE TITLE
Webpack is not building when starting webpack-serve

### ISSUE THREAD

**Issue by jonaskello** [webpack-contrib/webpack-serve#46]
* Operating System: MacOS
* Node Version: v9.6.1
* NPM Version: 5.6.0
* webpack Version: 4.1.0
* webpack-serve Version: 0.1.5

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve webpack.config.js
```

##### webpack.config.js

```js
  module.exports = {
  mode: "development",
  entry: {
    app: "./src/index"
  }
};
```

### Expected Behavior

Webpack should build.

### Actual Behavior

Webpack is not building, I just get this output but nothing more and the built script is not reachable:

```
$ webpack-serve webpack.config.js
ℹ ｢serve｣: Project is running at http://localhost:8080
ℹ ｢serve｣: Server URI copied to clipboard
```

### How Do We Reproduce?

Here is a repo to reproduce:

https://github.com/jonaskello/webpack-serve-repro

I don't know if it's a config error or a bug. I tried to use the simplest possible config.

**Comment by jonaskello** [comment]
If I try in zero config mode (without any webpack.config.js) it seems webpack is building when starting webpack-serve. But when I try it with a config file webpack is not building like described above.

**Comment by jonaskello** [comment]
Maybe related to #27 becuase if I change the entry to an array it will build.

**Comment by shongololo** [comment]
I am running into the same issue. I didn't notice it until I deleted my `.dist` folder.

My current work around is to build via `yarn run build`/`webpack --mode production` which creates the directory and the content, then `yarn run dev`/`webpack-serve --config './webpack.config.js'` works...

**Comment by shellscape** [comment]
@jonaskello Thanks for the issue, and yes I think you're correct that it's the same issue as #27. I have a nasty case of the stomach flu and won't be able to get to releasing until that passes, but 0.2.0 should fix that problem.

**Comment by shellscape** [comment]
@jonaskello 0.2.0 is released https://github.com/webpack-contrib/webpack-serve/releases/tag/v0.2.0 and should resolve the issue.

**Comment by shellscape** [comment]
Gonna close this for now. I tried the reproduce repo and it looked to work OK for me with 0.2.0. Please let me know if we need to reopen and we will.

**Comment by jonaskello** [comment]
@shellscape I can confirm it works for me too with 0.2.0. Thank you for the quick resolution and I hope you are feeling better!
