### ISSUE TITLE
webpack-serve-progress

### ISSUE THREAD

**Issue by shellscape** [webpack-contrib/webpack-serve#5]
The `progress` functionality of webpack-dev-server has been removed as a built-in feature of `webpack-serve` in moving towards the add-on philosophy. As such, a module is needed to provide the necessary supporting files, and an example of wiring up the add-on, to provide the same functionality in a separated concern.

**Comment by elisherer** [comment]
I've created a nice alternative solution using a plugin coupled with a middleware.
Check it out: [webpack-serve-waitpage](https://www.npmjs.com/package/webpack-serve-waitpage)

![](https://raw.githubusercontent.com/elisherer/webpack-serve-waitpage/HEAD/screenshot.png)

**Comment by shellscape** [comment]
@elisherer awesome. this is the first bundled addon for `webpack-serve`. I'll check it out!

**Comment by elisherer** [comment]
just release v0.2.0 with themes!

**Comment by shellscape** [comment]
@elisherer nice work. please feel free to submit a PR adding your project to the list of Add-Ons in the README

**Comment by elisherer** [comment]
@shellscape , Done #113
