### ISSUE TITLE
Adding typescript webpack config support

### ISSUE THREAD

**Issue by hitochan777** [webpack-contrib/webpack-serve#51]
* Operating System: Ubuntu 16.04
* Node Version: v9.3.0
* NPM Version: 5.7.1
* webpack Version: 4.0.1
* webpack-serve Version: 0.2.0

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

webpack-dev-server supports typescript in config file through `TS_NODE_PROJECT`.
```console
  $ TS_NODE_PROJECT=\"tsconfig-for-webpack-config.json\" webpack-dev-server --config config/webpack.config.dev.ts
```
On the other hand,  webpack-serve does not support it. 
```console
  $ TS_NODE_PROJECT=\"tsconfig-for-webpack-config.json\" webpack-serve --config config/webpack.config.dev.ts
```

### Expected Behavior
Enable typescript as webpack config language if `TS_NODE_PROJECT` is specified.
### Actual Behavior
It does not recognize typescript even when `TS_NODE_PROJECT` is specified.

### New Feature Use Case

- Add support for typescript when `TS_NODE_PROJECT` is passed to `webpack-serve`

**Comment by shellscape** [comment]
Thanks for the issue 🍺  `webpack-serve` is a JavaScript project and not a TypeScript project. It also does not cater specifically to any pseudo-languages or transpilers. Additionally, `TS_NODE_PROJECT` [appears nowhere](https://github.com/webpack/webpack-dev-server/search?utf8=%E2%9C%93&q=TS_NODE_PROJECT&type=) in the `webpack-dev-server` repository, nor do any TypeScript definitions. 

You may be looking for this https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webpack-dev-server, in which case you'll have to add the proper bindings/definitions to that project.

**Comment by hitochan777** [comment]
@shellscape thanks for the info. I will look for how `TS_NODE_PROJECT` works.
