### ISSUE TITLE
Comment "router must be the last middleware added" is misleading

### ISSUE THREAD

**Issue by vilic** [webpack-contrib/webpack-serve#58]
* Operating System:
* Node Version:
* NPM Version:
* webpack Version:
* webpack-serve Version:

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

I was trying to configure history fallback along with api proxy, and this comment really got me. The solution turns against it (though I guess it did actually mean "in this case") and adds router with history fallback before `webpack` and `content`, and proxy after them.

**Comment by shellscape** [comment]
😞 bummer. you removed some parts of the issue template, so we had to close it as invalid.
