### ISSUE TITLE
publicPath ignored

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [webpack-contrib/webpack-serve#59]
Hello,

I seem to be having issues serving content when using a publicPath. the devServer serves content from the build directory supplied to**content** in my config, but completely ignores publicPath and so I am unable to server my content correctly.

my config is:
```js
const config = {
        compiler,
        content: [config.get('pathToStaticBuildDir')],
        dev: {
             publicPath: '/client/',
        }
    }

serve(config).then((server) => {})
```

My build folder contains a folder called client that holds my index.html. 
```
build/
|--client/
|-----index.html
```
I am expecting to be able to reach this by setting the publicPath. Am I doing something wrong?

Thanks in advance.

**Comment by theboyWhoCriedWoolf** [comment]
Solved myself. thanks

**Comment by shellscape** [comment]
Please don't ignore the issue template next time or your issue will be closed.
