### ISSUE TITLE
watchContentBase Equivalent

### ISSUE THREAD

**Issue by shellscape** [webpack-contrib/webpack-serve#6]
The `watchContentBase` functionality of webpack-dev-server has been removed as a built-in feature of `webpack-serve` in moving towards the add-on philosophy. We need to create an example of wiring up `chokidar` and utilizing sockets provided by [webpack-contrib/webpack-hot-client](/webpack-contrib/webpack-hot-client), as we need a way to tell the page to reload.

**Comment by nakoo** [comment]
I am waiting on this!

**Comment by shellscape** [comment]
@nakoo I'll look into creating an add-on recipe for that feature this week. stay tuned!
