### ISSUE TITLE
Add support for Unix sockets

### ISSUE THREAD

**Issue by ryansully** [webpack-contrib/webpack-serve#66]
WDS supported Unix sockets via [devServer.socket](https://webpack.js.org/configuration/dev-server/#devserver-socket). Will there be support in `webpack-serve` for Unix sockets as well?

**Comment by shellscape** [comment]
Closing issue as invalid as the issue template was removed.

**Comment by ryansully** [comment]
Wow ok, I suppose I'll open a new issue...

**Comment by shellscape** [comment]
Or you could have edited this one...

**Comment by ryansully** [comment]
Right, well closing the issue usually signals to me (I'm sure others as well) that there would be no further discussion on the topic. In any case, we can continue in the other issue now.

**Comment by shellscape** [comment]
That would be an incorrect assumption.
