### ISSUE TITLE
capability to define a proxy?

### ISSUE THREAD

**Issue by slimee** [webpack-contrib/webpack-serve#68]
* Operating System:all
* Node Version:all
* NPM Version:all
* webpack Version:all
* webpack-serve Version:all

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

### Expected Behavior
define a proxy
### New Feature Use Case
Please add the capability to define a proxy, like that the /api calls may be proxied to the api service.
proxy: {
            '/api': {target: 'http://my-api-host:8082'}
        }

**Comment by shellscape** [comment]
Please read the README https://github.com/webpack-contrib/webpack-serve#add-function-parameters
