### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lifuzhao100** [webpack-contrib/webpack-serve#69]
* Operating System: win10
* Node Version: 8.10.0
* NPM Version:5.7.1
* webpack Version:4.1.1
* webpack-serve Version:0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve  --config ./webpack.config.js --content=./dist
```

##### webpack.config.js

```js
  const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
module.exports = {

	entry: './src/index.js',
	output: {
		filename: '[name].js',
		path: require('path').resolve(process.cwd(), 'dist')
	
	},
	plugins:[
		new HtmlWebpackPlugin(),
		new webpack.HotModuleReplacementPlugin()
	]
}
```
### Expected Behavior
compile successful, then my browser reload with new content
### Actual Behavior
the termical show me that webpack has compiled successful, but  browser doesnot reload with new content,but with an err in the console pane ,tell me that  Uncaught RangeError: Maximum call stack size exceeded
### How Do We Reproduce?
it's easy to reproduce with 0.2.0,or configure it like mine

**Comment by shellscape** [comment]
@lifuzhao100 an error report is no good without the call stack.

**Comment by lifuzhao100** [comment]
@shellscape 
![_20180321181044](https://user-images.githubusercontent.com/16594057/37716851-7063ae5c-2d5a-11e8-85dc-493d5edf1105.png)

**Comment by shellscape** [comment]
That's an error in webpack itself, not something that `webpack-serve` is in control of. There's nothing strange about your config so it must be something in your app code or environment that isn't playing nice with webpack's HMR.

**Comment by lifuzhao100** [comment]
@shellscape thanks!!!i am sorry to find that this err occurs when i add HotModuleReplacement Plugin to configure files.once i rm it, it works well.
