### ISSUE TITLE
stats is ignored

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack-contrib/webpack-serve#70]
* Operating System: Win 10
* Node Version: 9.x
* NPM Version: 5.x
* webpack Version: 4.2
* webpack-serve Version: 0.2

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve ... # remove this block if using the API
```

##### webpack.config.js

```js
  {
    // ...
    stats: 'none'
  }
```

### Expected Behavior

Respect the setting. Don't show logs.

### Actual Behavior

Default logs are shown.

### How Do We Reproduce?

Added `stats: 'none'` to https://github.com/donaldpipowitch/pipo-scripts/blob/master/packages/pipo-scripts/build.js#L61, but it uses `yarn` 🙈

**Comment by shellscape** [comment]
@donaldpipowitch which log output is being shown? paste?

**Comment by donaldpipowitch** [comment]
Here is an example :) https://github.com/donaldpipowitch/webpack-serve-issue-70-demo

**Comment by shellscape** [comment]
Thanks for the output in the README there, very helpful. That's going to be an issue with `webpack-dev-middleware` unfortunately. There may be something wonky going on there. For poops and giggles, can you reproduce that in `webpack-dev-server`?  This is the only thing we're doing with `stats` in this repo: https://github.com/webpack-contrib/webpack-serve/blob/f1aad5805ce5dea5afe9cc609bf5e7a7d2c131b1/index.js#L46-L61

**Comment by shellscape** [comment]
@donaldpipowitch ping

**Comment by donaldpipowitch** [comment]
Hi! Sorry, I'm currently sick. I think I need some more days before I can look into that again. Thanks. ✌️

**Comment by donaldpipowitch** [comment]
No problem. Thank you :)

**Comment by jdart** [comment]
If I add `options.dev = { stats: 'minimal' };` before the [getServer call](https://github.com/webpack-contrib/webpack-serve/blob/master/index.js#L63) stats are minimal... maybe passing stats should happen in options.js?
```
    if (configs[0].stats) {
      options.dev.stats = configs[0].stats;
    }
```

**Comment by jdart** [comment]
For sure I'm fuzzy on the relationship. I'm using a webpack.config.js that looks like the one from @donaldpipowitch, and running `webpack-serve` on the command line. Webpack won't allow a key "dev" ` - configuration has an unknown property 'dev'`. I tried running `webpack-serve --dev '{"stats": "minimal"}'` but it fails with `TypeError: Cannot create property 'publicPath' on string '{"stats": "minimal"}'`.

**Comment by jdart** [comment]
I found creating a .serverc.json with the below content works:
```
{
    "dev": {
        "stats": "minimal",
        "publicPath": "/"
    }
}
```

But adding the below to webpack.config.js does not work:
```    
serve: {
        dev: {
            stats: 'minimal',
            publicPath: '/'
        }
    },
```

**Comment by donaldpipowitch** [comment]
In case anyone sees this issue from googling it, since `webpack-serve@^2.0.0` the webpack config should look like this:

```
{
  serve: {
    devMiddleware: {
      stats: {}
    }
  }
}
```
