### ISSUE TITLE
Support for WriteFilePlugin or similar?

### ISSUE THREAD

**Issue by grillorafael** [webpack-contrib/webpack-serve#71]
* Operating System: Debian 9.4
* Node Version: 8.9.4
* NPM Version: 5.6.0
* webpack Version: 4.2.0
* webpack-serve Version: 0.2.0

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

Hi All,

I did not find this in Docs but is there way to achieve the same behaviour as in `webpack-dev-server` +  https://github.com/gajus/write-file-webpack-plugin ?

##### CLI Command

```console
webpack-serve webpack.config.js
```

##### webpack.config.js
https://gist.github.com/grillorafael/cb81aaf15073420dbf995d43e8834cfe

In the config you have the same settings I had with `webpack-dev-server` that was working just fine for me. So it was generating the files under `../public/v2` and then I was serving through a Play Framework website.

### Expected Behavior
To write the dev files into a specified folder similar to what webpack-dev-server does

### Actual Behavior
Nothing is written anywhere

### New Feature Use Case
To run webpack-serve in parallel with another website.

Website binds to `:9000` and serves a given folder that have the react app but it gets updated with hot module reload through webpack-serve

**Comment by shellscape** [comment]
You chose to ignore the warning in the issue template and removed a bunch of useful sections! Sad panda 🐼  If you edit your issue to include the sections you removed, we'll reopen this.

**Comment by grillorafael** [comment]
Issue updated

**Comment by grillorafael** [comment]
:+1:

**Comment by shellscape** [comment]
@grillorafael in the mean time, I took another look at the plugin source code, and you should be able to add that path in the `content` option to access the files it outputs to disk.

**Comment by shellscape** [comment]
@grillorafael https://github.com/webpack/webpack-dev-middleware/pull/287 is in progress and will allow for this directly in `webpack-dev-middleware` (and the `dev` option in `webpack-serve`) when that is merged.
