### ISSUE TITLE
Cannot find module './lib/HotClientError' error on webpack v4

### ISSUE THREAD

**Issue by dangodev** [webpack-contrib/webpack-serve#74]
* Operating System: MacOS High Sierra
* Node Version: 9.8.0
* NPM Version: 5.6.0
* webpack Version: 4.2.0
* webpack-serve Version: 0.20.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

No config set; attempting to read `src/index.js`

##### webpack.config.js

(none)

### Expected Behavior

Running

### Actual Behavior

```
module.js:545
    throw err;
    ^

Error: Cannot find module './lib/HotClientError'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (/Users/drew/Sites/webpack-serve/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/drew/Sites/webpack-serve/node_modules/webpack-hot-client/index.js:5:24)
    at Module._compile (/Users/drew/Sites/webpack-serve/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

### How Do We Reproduce?
Bug repro here: https://github.com/dangodev/webpack-serve-example

**Comment by shellscape** [comment]
> at Object.<anonymous> (/Users/drew/Sites/webpack-serve/node_modules/webpack-hot-client/index.js:5:24)
    
That's a webpack-hot-client error. Please take a closer look at your stack traces moving forward.

**Comment by dangodev** [comment]
@shellscape Should I open an error on the main webpack repo, then? Or am I missing a required config not specified in the instructions?

**Comment by dangodev** [comment]
@shellscape Thank you! The latest version 2.1.1 did it for me. Was trying to debug it further but noticed you updated it! 🙏

**Comment by shellscape** [comment]
@dangodev re: your previous comment. D. None of the above

You might consider a primer on Node and NPM modules before wading in much deeper in. As the stack trace (and that particular line I plucked) show, `webpack-hot-client` is an npm module. Looking at that module you can see that it's not in the main webpack repo, nor would a missing file error have anything to do with your webpack config. You can visit the `webpack-hot-client` repo an open an issue, but make sure you've searched the repo first to see if it's already been resolved.

**Comment by dangodev** [comment]
@shellscape again, **thank you** for fixing the bug in that other repo that you maintain, that is required by `webpack-serve`, and broke the default install of `webpack-serve`. I’ll try to open up a bug on the correct dependency next time :)
