### ISSUE TITLE
html-webpack-plugin doesn't work

### ISSUE THREAD

**Issue by artemirq** [webpack-contrib/webpack-serve#75]
* Operating System: Windows 10 Pro 1703
* Node Version: 9.5.0
* NPM Version: 5.7.1
* webpack Version: 4.2.0
* webpack-serve Version: 0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### Run webpack-serve

https://gist.github.com/artemirq/d705ed78c222f892bebb3202a0b9675a#file-run-js

##### webpack.config.js

https://gist.github.com/artemirq/d705ed78c222f892bebb3202a0b9675a#file-webpack-config-js

##### serve.config.js

https://gist.github.com/artemirq/d705ed78c222f892bebb3202a0b9675a#file-serve-config-js

### Expected Behavior

JS code would be injected in `index.html` via `html-webpack-plugin`. But in `webpack-dev-server` it's normally work

### Actual Behavior

JS code doesn't injected in `index.html`

### How Do We Reproduce?

Use similarly my config(or code) with html-webpack-plugin

**Comment by shellscape** [comment]
Please try one of the support options in the issue template for support questions.

**Comment by artemirq** [comment]
@shellscape Yeah, i sended this question in gitter `webpack`, but there nobody answers questions

**Comment by artemirq** [comment]
@shellscape And if you think that the problem is in the webpack, then no, `html-webpack-plugin` normally work with `webpack-dev-server`

**Comment by artemirq** [comment]
@shellscape You can not help? Can I wrong use `webpack-serve`?

**Comment by shellscape** [comment]
@artemirq please don't post successive messages, edit your prior message instead. `webpack-serve` is not `webpack-dev-server`. unless you can point to a particular cause in the code, then you're asking for support, which we don't provide here. You'll have to be patient and wait for an answer on Gitter or StackOverflow.

**Comment by artemirq** [comment]
@shellscape Sorry, but Github on smartphone doesn't have function to edit messages

**Comment by lili21** [comment]
webpack-serve is trying to replace `webpack-dev-server`. doesn't it means there should works like webpack-dev-server ?
