### ISSUE TITLE
serving routes from the bundle

### ISSUE THREAD

**Issue by HollyPony** [webpack-contrib/webpack-serve#78]
* Operating System: OSX 10.13.3
* Node Version: v9.8.0
* NPM Version: v5.8.0
* webpack Version: v4.1.1 -> webpack-cli v2.0.12
* webpack-serve Version: v0.2.0

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack-serve
```

##### webpack.config.js

```js
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  mode: 'development',
  output: {
    path: path.join(__dirname, '/dist'),
    filename: '[name].[hash].js',
    chunkFilename: '[name].[hash].js'
  },

  module: {
    rules: [{
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules/
    }]
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html',
      inject: 'body'
    })
  ]
}
```

### Expected Behavior

`localhost:8080/my-route` should be serve by my-bundle.js

### Actual Behavior

Reload on `localhost:8080/my-route` goes on `Not Found`

### How Do We Reproduce?

-> https://github.com/HollyPony/webpack-serve-routing-err

- npm i
- npm start
- Go on http://localhost:8080
- Click on route redirection for 'about' -> http://localhost:8080/about
- Refresh the page

FYI: That's was a working behaviour with `webpack-dev-server` but I'm trying to migrate here since last webpack 4 considerations.

Hope it's not a feature 🤞

**Comment by shellscape** [comment]
Well this definitely isn't a bug in this module. webpack-serve is not webpack-dev-server, and many of the quirks of that module are not found in this one. This issue is a support request (self-described as you're looking for help migrating), which we typically close and ask that folks go to Gitter or StackOverflow.

Your answer lies in the README: https://github.com/webpack-contrib/webpack-serve#add-function-parameters. Specifically with the `historyAPIFallback` recipe.

**Comment by HollyPony** [comment]
Digging about this issue it look like a server conf to enable for client-side routing / pushState html5 history feature. There is many information on google but I found I who seems useful here : http://www.madcoder.me/posts/view/5/configure-server-html5-push-state

**Comment by HollyPony** [comment]
You're right, I close for now. Thanks for the advice :)

**Comment by HollyPony** [comment]
FYI: I've made a branch with my answer : https://github.com/HollyPony/webpack-serve-routing-err/tree/answer

Thanks again a lot. The `add` wasn't the clearest answer for me reading the doc :S

**Comment by shellscape** [comment]
If you have suggestions for how to make that clearer, please let us know. We tried to make https://github.com/webpack-contrib/webpack-serve/blob/master/docs/addons/history-fallback.config.js as simple as possible, but there might be room for improvement.
