### ISSUE TITLE
Consider separating CLI and API into separate packages.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [webpack-contrib/webpack-serve#8]
* Operating System: N/A
* Node Version: N/A
* NPM Version: N/A
* webpack Version: N/A
* webpack-serve Version: 0.0.0

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Expected Behavior
`webpack-serve` should not call itself lean if it includes a CLI.

### Actual Behavior
`webpack-serve` includes a CLI.

**Comment by shellscape** [comment]
Closing citing [https://en.wikipedia.org/wiki/Law_of_triviality](https://en.wikipedia.org/wiki/Law_of_triviality). Please don't create additional issues along these lines (#7 qualifies as well).
