### ISSUE TITLE
Bundle files are not injected into index.html

### ISSUE THREAD

**Issue by zalishchuk** [webpack-contrib/webpack-serve#80]
* Operating System: macOS 10.13.3 (17D102)
* Node Version: 9.9.0
* NPM Version: 5.6.0
* webpack Version: 4.3.0
* webpack-serve Version: 0.3.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ cross-env NODE_ENV=development webpack-serve --config webpack.config.dev.js
```

##### webpack.config.js
https://gist.github.com/zalishchuk/389b63ebbf6a4631290c4d268982dcde

### Expected Behavior
Injected files
### Actual Behavior
Files are not injected, everything worked in `webpack-dev-server` (please, do not beat me with sticks).

**Comment by shellscape** [comment]
Remove `new HotModuleReplacementPlugin(),` and read the available docs, examples, and tests next time around (and before posting an issue). These aren't support forums, but there are support options in the issue template. Also of note, the `devServer` options in your config won't have any effect with `webpack-serve`.

**Comment by zalishchuk** [comment]
Everything is cool, but it didn't work, output bundle is not injected anyway. `devServer` option is just a fallback for another command, because `webpack-serve` is not working for me now.

**Comment by shellscape** [comment]
Hint: Where in the docs for this module does it state that it will inject the script into your `index.html` file for you? 😉

**Comment by zalishchuk** [comment]
Is not this the main `html-webpack-plugin` goal to inject files automatically? It just doesn't work with my configuration and I can't find why. I've just a simple configuration and everything works fine.

**Comment by zalishchuk** [comment]
So, I `webpack-serve` is trying to serve `index.html` file from root folder instead of `html-webpack-plugin` generated file, can we have an option to disable serving fucking root files, so we can't do shit like `http://localhost:8080/package.json` and get `package.json` contents?

**Comment by shellscape** [comment]
@zalishchuk language like that is not welcome in this org - this is your one warning. seek support elsewhere, or stick with `webpack-dev-server` as this module does not appear to meet your needs.
