### ISSUE TITLE
Can we have a cli option to change the port of the websocket server?

### ISSUE THREAD

**Issue by alnorth** [webpack-contrib/webpack-serve#82]
On my dev machine 8080 and 8081 are already in use. There's a `--port` option to change 8080 to something else, but it'd be great to have one to change 8081 too.

Happy to write a PR for it if needed.

**Comment by shellscape** [comment]
😞  You removed the issue template despite the warnings in the template. As a result, your issue is invalid and has to be closed. Bummer.

**Comment by alnorth** [comment]
Fine. I'll just use webpack-dev-server then.

**Comment by shellscape** [comment]
Cool 👍  Be aware that all repositories in `webpack-contrib` have the same expectations with regard to issue and pull request templates.
