### ISSUE TITLE
TypeError: Cannot read property 'watchRun' of undefined

### ISSUE THREAD

**Issue by wzup** [webpack-contrib/webpack-serve#84]
Bug?
Your docs do not mention `watchRun` in any form

`CLI`
```
$ node serve.config.js

An error was thrown while starting webpack-serve.
   Error: An error was thrown while initializing Webpack
  TypeError: Cannot read property 'watchRun' of undefined
    at getOptions.then (/home/user/app//node_modules/webpack-serve/index.js:35:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Error: An error was thrown while initializing Webpack
  TypeError: Cannot read property 'watchRun' of undefined
    at getOptions.then (/home/user/app//node_modules/webpack-serve/index.js:35:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Config `serve.config.js`:
```
'use strict';

const serve = require('webpack-serve');
const wpConfig = require('./webpack.config.js');

let serverConfig = {
    hot: true,           // Instruct the client not to apply Hot Module Replacement patches
}

serve({
    options: serverConfig,
    config: wpConfig,
});
```

**Comment by shellscape** [comment]
You chose to ignore the warning in the issue template and removed a bunch of useful sections! Sad panda 🐼 If you edit your issue to include the sections you removed, we'll reopen this.

**Comment by wzup** [comment]
@shellscape What benefit do I get if include all the sections? Will you provide a solution for plugin of yours?

**Comment by shellscape** [comment]
Well, if you would have followed the issue template (like the template instructs you to) then you would have provided your `webpack.config.js` and I would have been able to identify erroneous properties. But you didn't, so I can. If you can't take the time to follow simple instructions so we can help you efficiently, we won't take the time to try. Simple as that.

If you examine the error message you pasted and consider that the property mentioned in the `TypeError` doesn't exist in this repository, you'll arrive at your answer. This is basic debugging.

**Comment by wzup** [comment]
@shellscape 
Fair enough.
I've updated my issue and added up all the missing data

**Comment by shellscape** [comment]
Yes, but it appears you didn't fully grok the second half of my comment:

> If you examine the error message you pasted and consider that the property mentioned in the TypeError doesn't exist in this repository, you'll arrive at your answer.

The problem exists within your `webpack.config.js`. Specifically because you're using `webpack-spritesmith` which is the culprit for throwing the error. See: https://github.com/mixtur/webpack-spritesmith/blob/8e146881c439d4df142bbcd7b7f8f9e8cc8aba2c/lib/Plugin.js#L38

This is pretty basic debugging - look at what doesn't fit and investigate. How did I arrive at this?

**Comment by wzup** [comment]
@shellscape 
Thanks for the tip on how to search for errors 👍

BTW, it was not `webpack-spritesmith` issue. It was an issue of `webpack` itself. Because of its outdated version. I've updated webpack to `^4.4.1` and the initial error has gone away. But many more errors emerged because of all the other modules were outdated too.

So, the solution to initial issue is to update `webpack`.
