### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by wzup** [webpack-contrib/webpack-serve#87]
* Operating System: `Ubuntu 16.04.3 LTS`
* Node Version: `v8.9.4`
* NPM Version: `5.6.0`
* webpack Version: `2.2.1`
* webpack-serve Version: `^0.3.0`

This issue is for a:

- [ ] **bug**
- [x] **modification** request
- [ ] **feature** request

### New Feature Use Case
First,
There is a mismatch in docs on what is returned by `serve` function.
1) Returns an {Object} containing... https://github.com/webpack-contrib/webpack-serve#serveoptions
2) But here you show that a promise is returned, not an object https://github.com/webpack-contrib/webpack-serve#serveoptions
```
serve({ config }).then((server) => {
  server.on('listening', () => {
    console.log('happy fun time');
  });
});
```

Second,
Mismatch on structure of options passed to `serve` function 
1) `serve({ config })` means `serve({ config: {...wpconfig...} })`
2) `serve([options])` means `serve({...})`

So, above means that the stucture should be as follows. And this is wrong - all options in one object. It throws:
```
serve({
    config: { webpack config },
    ...all other webpack-serve options
})
```

And for some reason this doesn't throw. But it doesn't match plugin's docs
```
serve({
    config: { webpack config },
    options: { ...all other webpack-serve options }
})
```

**Comment by shellscape** [comment]
_(as an aside, please stop putting spaces in the checkboxes. the issue template does note not to. it won't render the checkboxes properly when you do)_

> Returns an {Object} containing...

Correct, that should read `Returns a {Promise} which returns an {Object} containing`

> Mismatch on structure of options passed to serve function

That is not correct. See: https://github.com/webpack-contrib/webpack-serve/blob/master/lib/options.js#L9. It looks like you may have a misunderstanding of how restructuring works in newer Node versions.

Also of note: Only webpack v4+ is supported by this module.
