### ISSUE TITLE
Node v7.6.0 required at install.

### ISSUE THREAD

**Issue by tech4him1** [webpack-contrib/webpack-serve#88]
* Operating System: All
* Node Version: v6.14.1
* NPM Version: Yarn v1.3.2
* webpack Version: v4
* webpack-serve Version: v0.3.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [x] **modification** request

### Expected Behavior
`webpack-serve` can be installed on Node v6 systems.

### Actual Behavior
Currently, `webpack-serve` cannot be installed with Yarn on a Node v6 system because `@shellscape/koa-static` specifies only v7.6.0 or greater. It will also warn when installed with NPM. Since you've added Node v6 support to the module, can the package.json be updated as well?

```
error @shellscape/koa-static@4.0.4: The engine "node" is incompatible with this module. Expected version ">= 7.6.0".
```

### How Do We Reproduce?

Run `yarn add webpack-serve` on a Node.JS v6 system.

**Comment by tech4him1** [comment]
I've created a PR at https://github.com/shellscape/koa-static/pull/1.

**Comment by tech4him1** [comment]
Thanks, haha. NPM still warns on every install, so Yarn's not completely biased in this case 😄

**Comment by shellscape** [comment]
@shellscape/koa-static v4.0.5 published

**Comment by tech4him1** [comment]
@shellscape Sorry, would you mind doing it for `koa-send` as well. https://github.com/shellscape/koa-send/pull/1

**Comment by shellscape** [comment]
Sure, but probably gonna have to wait until after the Easter holiday.

**Comment by tech4him1** [comment]
friendly bump since the issue is closed
