### ISSUE TITLE
serve.client/serve.server options not correctly used by webpack-serve

### ISSUE THREAD

**Issue by jonesnc** [webpack-contrib/webpack-serve#89]
* Operating System: Mac OS X, Docker Machine with Docker v18.03.0-ce, boot2docker VM, Debian 8.10 container OS
* Node Version: 9.10.0
* NPM Version: 5.6.0
* webpack Version: 4.4.1
* webpack-serve Version: 0.3.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  webpack-serve --config webpack.config.babel.js
```

##### webpack.config.babel.js

[https://gist.github.com/jonesnc/e5afd75691fbb92172b02f7a490bd240](https://gist.github.com/jonesnc/e5afd75691fbb92172b02f7a490bd240)

### Expected Behavior
Webpack-serve tells `webpack-hot-client` to listen at my webpack config's `serve.host.client` value, which is set to `192.168.64.7` in the gist linked above. Webpack-serve will run the project at `http://0.0.0.0`, and use the port used should be `serve.port`, which is `8500`.
### Actual Behavior
I get the following messages in the console:
```
⚠ ｢hot｣: `options.host.client` does not match `options.host.server`. This can cause unpredictable behavior in the browser.
ℹ ｢hot｣: webpack: Compiling...
ℹ ｢serve｣: Project is running at http://[object Object]:32985
⚠ ｢serve｣: Failed to copy server URI to clipboard. Use logLevel: 'debug' for more information.
ℹ ｢hot｣: WebSocket Server Listening at 0.0.0.0:44261
```
### How Do We Reproduce?
Create a directory with the webpack I included, install the packages versions I described and run `webpack-serve --config webpack.config.babel.js`. This behavior was observed within a `docker-machine` environment, but I suspect `webpack-serve` will behave in a similar way.

**Comment by evaera** [comment]
Problem line appears to be here: https://github.com/webpack-contrib/webpack-serve/blob/83577936b95c02176028e38c0ffa65c2e4d27df8/lib/server.js#L116

Looks like get-port detects the port as being in-use and gives a random port number, even though the port isn't in use until webpack-serve is started.

**Comment by shellscape** [comment]
@evaera that's not the problem. look at the console output and you'll glean the cause of the issue.

@jonesnc this is a conflict between the update to `webpack-hot-client` and `webpack-serve`, and also a docs snafu. I'll try and get a fix in later today.

**Comment by nmschulte** [comment]
I believe you can still achieve the behavior by passing that object to `webpack-serve`'s [`hot` option](https://github.com/webpack-contrib/webpack-serve#hot):
```
{
  host: '0.0.0.0',
  hot: {
    host: {
        server: ''0.0.0.0',
        client: 'localhost'
    }
  }
}
```

**Comment by evaera** [comment]
@nmschulte That would work but webpack-serve enforces that host and hot.host match :(

```
An error was thrown while starting webpack-serve.
   Error: webpack-serve: The `hot.host` property must match `host` option.
```

**Comment by shellscape** [comment]
And that's why a patch is needed.

**Comment by jonesnc** [comment]
When I do the following, which I think is the correct config for my dev environment:

```
serve:
   { host: '0.0.0.0',
     hot: { server: '192.168.64.7', client: '0.0.0.0' } } }
```

gives me this error

```
TypeError: server.on is not a function
    at addListeners (/usr/local/share/.config/yarn/global/node_modules/webpack-hot-client/node_modules/ws/lib/websocket-server.js:310:48)
    at new WebSocketServer (/usr/local/share/.config/yarn/global/node_modules/webpack-hot-client/node_modules/ws/lib/websocket-server.js:77:31)
    at module.exports (/usr/local/share/.config/yarn/global/node_modules/webpack-hot-client/index.js:63:15)
    at fn (/usr/local/share/.config/yarn/global/node_modules/koa-webpack/index.js:84:32)
    at Object.webpack (/usr/local/share/.config/yarn/global/node_modules/webpack-serve/lib/server.js:32:25)
    at Promise.all.then (/usr/local/share/.config/yarn/global/node_modules/webpack-serve/lib/server.js:127:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
Error: An error was thrown while initializing koa-webpack
 TypeError: server.on is not a function
    at Object.webpack (/usr/local/share/.config/yarn/global/node_modules/webpack-serve/lib/server.js:43:15)
    at Promise.all.then (/usr/local/share/.config/yarn/global/node_modules/webpack-serve/lib/server.js:127:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**Comment by evaera** [comment]
You have to pass `host` inside `hot`, like: 

```
hot: {
    hot: false,
      server: '0.0.0.0',
      client: 'localhost',
    }
  },
```

**Comment by jonesnc** [comment]
@evaera ah, thank you. After updating `hot` to the correct structure, I'm also getting 

The `hot.host` property must match `host` option.

**Comment by jonesnc** [comment]
@shellscape would the patch be as straightforward as changing [this section of code](https://github.com/webpack-contrib/webpack-serve/blob/83577936b95c02176028e38c0ffa65c2e4d27df8/lib/options.js#L177) from

```
if (options.hot) {
      if (options.hot.host && options.host && options.hot.host !== options.host) {
        throw new Error('webpack-serve: The `hot.host` property must match `host` option.');
      } else if (!options.hot.host) {
        options.hot.host = options.host;
      }
}
```

to

```
if (options.hot && !options.hot.host) {
    options.hot.host = options.host;
}
```

Because, if so, I can submit a PR.

**Comment by shellscape** [comment]
That would be a big negative.
