### ISSUE TITLE
Consider removing `update-notifier`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [webpack-contrib/webpack-serve#9]
* Operating System: N/A
* Node Version: N/A
* NPM Version: N/A
* webpack Version: N/A
* webpack-serve Version: 0.0.0

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Expected Behavior
`webpack-serve` should not include large packages unnecessary for its use case.

### Actual Behavior
`webpack-serve` includes `update-notifier`.

**Comment by shellscape** [comment]
Thanks for checking in but it stays.
