### ISSUE TITLE
Your software should pass `configuration.output.publicPath` to `dev` options

### ISSUE THREAD

**Issue by catamphetamine** [webpack-contrib/webpack-serve#95]
For all coming from Google here.
Do it like this:

```js
// network path for static files: fetch all statics from webpack development server
configuration.output.publicPath = `http://${application_configuration.webpack.devserver.host}:${application_configuration.webpack.devserver.port}${configuration.output.publicPath}`

// `webpack-serve` settings.
configuration.serve =
{
	port : application_configuration.webpack.devserver.port,
	dev  :
	{
		publicPath : configuration.output.publicPath
	}
}
```

This software should automatically detect `output.publicPath` in webpack configuration and pass it to webpack dev middleware as an option.

I'm closing this and not reading any comments.

**Comment by catamphetamine** [comment]
And also `headers : { 'Access-Control-Allow-Origin': '*' }` must be set for dev-server otherwise it won't hot-reload anything.

**Comment by jonesnc** [comment]
@catamphetamine Could you elaborate on where you placed `headers : { 'Access-Control-Allow-Origin': '*' }`? I'm having a similar issue.
